import React from 'react';
import { Image, Pressable, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import * as Haptics from 'expo-haptics';
import { makeStyles, useScheme } from '../theme/theme';

/**
 * The six places you can be.
 *
 * Home was a stack of eight rows, which is a menu rather than a product: nothing
 * was ranked, so everything competed. A tab bar says what matters (learn), keeps
 * the rest one tap away, and gets achievements, twins, plan and account off the
 * front page and into a profile where they belong.
 *
 * Icons are drawn rather than pulled from an icon set, because a lightning bolt
 * and a breadboard say Ohmlet and a generic glyph set says nothing.
 *
 * NO CAPTIONS, since 2026-08-29. Each tab used to carry its name in 11px under
 * the icon. Faith asked for the same treatment the top strip got: take the words
 * away and let the icons be big enough to speak. The words were not carrying
 * meaning the artwork did not already carry, and they were holding every icon
 * down to 30pt in a bar that had room for more.
 *
 * The caption WAS carrying one thing, and it was not visual: the tab's name for
 * anyone who cannot see the picture. That moved to `accessibilityLabel` on the
 * Pressable, which unlike a plain View is an accessibility element already, so
 * the label is read rather than merely present.
 */

/**
 * ── The `off` set still wants dark artwork ──
 *
 * The unselected icons are ink OUTLINES over light fills, drawn against a white
 * bar. On the dark bar (#171b24) the outline half of that has nowhere to go:
 * `learn` reads as a smudge and `plans` all but disappears, while `practice`,
 * `live` and `profile` survive on their filled shapes alone.
 *
 * `tintColor` is not the fix and was tried: it recolours EVERY opaque pixel, so
 * the icons that read on dark do so because they are filled, and tinting turns
 * exactly those into solid blobs. The strokes have to be re-drawn light, which
 * means six new sources through scripts/export-nav-icons.py, not a prop.
 *
 * The `on` set needs nothing: it carries its own cream plate and reads on both.
 */

/**
 * 40, and the artwork is now authored for it.
 *
 * The set was 30/60/90px, so 34pt was already asking a 3x screen for 102 pixels
 * and getting 90. Soft edges absorbed it, but it was the ceiling. The 512px
 * sources were in frontend/assets-source/nav all along, so nothing had to be
 * redrawn: mobile/scripts/export-nav-icons.py cuts them again at 40/80/120 and
 * preserves each icon's existing ink fraction rather than the source's own
 * framing, which is what keeps an `off` state and its `on` state the same visual
 * weight.
 *
 * To go further, run that script with a bigger number. The sources hold up to
 * about 170pt before THEY are the limit.
 */
const ICON = 40;

/**
 * The tab icons are painted artwork, one file per state.
 *
 * They were five SVG paths drawn here. The comment above used to argue that
 * drawing them beat pulling from an icon set, because a lightning bolt from a
 * pack is somebody else's lightning bolt. That reasoning was right and the
 * result still was not Ohmlet's: Faith's words for the old Practice icon were
 * "very, very rudimentary". Hand-drawn generic is still generic.
 *
 * Every one now carries the electronics idea. The graduation cap's tassel is a
 * resistor, Practice is a breadboard with a real component across it, Live is a
 * camera with a lit indicator, Community wires three people together, Profile
 * has a component at the collar.
 *
 * Two files each. The selected state is not a tint of the unselected one: it is
 * its own drawing, with the gold plate built into the art. That is why `slotOn`
 * is gone from the styles below, and why the two states must stay the same
 * scale as each other, which is enforced by generating both from one source
 * normalised on its LINEWORK rather than its canvas. Scale the icon on tap and
 * the whole bar twitches.
 */
/**
 * Three sources per tab, not two.
 *
 * The unselected art is ink outlines over light fills, drawn against a white
 * bar. On the dark bar (#171b24) that ink is nearly the bar's own value: `learn`
 * reads as a smudge and `plans` all but disappears. `practice` and `live`
 * survive on their filled shapes, which is luck rather than design.
 *
 * `tintColor` was tried and rejected. It recolours every opaque pixel, so the
 * icons that survive do so precisely because they are filled, and tinting turns
 * exactly those into blobs.
 *
 * `-offdark` is generated by `scripts/export-nav-icons-dark.py`, which flips
 * HSV value and leaves hue, saturation and alpha alone. Ink becomes a light
 * stroke, the light fills recede toward the bar, and the silhouette is identical
 * because alpha is untouched. That is the same swap the palette makes elsewhere.
 *
 * The SELECTED art needs no variant: it carries its own cream plate, which is
 * what a selected state is for, and it reads on either bar.
 */
const TAB_ART = {
  learn: { off: require('../../assets/nav/learn-off.png'), offDark: require('../../assets/nav/learn-offdark.png'), on: require('../../assets/nav/learn-on.png') },
  practice: { off: require('../../assets/nav/practice-off.png'), offDark: require('../../assets/nav/practice-offdark.png'), on: require('../../assets/nav/practice-on.png') },
  live: { off: require('../../assets/nav/live-off.png'), offDark: require('../../assets/nav/live-offdark.png'), on: require('../../assets/nav/live-on.png') },
  community: { off: require('../../assets/nav/community-off.png'), offDark: require('../../assets/nav/community-offdark.png'), on: require('../../assets/nav/community-on.png') },
  profile: { off: require('../../assets/nav/profile-off.png'), offDark: require('../../assets/nav/profile-offdark.png'), on: require('../../assets/nav/profile-on.png') },
  // The mascot with its tool belt, from Faith, 2026-08-30. The only full-colour
  // icon in the bar in BOTH states, and deliberately: the other five are ink
  // linework until selected, so the one tab that asks for money is the one that
  // catches the eye. Its plate is composited into the `on` file to the same
  // measurements as the painted set, 10% inset and an 18% corner radius on a
  // flat #fff6d6 with no outline, because a mascot has no plate of its own.
  plans: { off: require('../../assets/nav/plans-off.png'), offDark: require('../../assets/nav/plans-offdark.png'), on: require('../../assets/nav/plans-on.png') },
} as const;

export const TAB_ICONS = TAB_ART;



export interface TabItem {
  key: keyof typeof TAB_ICONS;
  /**
   * No longer drawn on screen. It is the tab's ACCESSIBLE NAME, which is the
   * job the caption was actually doing: a row of six pictures with nothing said
   * about them is not navigable by anyone who cannot see the pictures.
   */
  label: string;
  onPress: () => void;
}

export const TabBar: React.FC<{ items: TabItem[]; active: string }> = ({ items, active }) => {
  const s = useS();
  const scheme = useScheme();
  const insets = useSafeAreaInsets();
  return (
      <View style={[s.bar, { paddingBottom: Math.max(insets.bottom, 10) }]}>
        {items.map((item) => {
          const on = item.key === active;
          return (
            <Pressable
              key={item.key}
              onPress={() => {
                void Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
                item.onPress();
              }}
              style={s.tab}
              accessibilityRole="tab"
              accessibilityState={{ selected: on }}
              accessibilityLabel={item.label}
            >
              {/* The active tab gets a filled plate behind its icon. A colour swap
                  on a hairline row is not enough signal to find yourself by, and
                  it is the only signal left now the captions have gone. */}
              <View style={s.slot}>
                <Image
                  source={TAB_ART[item.key][on ? 'on' : scheme === 'dark' ? 'offDark' : 'off']}
                  style={s.icon}
                  resizeMode="contain"
                  accessibilityIgnoresInvertColors
                />
              </View>
            </Pressable>
          );
        })}
      </View>
    );
};

const useS = makeStyles((colors, th) => ({
  bar: {
    flexDirection: 'row',
    backgroundColor: colors.surface,
    // A real edge, not a hairline. The bar is app chrome and should read as a
    // surface the content sits above, which a 0.5px line does not achieve.
    borderTopWidth: 2,
    borderTopColor: colors.line,
    paddingTop: 4,
    ...th.elevation.overlay,
  },
  tab: { flex: 1, alignItems: 'center', paddingVertical: 2 },
  slot: {
    width: ICON + 10, height: ICON + 2,
    alignItems: 'center', justifyContent: 'center',
  },
  icon: { width: ICON, height: ICON },
}));
