import type { LessonScript } from '../types';

/**
 * Unit 5, Inputs, Outputs & Code. Checkpoint for "Analog & PWM".
 *
 * PWM is the one idea in the unit that a still picture actively misleads you
 * about: the pin is never at half voltage, and a diagram of "half brightness"
 * suggests it is. The waveform with its average line is the whole lesson.
 */
export const analogPwm: LessonScript = {
  id: 'analog-pwm',
  title: 'Analog and PWM',
  unitTitle: 'Inputs, Outputs & Code',
  unitId: 'inputs-outputs',
  skillId: 'analog-pwm',
  skillTitle: 'Analog & PWM',
  accent: '#ff6f5e',
  segments: [
    { text: 'A digital pin has two states. So how does an Arduino dim an LED to exactly one third brightness?',
      scene: { kind: 'title' } },
    { text: 'First, the easy direction. Reading an analog voltage in.',
      scene: { kind: 'formula', expr: 'analogRead(A0);' } },
    { text: 'That measures the voltage on an analog pin and gives you a number from nought to one thousand and twenty three.',
      scene: { kind: 'circuit', variant: 'divider', flow: true, highlight: 'tap', label: 'A voltage becomes a number' } },
    { text: 'Two and a half volts reads about five hundred and twelve. Three volts reads about six hundred and fourteen.',
      scene: { kind: 'formula', expr: '3.0V → 614' } },
    { text: 'And analog inputs need no pinMode. They are inputs already, and analogRead just works.',
      scene: { kind: 'statement', lines: ['No pinMode', 'needed here'] } },
    { text: 'Now the hard direction. Getting a level out of a pin that only knows two levels.',
      scene: { kind: 'statement', lines: ['Two levels out.', 'That is all.'] } },
    { text: 'Here is the trick. Switch the pin on and off very fast, and change how long it spends on.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'pwm50 avg', label: 'On half the time' } },
    { text: 'That fraction is called the duty cycle. On half the time is fifty percent duty.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'pwm50 avg', label: '50% duty' } },
    { text: 'A quarter of the time is twenty five percent, and the average sits at a quarter of five volts.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'pwm25 avg', label: '25% duty' } },
    { text: 'Three quarters of the time and the average is nearly four volts.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'pwm75 avg', label: '75% duty' } },
    { text: 'This is pulse width modulation, and the function that does it has a slightly misleading name.',
      scene: { kind: 'formula', expr: 'analogWrite(LED, 128);' } },
    { text: 'The value runs nought to two hundred and fifty five. Nought is off, two five five is full on.',
      scene: { kind: 'formula', expr: '0 = off, 255 = full' } },
    { text: 'One hundred and twenty eight is about half, which averages to about two and a half volts.',
      scene: { kind: 'formula', expr: '128 of 255 → ~2.5V avg' } },
    { text: 'But be clear about what is happening, because this is where people go wrong later.',
      scene: { kind: 'statement', lines: ['Be clear', 'about this'] } },
    { text: 'The pin is never at two and a half volts. It is at five, then nought, then five, hundreds of times a second.',
      scene: { kind: 'compare', left: 'Average: 2.5V', right: 'Actual: 0V or 5V', caption: 'Only one of these is on the wire' } },
    { text: 'On an Uno it switches at about four hundred and ninety hertz on most pins.',
      scene: { kind: 'formula', expr: '~490Hz on most pins' } },
    { text: 'Your eye blends anything faster than about twenty flashes a second, so an LED looks smoothly dimmed.',
      scene: { kind: 'statement', lines: ['Your eye does', 'the averaging'] } },
    { text: 'A motor blends it too, because it is too heavy to speed up and slow down that fast.',
      scene: { kind: 'statement', lines: ['A motor is', 'too heavy to notice'] } },
    { text: 'But a voltmeter also averages, which is why a meter on a P W M pin lies to you convincingly.',
      scene: { kind: 'statement', lines: ['Your meter', 'averages too'] } },
    { text: 'Only some pins can do this. On an Uno they are marked with a squiggle on the board.',
      scene: { kind: 'circuit', variant: 'board', flow: false, highlight: 'digital', label: 'Only the marked pins' } },
    { text: 'Call analogWrite on a plain pin and you get fully on or fully off, and nothing in between.',
      scene: { kind: 'statement', lines: ['Wrong pin,', 'no dimming'] } },
    { text: 'One more output worth knowing, because it uses frequency rather than duty.',
      scene: { kind: 'formula', expr: 'tone(BUZZER, 1000);' } },
    { text: 'Tone switches a pin at whatever frequency you ask, in hertz, and a piezo buzzer turns that into a pitch.',
      scene: { kind: 'statement', lines: ['Frequency in,', 'pitch out'] } },
    { text: 'Four hundred and forty hertz is a concert A. Two thousand is a shrill beep you cannot ignore.',
      scene: { kind: 'compare', left: '440Hz: a note', right: '2000Hz: an alarm', caption: 'Pick one for your build' } },
    { text: 'And noTone stops it, because tone keeps running in the background until you say otherwise.',
      scene: { kind: 'statement', lines: ['tone runs on', 'until you stop it'] } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. analogRead turns a voltage into nought to one thousand and twenty three, with no pinMode needed.',
      scene: { kind: 'recap', items: ['analogRead: voltage to 0 to 1023'] } },
    { text: 'Two. analogWrite is P W M, nought to two five five, and the pin only ever sits at nought or five volts.',
      scene: { kind: 'recap', items: ['analogRead: voltage to 0 to 1023', 'PWM averages, it does not level'] } },
    { text: 'Three. Only the marked pins do P W M, and tone sets frequency rather than duty.',
      scene: { kind: 'recap', items: ['analogRead: voltage to 0 to 1023', 'PWM averages, it does not level', 'Marked pins only, and tone is frequency'] } },
    { text: 'Go and fade an LED from nought to two five five, and watch where it stops looking linear.',
      scene: { kind: 'outro' } },
  ],
};
