import type { LessonScript } from '../types';

/**
 * Unit 2, On the Breadboard. Checkpoint for "The Breadboard".
 *
 * A board is a picture, not a sentence, and the connections a learner cannot
 * see are the ones that cost them an evening. The film spends most of its time
 * on the two invisible facts: a row of five is one node, and the ravine cuts
 * every row in half.
 */
export const breadboarding: LessonScript = {
  id: 'breadboarding',
  title: 'The Breadboard',
  unitTitle: 'On the Breadboard',
  unitId: 'breadboard',
  skillId: 'breadboarding',
  skillTitle: 'The Breadboard',
  accent: '#549cf0',
  segments: [
    { text: 'A breadboard looks like a grid of identical holes. It is nothing of the kind.',
      scene: { kind: 'title' } },
    { text: 'Underneath the plastic there are metal strips, and they connect the holes in a fixed pattern.',
      scene: { kind: 'circuit', variant: 'breadboard', flow: false, label: 'Strips under the plastic' } },
    { text: 'Down each long edge run the power rails.',
      scene: { kind: 'circuit', variant: 'breadboard', flow: true, highlight: 'rails', label: 'The power rails' } },
    { text: 'Every hole along one rail is joined to every other hole on that rail, the whole length of the board.',
      scene: { kind: 'statement', lines: ['One rail is', 'one long node'] } },
    { text: 'There is a red stripe and a blue one. Red carries positive by convention, blue carries ground.',
      scene: { kind: 'statement', lines: ['Red positive.', 'Blue ground.'] } },
    { text: 'The rails on opposite sides are not joined to each other. If you want them joined, you jumper them.',
      scene: { kind: 'statement', lines: ['Two sides,', 'two separate buses'] } },
    { text: 'In the middle, the board is arranged in rows of five.',
      scene: { kind: 'circuit', variant: 'breadboard', flow: false, highlight: 'row', label: 'A row of five' } },
    { text: 'Those five holes are one connected strip. Put a leg in any one of them and it is the same electrical point.',
      scene: { kind: 'statement', lines: ['Five holes,', 'one point'] } },
    { text: 'And down the centre runs a gap. That gap cuts every row in half.',
      scene: { kind: 'circuit', variant: 'breadboard', flow: false, highlight: 'ravine', label: 'The gap cuts every row' } },
    { text: 'The five holes on one side are one strip. The five on the other side are a completely different strip.',
      scene: { kind: 'statement', lines: ['Same number.', 'Different node.'] } },
    { text: 'That gap is not decoration. It exists so a chip can straddle it with its two rows of pins kept apart.',
      scene: { kind: 'statement', lines: ['It is there', 'for chips'] } },
    { text: 'Now the mistake almost everybody makes on their first build.',
      scene: { kind: 'statement', lines: ['The first', 'mistake'] } },
    { text: 'Both legs of a component pushed into the same row of five.',
      scene: { kind: 'circuit', variant: 'breadboard', flow: false, highlight: 'deadrow', label: 'Both legs, one row' } },
    { text: 'The row joins them together, so you have wired the component straight to itself. It is short circuited.',
      scene: { kind: 'statement', lines: ['Wired to itself.', 'Shorted out.'] } },
    { text: 'A resistor like that does nothing at all. An LED like that never lights, and the board looks perfect.',
      scene: { kind: 'compare', left: 'Different rows', right: 'Same row', caption: 'Only one of these is a circuit' } },
    { text: 'So the rule is short. A component’s two legs always go in two different rows.',
      scene: { kind: 'statement', lines: ['Two legs,', 'two rows'] } },
    { text: 'Wire next, because the wrong wire will waste your evening.',
      scene: { kind: 'statement', lines: ['Now the wire'] } },
    { text: 'Use solid core wire, about twenty two gauge. It pushes into the hole and stays where you put it.',
      scene: { kind: 'statement', lines: ['Solid core,', '22 gauge'] } },
    { text: 'Stranded wire frays as you push, and half the strands end up bent outside the hole.',
      scene: { kind: 'compare', left: 'Solid core', right: 'Stranded', caption: 'One of these actually goes in' } },
    { text: 'Keep the jumpers short and flat against the board.',
      scene: { kind: 'circuit', variant: 'breadboard', flow: true, highlight: 'rails', label: 'Short, flat, traceable' } },
    { text: 'That is not tidiness for its own sake. A flat board can be read at a glance, a nest of arcs cannot.',
      scene: { kind: 'statement', lines: ['Tidy is', 'debuggable'] } },
    { text: 'Colour code them as well. Red for positive, black for ground, whatever you like for signals.',
      scene: { kind: 'statement', lines: ['Red, black,', 'and your choice'] } },
    { text: 'Electrically the colour means nothing. To you at eleven at night it means everything.',
      scene: { kind: 'statement', lines: ['The colour is', 'for you'] } },
    { text: 'Power the rails first, then take a short jumper from the nearest rail hole to whatever needs it.',
      scene: { kind: 'circuit', variant: 'breadboard', flow: true, highlight: 'rails row', label: 'Rails first, then branch' } },
    { text: 'Do that and every part of your board has power and ground within a centimetre of it.',
      scene: { kind: 'statement', lines: ['Power, everywhere', 'you need it'] } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. A row of five is one connected point, and the centre gap splits every row in two.',
      scene: { kind: 'recap', items: ['A row of five is one point'] } },
    { text: 'Two. A component’s legs must land in different rows, or you have shorted it out.',
      scene: { kind: 'recap', items: ['A row of five is one point', 'Two legs, two rows'] } },
    { text: 'Three. Power the rails first, then keep every jumper short, flat and colour coded.',
      scene: { kind: 'recap', items: ['A row of five is one point', 'Two legs, two rows', 'Rails first, wires flat'] } },
    { text: 'Go and trace a row with your meter on continuity. Then trace across the gap.',
      scene: { kind: 'outro' } },
  ],
};
