import type { LessonScript } from '../types';

/**
 * Unit 12, Comms, Motors & Robotics. Sits at the checkpoint for "Brushless
 * Motors and FOC".
 *
 * Chosen for video because a brushed motor's commutator is a mechanical thing
 * you can see, and its replacement is a piece of software running eight thousand
 * times a second that you cannot. The whole subject is the handover: the brushes
 * did the switching, now the code does, and everything else about a brushless
 * motor follows from that one substitution.
 */
export const brushlessAndFoc: LessonScript = {
  id: 'brushless-and-foc',
  title: 'Brushless Motors and FOC',
  unitTitle: 'Comms, Motors & Robotics',
  unitId: 'comms-motors-robotics',
  skillId: 'brushless-and-foc',
  skillTitle: 'Brushless Motors and FOC',
  accent: '#549cf0',
  segments: [
    { text: 'A brushed motor spins because something inside it keeps reversing the current at exactly the right moment.',
      scene: { kind: 'title' } },
    { text: 'That something is a ring of copper segments with two carbon blocks pressed against it.',
      scene: { kind: 'statement', lines: ['A commutator', 'and two brushes'] } },
    { text: 'It is a mechanical switch that runs at the speed of the motor, and it is brilliantly simple.',
      scene: { kind: 'compare', left: 'Simple: two wires and go', right: 'Wearing: contacts, sparks, dust', caption: 'What brushes cost you' } },
    { text: 'It also wears out, throws sparks, and puts electrical noise into everything nearby.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'noise', label: 'Brush noise' } },
    { text: 'A brushless motor deletes the brushes and gives their job to a processor.',
      scene: { kind: 'statement', lines: ['Delete the brushes.', 'Write the code.'] } },
    { text: 'The magnets move to the rotor. The coils stay still, on the outside, in three sets.',
      scene: { kind: 'compare', left: 'Brushed: coils spin', right: 'Brushless: magnets spin', caption: 'Inside out' } },
    { text: 'Three phases, driven by six transistors arranged as three half bridges.',
      scene: { kind: 'circuit', variant: 'transistor', flow: true, label: 'One of three half bridges' } },
    { text: 'Each half bridge can pull its phase up to the supply, or down to ground. That is all it can do.',
      scene: { kind: 'statement', lines: ['Up, or down.', 'Six switches.'] } },
    { text: 'Switching them in the right order at the right moment IS the commutator now. In software.',
      scene: { kind: 'statement', lines: ['The commutator', 'is now code'] } },
    { text: 'Which means the code has to know where the rotor is. If it guesses wrong, the motor pushes the wrong way.',
      scene: { kind: 'statement', lines: ['It must know', 'where the rotor is'] } },
    { text: 'Cheap drives use three Hall sensors and get the position in six chunks per revolution.',
      scene: { kind: 'circuit', variant: 'board', flow: true, highlight: 'pin', label: 'Six steps per turn' } },
    { text: 'That is trapezoidal control. Energise two phases, wait for the next Hall change, move on.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'square', label: 'Six-step, trapezoidal' } },
    { text: 'It works, it is easy, and it is rough. Torque rises and falls within every one of those six steps.',
      scene: { kind: 'compare', left: 'Simple to write', right: 'Torque ripple you can hear', caption: 'What six steps costs' } },
    { text: 'You hear it as a whine and feel it as cogging at low speed.',
      scene: { kind: 'statement', lines: ['A whine', 'you can hear'] } },
    { text: 'Field oriented control is what you do when six chunks is not good enough.',
      scene: { kind: 'statement', lines: ['Field oriented', 'control'] } },
    { text: 'It starts from one piece of physics. Torque comes from the angle between the rotor field and the stator field.',
      scene: { kind: 'formula', expr: 'torque ∝ sin(θ)', note: 'Maximum at ninety degrees, zero when aligned' } },
    { text: 'At ninety degrees, every amp you push produces the most torque it possibly can.',
      scene: { kind: 'compare', left: '90°: all torque', right: '0°: all heat', caption: 'The same current, twice the result' } },
    { text: 'Aligned, at zero degrees, that same current produces no torque at all. It just heats the motor.',
      scene: { kind: 'statement', lines: ['Same current.', 'No torque.'] } },
    { text: 'So F O C measures the rotor angle continuously, and holds the stator field at ninety degrees to it. Always.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'sine', label: 'Three smooth phases' } },
    { text: 'Not six steps. A continuously rotating field, made of three sine waves a hundred and twenty degrees apart.',
      scene: { kind: 'statement', lines: ['Three sines.', '120 degrees apart.'] } },
    { text: 'The result is smooth torque at any speed, including standstill, and noticeably less heat for the same work.',
      scene: { kind: 'compare', left: 'Six-step: ripple and whine', right: 'FOC: smooth, cooler', caption: 'Why drones and robot joints use it' } },
    { text: 'The price is that it needs a real rotor angle, not six chunks. An encoder, or a resolver, or a good estimator.',
      scene: { kind: 'circuit', variant: 'board', flow: true, highlight: 'chip', label: 'Continuous angle needed' } },
    { text: 'And it needs the current loop to run fast. Ten to twenty thousand times a second, every second.',
      scene: { kind: 'formula', expr: '10–20 kHz current loop', note: 'Measure, transform, correct, repeat' } },
    { text: 'Two safety facts about the six transistors, and they matter more than any of the theory.',
      scene: { kind: 'statement', lines: ['Two safety facts'] } },
    { text: 'First, never let both transistors in one half bridge be on together.',
      scene: { kind: 'circuit', variant: 'transistor', flow: false, highlight: 'gap', label: 'Shoot-through' } },
    { text: 'That is a dead short from supply to ground through two switches. It is called shoot-through and it destroys them.',
      scene: { kind: 'statement', lines: ['A short circuit', 'through your bridge'] } },
    { text: 'The fix is dead time. A deliberate gap where both are off, while the one turning off actually finishes.',
      scene: { kind: 'compare', left: 'Off, then on: safe', right: 'On before off: destroyed', caption: 'Dead time is not optional' } },
    { text: 'Second, a motor spun by hand is a generator. It puts voltage back into your driver whether it is powered or not.',
      scene: { kind: 'circuit', variant: 'flyback', flow: true, label: 'Back EMF, coming home' } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. Brushless moves the commutator into software, and the software must know the rotor angle.',
      scene: { kind: 'recap', items: ['The commutator became code'] } },
    { text: 'Two. Torque follows the sine of the angle between the fields, so F O C holds it at ninety degrees.',
      scene: { kind: 'recap', items: ['The commutator became code', 'Ninety degrees is all the torque'] } },
    { text: 'Three. Dead time on every half bridge, always, or you will replace transistors.',
      scene: { kind: 'recap', items: ['The commutator became code', 'Ninety degrees is all the torque', 'Dead time, every bridge'] } },
    { text: 'Go and spin a brushless motor by hand with a meter across two of its phases, and watch it generate.',
      scene: { kind: 'outro' } },
  ],
};
