import type { LessonScript } from '../types';

/**
 * Unit 2, On the Breadboard. Checkpoint for "Building Circuits".
 *
 * The translation step. A learner who can read a schematic and can use a
 * breadboard still stalls between the two, because they try to make the board
 * LOOK like the drawing. The film says out loud that they are allowed to look
 * nothing alike as long as the nodes match.
 */
export const buildingCircuits: LessonScript = {
  id: 'building-circuits',
  title: 'Schematic to Board',
  unitTitle: 'On the Breadboard',
  unitId: 'breadboard',
  skillId: 'building-circuits',
  skillTitle: 'Building Circuits',
  accent: '#549cf0',
  segments: [
    { text: 'A schematic and a breadboard build are the same circuit seen two completely different ways.',
      scene: { kind: 'title' } },
    { text: 'The schematic says what connects to what. It says nothing at all about where anything sits.',
      scene: { kind: 'circuit', variant: 'led', flow: false, label: 'What connects to what' } },
    { text: 'The board is the physical answer, and there are many correct physical answers.',
      scene: { kind: 'circuit', variant: 'breadboard', flow: false, label: 'One of many right builds' } },
    { text: 'So do not try to make your board look like the drawing. Make the connections match, and stop there.',
      scene: { kind: 'compare', left: 'Same nodes', right: 'Same shape', caption: 'Only one of these is required' } },
    { text: 'Read a schematic node by node. A dot where two wires cross means they are joined.',
      scene: { kind: 'statement', lines: ['A dot means', 'joined'] } },
    { text: 'No dot, and they simply pass over each other. Missing that is a whole evening of confusion.',
      scene: { kind: 'statement', lines: ['No dot means', 'passing over'] } },
    { text: 'Take the simplest real build. Five volts, a resistor, an LED, and back to ground.',
      scene: { kind: 'circuit', variant: 'led', flow: true, label: 'Four connections, that is all' } },
    { text: 'Four connections. Rail to resistor. Resistor to LED anode. LED cathode to the ground rail.',
      scene: { kind: 'statement', lines: ['Rail, resistor,', 'LED, ground'] } },
    { text: 'On the board that becomes a jumper from the plus rail into row ten.',
      scene: { kind: 'circuit', variant: 'breadboard', flow: true, highlight: 'rails', label: 'Plus rail to row ten' } },
    { text: 'The resistor bridges row ten to row twelve. The LED bridges row twelve to row fourteen.',
      scene: { kind: 'circuit', variant: 'breadboard', flow: true, highlight: 'row', label: 'Every part bridges two rows' } },
    { text: 'Then a jumper from row fourteen back to the minus rail, and the loop is closed.',
      scene: { kind: 'statement', lines: ['And the loop', 'is closed'] } },
    { text: 'Notice that every part bridged two different rows. That single check catches most build faults.',
      scene: { kind: 'statement', lines: ['Every part', 'bridges two rows'] } },
    { text: 'Does the order matter? Resistor before the LED, or after it?',
      scene: { kind: 'statement', lines: ['Does the order', 'matter?'] } },
    { text: 'Electrically, no. It is one loop, so the same current flows through both wherever you put them.',
      scene: { kind: 'compare', left: 'R then LED', right: 'LED then R', caption: 'Identical current, either way' } },
    { text: 'What matters is that the resistor is in the loop at all. Its position is your convenience.',
      scene: { kind: 'statement', lines: ['Present matters.', 'Position does not.'] } },
    { text: 'Now build that same branch twice, side by side, off one supply.',
      scene: { kind: 'circuit', variant: 'parallel', flow: true, label: 'The same branch, twice' } },
    { text: 'That is parallel, and it needs one thing that catches people out.',
      scene: { kind: 'statement', lines: ['One thing', 'catches people'] } },
    { text: 'Each LED needs its own resistor. Not one shared resistor feeding both branches.',
      scene: { kind: 'circuit', variant: 'parallel', flow: true, highlight: 'r1 r2', label: 'A resistor in each branch' } },
    { text: 'No two LEDs are quite the same. The one with the lower forward voltage takes more of a shared current.',
      scene: { kind: 'compare', left: 'One each', right: 'One shared', caption: 'Shared means one of them wins' } },
    { text: 'So one is bright and the other is noticeably dim, and nothing about your wiring looks wrong.',
      scene: { kind: 'statement', lines: ['Bright and dim,', 'and wired right'] } },
    { text: 'A resistor per branch sets each current on its own, and the two match.',
      scene: { kind: 'statement', lines: ['Own resistor,', 'own current'] } },
    { text: 'Branch currents add up at the supply. Two branches at twelve milliamps draw twenty four in total.',
      scene: { kind: 'formula', expr: '12mA + 12mA = 24mA' } },
    { text: 'Worth knowing before you put eight LEDs on one microcontroller pin and wonder why it got hot.',
      scene: { kind: 'statement', lines: ['Count the total', 'before you build'] } },
    { text: 'And if one branch fails open, the others do not notice. That is the other gift of parallel.',
      scene: { kind: 'statement', lines: ['One branch dies,', 'the rest run'] } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. Match the connections, not the picture. A dot means joined, no dot means crossing.',
      scene: { kind: 'recap', items: ['Match nodes, not layout'] } },
    { text: 'Two. Every component bridges two different rows, and the order in a loop does not change the current.',
      scene: { kind: 'recap', items: ['Match nodes, not layout', 'Every part bridges two rows'] } },
    { text: 'Three. In parallel, one resistor per branch, and the branch currents add at the supply.',
      scene: { kind: 'recap', items: ['Match nodes, not layout', 'Every part bridges two rows', 'One resistor per branch'] } },
    { text: 'Go and build the same schematic twice, in two different layouts.',
      scene: { kind: 'outro' } },
  ],
};
