import type { LessonScript } from '../types';

/**
 * Unit 12, Comms, Motors & Robotics. Sits at the checkpoint for "The CAN Bus".
 *
 * Chosen for video because arbitration is a RACE, and the resolution of that
 * race happens on the wire rather than in anyone's code. Two nodes transmit at
 * the same instant, both watch the bus, and one of them silently discovers it
 * has lost and stops. Describing that in a quiz makes it sound like a protocol
 * rule. Watching the dominant bit win makes it obvious why it needs no arbiter.
 */
export const canBus: LessonScript = {
  id: 'can-bus',
  title: 'The CAN Bus',
  unitTitle: 'Comms, Motors & Robotics',
  unitId: 'comms-motors-robotics',
  skillId: 'can-bus',
  skillTitle: 'The CAN Bus',
  accent: '#549cf0',
  segments: [
    { text: 'A car has dozens of computers in it, spread across metres of noisy, vibrating, electrically hostile machine.',
      scene: { kind: 'title' } },
    { text: 'C A N is the bus that was built for exactly that, and it makes some unusual choices.',
      scene: { kind: 'statement', lines: ['Built for', 'a hostile place'] } },
    { text: 'The first one is that it does not send voltages. It sends the difference between two wires.',
      scene: { kind: 'circuit', variant: 'board', flow: true, highlight: 'pin', label: 'CAN high, CAN low' } },
    { text: 'C A N high and C A N low, twisted together, and the receiver only ever looks at the gap between them.',
      scene: { kind: 'compare', left: 'Single ended: noise adds', right: 'Differential: noise cancels', caption: 'Why two wires beat one' } },
    { text: 'Noise hits a twisted pair almost equally on both wires. Subtract one from the other and it cancels.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'noise', label: 'Noise on both wires' } },
    { text: 'That is how a signal survives a journey along a wiring loom next to an ignition coil.',
      scene: { kind: 'statement', lines: ['Noise on both.', 'Gone in the difference.'] } },
    { text: 'Second choice. The two bit values are not equal. One of them wins.',
      scene: { kind: 'statement', lines: ['One bit wins'] } },
    { text: 'A zero is dominant. A one is recessive. Any node sending a zero pulls the whole bus to zero.',
      scene: { kind: 'compare', left: 'Dominant 0: pulls the bus', right: 'Recessive 1: lets it float', caption: 'A wired AND across every node' } },
    { text: 'The bus is a wired AND. If everybody sends a one, it reads one. If anybody sends a zero, it reads zero.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'square', label: 'Any zero wins' } },
    { text: 'That asymmetry is the whole trick, because it is what makes arbitration free.',
      scene: { kind: 'statement', lines: ['Arbitration,', 'for free'] } },
    { text: 'C A N has no master. Every node transmits when the bus is idle, and two of them will eventually start together.',
      scene: { kind: 'circuit', variant: 'board', flow: true, label: 'Two nodes, same instant' } },
    { text: 'Every message starts with an identifier, and every transmitter watches the bus while it sends.',
      scene: { kind: 'statement', lines: ['Send a bit.', 'Read the bus.'] } },
    { text: 'Send a recessive one, read back a dominant zero, and you know somebody else is sending too.',
      scene: { kind: 'compare', left: 'Sent 1, read 1: still winning', right: 'Sent 1, read 0: you lost', caption: 'How a node learns it lost' } },
    { text: 'The loser stops immediately and becomes a receiver. No collision. No retry storm. Nothing corrupted.',
      scene: { kind: 'statement', lines: ['No collision.', 'One transmitter left.'] } },
    { text: 'The winner never even noticed. Its message carries on without a single lost bit.',
      scene: { kind: 'statement', lines: ['The winner', 'never noticed'] } },
    { text: 'And because zero is dominant, the lower the identifier, the higher the priority.',
      scene: { kind: 'formula', expr: 'lower ID = higher priority', note: 'A consequence of the wiring, not a rule bolted on' } },
    { text: 'So brakes get a low identifier and the seat heater gets a high one, and the brakes always go first.',
      scene: { kind: 'compare', left: 'ID 0x001: brakes', right: 'ID 0x600: seat heater', caption: 'Priority you choose at design time' } },
    { text: 'Third choice, and it is the one that changes how you think. Messages are not addressed to anybody.',
      scene: { kind: 'statement', lines: ['Nobody is', 'the recipient'] } },
    { text: 'The identifier says what the message IS, not who it is for. Engine speed. Wheel speed. Brake pressure.',
      scene: { kind: 'compare', left: 'Not: node 4 to node 7', right: 'But: this is wheel speed', caption: 'Content, not address' } },
    { text: 'Every node hears every message and filters for the ones it cares about, in hardware.',
      scene: { kind: 'circuit', variant: 'board', flow: true, highlight: 'chip', label: 'Everyone hears, hardware filters' } },
    { text: 'Add a new dashboard that wants wheel speed and you change nothing on the sender. It was already broadcasting.',
      scene: { kind: 'statement', lines: ['Add a listener.', 'Change nothing.'] } },
    { text: 'Now the physical layer, because this is where most benches fail.',
      scene: { kind: 'statement', lines: ['Where benches', 'actually fail'] } },
    { text: 'A C A N bus is a line, not a star. One trunk, with the nodes on short stubs off it.',
      scene: { kind: 'compare', left: 'Line with short stubs', right: 'Not a star', caption: 'The topology is not optional' } },
    { text: 'And it needs one hundred and twenty ohms at each end of that line. Both ends. Exactly two.',
      scene: { kind: 'formula', expr: '120Ω + 120Ω = 60Ω', note: 'What your meter reads across a healthy bus, powered off' } },
    { text: 'Those resistors are not there to limit current. They stop the edge reflecting off the end of the cable.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'clip', label: 'An unterminated edge, reflecting' } },
    { text: 'Miss one and it often still works on the bench and fails in the car. That is the worst possible failure.',
      scene: { kind: 'statement', lines: ['Works on the bench.', 'Fails in the car.'] } },
    { text: 'Measure it. Power off, meter across C A N high and C A N low. Sixty ohms is healthy.',
      scene: { kind: 'compare', left: '60Ω: two terminators', right: '120Ω: only one', caption: 'A ten second check' } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. Zero is dominant, so the lowest identifier wins and nothing is ever corrupted by a collision.',
      scene: { kind: 'recap', items: ['Dominant zero decides everything'] } },
    { text: 'Two. Identifiers name the message, not the recipient. Everyone listens and filters.',
      scene: { kind: 'recap', items: ['Dominant zero decides everything', 'The ID is the content'] } },
    { text: 'Three. One hundred and twenty ohms at both ends, and sixty on the meter.',
      scene: { kind: 'recap', items: ['Dominant zero decides everything', 'The ID is the content', 'Terminate both ends'] } },
    { text: 'Go and put a meter across a C A N bus you can reach, and see whether it reads sixty.',
      scene: { kind: 'outro' } },
  ],
};
