import type { LessonScript } from '../types';

/**
 * Unit 6, Capacitors, RC & Timing. Checkpoint for "Capacitors at Work".
 *
 * Three jobs that look unrelated on a schematic and are one behaviour
 * underneath. The film ends on the point the lessons make almost in passing:
 * the time constant and the cutoff frequency are the same fact, seen from two
 * directions.
 */
export const capsAtWork: LessonScript = {
  id: 'caps-at-work',
  title: 'Capacitors at Work',
  unitTitle: 'Capacitors, RC & Timing',
  unitId: 'capacitors-rc',
  skillId: 'caps-at-work',
  skillTitle: 'Capacitors at Work',
  accent: '#549cf0',
  segments: [
    { text: 'A capacitor does three completely different looking jobs, and underneath they are all the same job.',
      scene: { kind: 'title' } },
    { text: 'It resists a change in voltage. Watch that one idea turn into three circuits.',
      scene: { kind: 'statement', lines: ['One idea.', 'Three circuits.'] } },
    { text: 'First job. Smoothing a supply that is not steady.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'ripple', label: 'A supply that wobbles' } },
    { text: 'Put a large capacitor across the rail and it fills the dips from the charge it holds.',
      scene: { kind: 'circuit', variant: 'regulator', flow: true, highlight: 'cout', label: 'A reservoir on the rail' } },
    { text: 'The voltage cannot fall quickly, because falling means discharging, and discharging takes time.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'smooth', label: 'The same rail, smoothed' } },
    { text: 'That is a reservoir capacitor. Large, hundreds or thousands of microfarads, and an electrolytic.',
      scene: { kind: 'statement', lines: ['Large, slow,', 'electrolytic'] } },
    { text: 'Second job, which looks identical on the schematic and does something else entirely.',
      scene: { kind: 'circuit', variant: 'regulator', flow: true, highlight: 'cin', label: 'The same shape, another job' } },
    { text: 'A decoupling capacitor, sitting right beside a chip’s power pins.',
      scene: { kind: 'statement', lines: ['Right beside', 'the chip'] } },
    { text: 'A digital chip draws current in sharp bursts every time its outputs switch.',
      scene: { kind: 'statement', lines: ['Chips draw current', 'in bursts'] } },
    { text: 'The wire from your supply has inductance, so it cannot deliver a burst that fast.',
      scene: { kind: 'statement', lines: ['The wire is', 'too slow'] } },
    { text: 'So the local rail sags for a moment, and a sagging rail is how a microcontroller resets at random.',
      scene: { kind: 'statement', lines: ['A sag becomes', 'a reset'] } },
    { text: 'A one hundred nanofarad ceramic, millimetres from the pins, supplies that burst locally.',
      scene: { kind: 'formula', expr: '100nF, as close as possible' } },
    { text: 'Small and fast, where the reservoir is large and slow. That is why boards have both.',
      scene: { kind: 'compare', left: 'Electrolytic: slow dips', right: 'Ceramic: fast bursts', caption: 'Two timescales, two parts' } },
    { text: 'Third job. A capacitor in series with a signal instead of across it.',
      scene: { kind: 'statement', lines: ['In series,', 'not across'] } },
    { text: 'Steady voltage charges it once, and then no more current flows. So it blocks DC completely.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'dc', label: 'DC: charges once, then stops' } },
    { text: 'But a signal that keeps changing keeps charging and discharging it, so the changing part passes through.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'sine', label: 'AC: keeps moving' } },
    { text: 'That is a coupling capacitor. It passes the wiggle and strips off the level underneath.',
      scene: { kind: 'compare', left: 'Passes the wiggle', right: 'Blocks the level', caption: 'One part, two behaviours' } },
    { text: 'Which is exactly what you want between amplifier stages that sit at different DC voltages.',
      scene: { kind: 'statement', lines: ['Between stages', 'at different levels'] } },
    { text: 'Its opposition to a signal is called reactance, and it depends on frequency.',
      scene: { kind: 'formula', expr: 'Xc = 1 / (2π f C)' } },
    { text: 'High frequency means low reactance, so fast signals pass easily.',
      scene: { kind: 'statement', lines: ['Faster signal,', 'easier passage'] } },
    { text: 'At nought hertz, which is steady DC, the reactance is infinite. That is the blocking, in one equation.',
      scene: { kind: 'statement', lines: ['At 0Hz,', 'infinite'] } },
    { text: 'Now put a resistor in series and the capacitor to ground, and take the output across the capacitor.',
      scene: { kind: 'circuit', variant: 'rc', flow: true, highlight: 'resistor', label: 'A low pass filter' } },
    { text: 'Slow signals charge it and appear at the output. Fast ones are shunted to ground.',
      scene: { kind: 'circuit', variant: 'bode', highlight: 'lowpass', label: 'Low frequencies pass' } },
    { text: 'The frequency where it starts cutting is the cutoff, and it is one formula.',
      scene: { kind: 'formula', expr: 'fc = 1 / (2π R C)' } },
    { text: 'One point six kilohms and nought point one microfarads gives a cutoff of about one kilohertz.',
      scene: { kind: 'formula', expr: '1.6kΩ, 0.1µF → 1kHz' } },
    { text: 'And notice that is the same R and the same C that gave you the time constant. One behaviour, two views.',
      scene: { kind: 'compare', left: 'τ = R x C', right: 'fc = 1/(2πRC)', caption: 'The same circuit, twice' } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. Across a rail it smooths. A big electrolytic for slow dips, a small ceramic for fast bursts.',
      scene: { kind: 'recap', items: ['Across the rail, it smooths'] } },
    { text: 'Two. In series with a signal it blocks the DC level and passes the changing part.',
      scene: { kind: 'recap', items: ['Across the rail, it smooths', 'In series, it blocks DC and passes AC'] } },
    { text: 'Three. With a resistor it filters, and the cutoff is one over two pi R C.',
      scene: { kind: 'recap', items: ['Across the rail, it smooths', 'In series, it blocks DC and passes AC', 'With a resistor, it filters'] } },
    { text: 'Go and put a hundred nanofarads next to a chip that has been resetting on you.',
      scene: { kind: 'outro' } },
  ],
};
