import type { LessonScript } from '../types';

/**
 * Unit 11, Digital Logic & Embedded. Sits at the checkpoint for "Timing and
 * Clock Domains".
 *
 * The one film in this batch where motion is not a nice-to-have. Metastability
 * is defined by DURATION: an output sitting at an undefined level, between the
 * rails, for longer than it should, before it resolves to a value nobody can
 * predict. There is no still image of that. The authored lesson deliberately has
 * no drawing exercise for setup and hold for the same reason, and says so.
 */
export const clockDomains: LessonScript = {
  id: 'clock-domains',
  title: 'Timing and Clock Domains',
  unitTitle: 'Digital Logic & Embedded',
  unitId: 'digital-logic',
  skillId: 'clock-domains',
  skillTitle: 'Timing and Clock Domains',
  accent: '#549cf0',
  segments: [
    { text: 'A flip-flop has one job. On the clock edge, copy the input to the output.',
      scene: { kind: 'title' } },
    { text: 'It only does that job if you leave the input alone for long enough around the edge.',
      scene: { kind: 'circuit', variant: 'gate', highlight: 'ff 1 1', label: 'D in, Q out' } },
    { text: 'Setup time is how long the input must be stable BEFORE the edge arrives.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'square', label: 'Stable before the edge' } },
    { text: 'Hold time is how long it must stay stable AFTER. Both are in the datasheet, in nanoseconds.',
      scene: { kind: 'compare', left: 'Setup: quiet before', right: 'Hold: quiet after', caption: 'A window around the edge' } },
    { text: 'Miss either one and the flip-flop is not guaranteed to give you a one or a zero at all.',
      scene: { kind: 'statement', lines: ['Not guaranteed', 'to give you', 'either'] } },
    { text: 'Inside one clock domain, keeping that promise is arithmetic, and the tools do it for you.',
      scene: { kind: 'statement', lines: ['One clock.', 'One sum.'] } },
    { text: 'The path from one flip-flop to the next has to fit inside one clock period.',
      scene: { kind: 'circuit', variant: 'gate', highlight: 'ff 1 0', label: 'Flop, logic, flop' } },
    { text: 'Clock to Q, plus the logic in between, plus setup on the far end. That total is your critical path.',
      scene: { kind: 'formula', expr: 'tCQ + tLOGIC + tSETUP < tPERIOD', note: 'The whole of timing closure, in one line' } },
    { text: 'Whatever is left over is slack. Positive slack means it fits. Negative slack means it does not.',
      scene: { kind: 'compare', left: 'Positive slack: it fits', right: 'Negative slack: too slow', caption: 'The number the tools report' } },
    { text: 'Negative slack does not mean a slightly wrong answer. It means an answer you cannot rely on.',
      scene: { kind: 'statement', lines: ['Not slightly wrong.', 'Unreliable.'] } },
    { text: 'And the longest path in the whole design sets the clock. Not the average. The worst one.',
      scene: { kind: 'statement', lines: ['The slowest path', 'sets the speed'] } },
    { text: 'Now take two clocks that have nothing to do with each other.',
      scene: { kind: 'statement', lines: ['Two clocks.', 'No relationship.'] } },
    { text: 'A signal crossing between them arrives whenever it likes. Sooner or later it will land inside that window.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'square', label: 'Arriving whenever it likes' } },
    { text: 'Not might. Will. Given enough time, every asynchronous crossing violates setup or hold.',
      scene: { kind: 'statement', lines: ['Not might.', 'Will.'] } },
    { text: 'When that happens the output does something it is not supposed to be able to do.',
      scene: { kind: 'statement', lines: ['Metastability'] } },
    { text: 'It rises partway toward high, and stops. It sits at an undefined level, between the rails.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'sine', label: 'Stuck between the rails' } },
    { text: 'It is not a one. It is not a zero. It is a plateau at a voltage that means nothing.',
      scene: { kind: 'statement', lines: ['Not one.', 'Not zero.'] } },
    { text: 'Eventually it resolves, because physics will not let it stay there. But you do not get to choose which way.',
      scene: { kind: 'compare', left: 'Resolves to 1', right: 'Or resolves to 0', caption: 'And you cannot predict which' } },
    { text: 'Worse, downstream gates disagree about what they saw while it was undecided.',
      scene: { kind: 'circuit', variant: 'gate', highlight: 'and 1 0', label: 'Two gates, two answers' } },
    { text: 'Half your logic thinks it went high, half thinks it stayed low. That is one state machine in two states at once.',
      scene: { kind: 'statement', lines: ['One machine.', 'Two states.'] } },
    { text: 'You cannot prevent this. There is no circuit that makes it impossible.',
      scene: { kind: 'statement', lines: ['You cannot', 'prevent it'] } },
    { text: 'What you can do is give it time, and time buys an enormous amount.',
      scene: { kind: 'statement', lines: ['Give it time'] } },
    { text: 'Resolution is exponential. Every extra nanosecond multiplies the mean time between failures.',
      scene: { kind: 'compare', left: 'One more nanosecond', right: 'A thousand times the MTBF', caption: 'Resolution time buys reliability exponentially' } },
    { text: 'That is why the fix is so cheap. Two flip-flops in a row, both on the receiving clock.',
      scene: { kind: 'circuit', variant: 'gate', highlight: 'ff 1 1', label: 'Two flops, one clock' } },
    { text: 'The first one may well go metastable. It is given a whole clock period to settle before the second looks.',
      scene: { kind: 'compare', left: 'First flop: may wobble', right: 'Second: sees it settled', caption: 'The two-flop synchroniser' } },
    { text: 'That takes a failure every few seconds and turns it into one every few thousand years.',
      scene: { kind: 'formula', expr: 'MTBF ∝ e^(t/τ)', note: 'Why one extra flip-flop is enough' } },
    { text: 'Two rules about using it. Synchronise every crossing signal, and never fan out before the synchroniser.',
      scene: { kind: 'statement', lines: ['One synchroniser', 'per signal'] } },
    { text: 'Feeding a metastable output to two synchronisers gives you two answers to the same question.',
      scene: { kind: 'statement', lines: ['Two answers.', 'Same question.'] } },
    { text: 'And two flops only work for one bit. A bus crossing needs a handshake, or a F I F O with Grey coded pointers.',
      scene: { kind: 'compare', left: 'One bit: two flops', right: 'A bus: handshake or FIFO', caption: 'Because bits arrive at different times' } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. Setup and hold are a quiet window around the edge, and missing it has no defined result.',
      scene: { kind: 'recap', items: ['Quiet before and after the edge'] } },
    { text: 'Two. Every asynchronous crossing will go metastable eventually. It is when, not whether.',
      scene: { kind: 'recap', items: ['Quiet before and after the edge', 'Crossings will go metastable'] } },
    { text: 'Three. Two flip-flops on the receiving clock, on every single crossing signal.',
      scene: { kind: 'recap', items: ['Quiet before and after the edge', 'Crossings will go metastable', 'Two flops, every crossing'] } },
    { text: 'Go and find a signal in a design of yours that crosses clocks, and count the flip-flops on it.',
      scene: { kind: 'outro' } },
  ],
};
