import type { LessonScript } from '../types';

/**
 * Unit 5, Inputs, Outputs & Code. Checkpoint for "Code the Light Alarm".
 *
 * The unit's capstone, and the first sketch a learner writes that has a
 * decision in it. Most of the film is the calibration loop, because a
 * threshold copied from a tutorial is the single reason these builds do not
 * work on somebody else's desk.
 */
export const codeAlarm: LessonScript = {
  id: 'code-alarm',
  title: 'Code the Alarm',
  unitTitle: 'Inputs, Outputs & Code',
  unitId: 'inputs-outputs',
  skillId: 'code-alarm',
  skillTitle: 'Code the Light Alarm',
  accent: '#ff6f5e',
  segments: [
    { text: 'You wired the alarm in unit three. Now the deciding moves out of the wires and into a sketch.',
      scene: { kind: 'title' } },
    { text: 'The whole loop is three statements, one for each stage.',
      scene: { kind: 'statement', lines: ['Sense.', 'Decide.', 'Act.'] } },
    { text: 'Sense is one call, reading the divider midpoint.',
      scene: { kind: 'formula', expr: 'int reading = analogRead(A0);' } },
    { text: 'Decide is one comparison.',
      scene: { kind: 'formula', expr: 'if (reading < threshold)' } },
    { text: 'And act is one write, driving the output pin.',
      scene: { kind: 'formula', expr: 'digitalWrite(ALARM, HIGH);' } },
    { text: 'The condition in the brackets is the interesting part, so let us be precise about the operators.',
      scene: { kind: 'statement', lines: ['Be precise', 'about these'] } },
    { text: 'Less than, greater than, and double equals for is equal to.',
      scene: { kind: 'formula', expr: '<   >   ==' } },
    { text: 'A single equals sign assigns a value. A double equals compares two. That one letter is a real bug.',
      scene: { kind: 'compare', left: '= assigns', right: '== compares', caption: 'The classic one character bug' } },
    { text: 'And you need the else, or the alarm turns on and never turns off again.',
      scene: { kind: 'formula', expr: '} else { ... }' } },
    { text: 'Because digitalWrite holds its state. Nothing turns your output off unless you write low to it.',
      scene: { kind: 'statement', lines: ['Nothing turns it', 'off but you'] } },
    { text: 'Now the number in the middle of that comparison, which is where all the real work is.',
      scene: { kind: 'statement', lines: ['The threshold'] } },
    { text: 'Do not copy a threshold from anywhere. It depends on your LDR, your resistor, and your room.',
      scene: { kind: 'statement', lines: ['Never copy', 'a threshold'] } },
    { text: 'Print the reading instead, and go and look at it.',
      scene: { kind: 'formula', expr: 'Serial.println(reading);' } },
    { text: 'Watch the monitor with the lights on. Say it settles around seven hundred and eighty.',
      scene: { kind: 'circuit', variant: 'board', flow: true, highlight: 'usb', label: 'Bright: about 780' } },
    { text: 'Now put your hand over the sensor. Say it drops to about one hundred and ninety.',
      scene: { kind: 'compare', left: 'Bright 780', right: 'Dark 190', caption: 'Two numbers you measured' } },
    { text: 'Put the threshold between them. Around four hundred and eighty five, and it will be reliable.',
      scene: { kind: 'formula', expr: 'threshold = 485' } },
    { text: 'That is calibration, and it takes about ninety seconds.',
      scene: { kind: 'statement', lines: ['Ninety seconds', 'of measuring'] } },
    { text: 'Set it at seven seventy instead and every shadow, every passing cloud, sets the alarm off.',
      scene: { kind: 'statement', lines: ['No margin,', 'no peace'] } },
    { text: 'Set it at two hundred and it only fires in a genuinely dark room, which is not an alarm.',
      scene: { kind: 'statement', lines: ['Too far the', 'other way'] } },
    { text: 'One more improvement, and it costs you nothing.',
      scene: { kind: 'statement', lines: ['One improvement'] } },
    { text: 'A raw sensor reading jitters by a few counts even when nothing is changing.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'noise', label: 'A real reading, up close' } },
    { text: 'Right at the threshold that jitter crosses the line back and forth, and the output chatters.',
      scene: { kind: 'statement', lines: ['At the line,', 'it chatters'] } },
    { text: 'Use two numbers. Turn on below four hundred and fifty, turn off above five hundred and fifty.',
      scene: { kind: 'formula', expr: 'on < 450, off > 550' } },
    { text: 'Now it needs a real change in light to switch either way, and it feels solid instead of nervous.',
      scene: { kind: 'statement', lines: ['A real change,', 'or nothing'] } },
    { text: 'And swapping the LED for a buzzer changes one line, because act is already separate from decide.',
      scene: { kind: 'formula', expr: 'tone(BUZZER, 2000);' } },
    { text: 'That is what sense, decide, act buys you. Each stage can change without touching the others.',
      scene: { kind: 'statement', lines: ['Three stages,', 'three separate edits'] } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. analogRead, then if, then digitalWrite. Sense, decide, act, in three lines.',
      scene: { kind: 'recap', items: ['Read, compare, write'] } },
    { text: 'Two. Measure your own bright and dark readings and put the threshold between them.',
      scene: { kind: 'recap', items: ['Read, compare, write', 'Calibrate, never copy'] } },
    { text: 'Three. Always write the off case too, and use two thresholds to kill the chatter.',
      scene: { kind: 'recap', items: ['Read, compare, write', 'Calibrate, never copy', 'Write the off case, and add margin'] } },
    { text: 'Go and calibrate yours, then check it still works with the curtains half closed.',
      scene: { kind: 'outro' } },
  ],
};
