import type { LessonScript } from '../types';

/**
 * Unit 2, On the Breadboard. Checkpoint for "Debugging & Safety".
 *
 * The only skill in the unit where the failure is dangerous rather than merely
 * disappointing, so the film puts a real number on a short circuit, five amps
 * out of a five volt supply, before it teaches the search procedure.
 */
export const debuggingSafety: LessonScript = {
  id: 'debugging-safety',
  title: 'Faults and Safety',
  unitTitle: 'On the Breadboard',
  unitId: 'breadboard',
  skillId: 'debugging-safety',
  skillTitle: 'Debugging & Safety',
  accent: '#549cf0',
  segments: [
    { text: 'Almost every circuit that fails at your bench fails for one of about four reasons.',
      scene: { kind: 'title' } },
    { text: 'And one of those four can set fire to things, so we will start there.',
      scene: { kind: 'statement', lines: ['Start with the', 'dangerous one'] } },
    { text: 'A short circuit is a low resistance path that lets current bypass your components entirely.',
      scene: { kind: 'circuit', variant: 'led', flow: true, highlight: 'nores', label: 'Nothing in the way' } },
    { text: 'Put Ohm’s law to it. Five volts across a path with one ohm of wire resistance.',
      scene: { kind: 'formula', expr: '5V / 1Ω = 5A' } },
    { text: 'Five amps. Out of a supply that expected to give you twenty milliamps.',
      scene: { kind: 'compare', left: '20mA expected', right: '5A delivered', caption: 'Two hundred and fifty times over' } },
    { text: 'The wire heats, the battery heats, and a lithium cell asked for that can vent or catch fire.',
      scene: { kind: 'statement', lines: ['This is the', 'part that burns'] } },
    { text: 'So three habits. Always have something resistive in the path before you connect power.',
      scene: { kind: 'circuit', variant: 'led', flow: true, highlight: 'resistor', label: 'Something in the path' } },
    { text: 'Check your wiring with power off. Every rewire, every time, before it goes live.',
      scene: { kind: 'statement', lines: ['Rewire.', 'Then power.'] } },
    { text: 'And if anything gets hot or smells, pull the power first and investigate second.',
      scene: { kind: 'statement', lines: ['Hot or smelly?', 'Power off first.'] } },
    { text: 'Now the faults that are merely annoying, in the order you will meet them.',
      scene: { kind: 'statement', lines: ['The other three'] } },
    { text: 'A reversed LED. It blocks current, so it stays completely dark. Not dim. Dark.',
      scene: { kind: 'circuit', variant: 'led', flow: true, highlight: 'reversed', label: 'Reversed: dark, not dim' } },
    { text: 'A missing current limiting resistor, which destroys the LED in a fraction of a second.',
      scene: { kind: 'statement', lines: ['Missing resistor,', 'dead LED'] } },
    { text: 'Both legs of a part in the same connected row, which shorts that part straight out.',
      scene: { kind: 'circuit', variant: 'breadboard', flow: false, highlight: 'deadrow', label: 'Both legs, one row' } },
    { text: 'And a loose jumper, which breaks the loop and makes an entire build look dead.',
      scene: { kind: 'circuit', variant: 'loop', flow: false, broken: 'right', label: 'One loose wire' } },
    { text: 'When nothing happens, the temptation is to start swapping components. Do not.',
      scene: { kind: 'statement', lines: ['Do not start', 'swapping parts'] } },
    { text: 'A faulty component is genuinely rare. A broken loop or a reversed part is almost certain.',
      scene: { kind: 'compare', left: 'Broken loop', right: 'Faulty part', caption: 'Which is far more likely' } },
    { text: 'So work the loop in a fixed order, and do not skip a step because you feel sure.',
      scene: { kind: 'statement', lines: ['A fixed order,', 'every time'] } },
    { text: 'First, does power actually reach the rails? Put your meter across them and read it.',
      scene: { kind: 'circuit', variant: 'breadboard', flow: true, highlight: 'rails', label: 'One: is power there?' } },
    { text: 'Nought volts on a powered board means the supply is not getting in at all.',
      scene: { kind: 'statement', lines: ['0V means', 'nothing arrived'] } },
    { text: 'Second, is the loop complete? Set the meter to continuity and probe each connection.',
      scene: { kind: 'circuit', variant: 'trace', flow: true, label: 'Two: is the loop closed?' } },
    { text: 'A beep is a good wire. Silence on a wire you believed in is your fault found.',
      scene: { kind: 'compare', left: 'Beeps', right: 'Silence', caption: 'The second one is your answer' } },
    { text: 'Third, is anything in backwards? Check every polarised part, so LEDs, diodes and electrolytics.',
      scene: { kind: 'statement', lines: ['Three: check', 'the polarities'] } },
    { text: 'Fourth, and only fourth, are the values right? Read the bands rather than trusting the drawer.',
      scene: { kind: 'statement', lines: ['Four: read the', 'actual values'] } },
    { text: 'You can also walk the voltage along the loop. It should drop step by step as you go.',
      scene: { kind: 'statement', lines: ['Walk the voltage', 'round the loop'] } },
    { text: 'Wherever the voltage suddenly vanishes is exactly where your break is sitting.',
      scene: { kind: 'statement', lines: ['Where it vanishes,', 'there it is'] } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. A short is a path with no resistance, and the current it draws is enormous.',
      scene: { kind: 'recap', items: ['A short draws amps, not milliamps'] } },
    { text: 'Two. Nearly every dead build is a broken loop, a reversed part, or a shorted row.',
      scene: { kind: 'recap', items: ['A short draws amps, not milliamps', 'It is rarely a faulty component'] } },
    { text: 'Three. Debug in order: power, then loop, then polarity, then values.',
      scene: { kind: 'recap', items: ['A short draws amps, not milliamps', 'It is rarely a faulty component', 'Power, loop, polarity, values'] } },
    { text: 'Go and break a working circuit on purpose, then find it with only the meter.',
      scene: { kind: 'outro' } },
  ],
};
