import type { LessonScript } from '../types';

/**
 * Unit 12, Comms, Motors & Robotics. Checkpoint for "Driving Motors".
 *
 * Three separate failures live in this one skill, and a learner usually meets
 * all three at once: the pin cannot supply the current, the coil kicks back,
 * and the shared rail browns out the microcontroller mid-move.
 */
export const drivingMotors: LessonScript = {
  id: 'driving-motors',
  title: 'Driving Motors',
  unitTitle: 'Comms, Motors & Robotics',
  unitId: 'comms-motors-robotics',
  skillId: 'driving-motors',
  skillTitle: 'Driving Motors',
  accent: '#549cf0',
  segments: [
    { text: 'A motor is the most demanding thing you have connected to a microcontroller, in three separate ways.',
      scene: { kind: 'title' } },
    { text: 'Inside a brushed DC motor is a coil on a spinning rotor, surrounded by fixed magnets.',
      scene: { kind: 'circuit', variant: 'flyback', flow: true, highlight: 'coil', label: 'A coil, spinning' } },
    { text: 'Current through the coil makes a magnetic field, and the magnets pull it round.',
      scene: { kind: 'statement', lines: ['A field,', 'pulled round'] } },
    { text: 'Brushes flip the coil current every half turn, so the pull keeps going the same way.',
      scene: { kind: 'statement', lines: ['The brushes', 'keep flipping it'] } },
    { text: 'More voltage means more speed. Gear it down and you trade that speed for torque.',
      scene: { kind: 'compare', left: 'More volts: faster', right: 'More gearing: stronger', caption: 'You cannot have both for free' } },
    { text: 'Now the first problem. A small hobby motor wants two hundred milliamps, and far more at stall.',
      scene: { kind: 'circuit', variant: 'pin-direct', flow: true, highlight: 'load', label: 'A pin gives twenty' } },
    { text: 'A pin gives twenty. So a transistor switches the motor, exactly as you learned in unit seven.',
      scene: { kind: 'circuit', variant: 'transistor', flow: true, highlight: 'base', label: 'The pin instructs' } },
    { text: 'Second problem. A motor is a coil, and a coil kicks back when you switch it off.',
      scene: { kind: 'circuit', variant: 'flyback', flow: false, broken: 'right', highlight: 'spike', label: 'Back EMF, again' } },
    { text: 'So a flyback diode across the motor, banded end to the positive rail. Same rule as the relay.',
      scene: { kind: 'circuit', variant: 'flyback', flow: true, highlight: 'diode', label: 'The same diode as before' } },
    { text: 'And a motor is also a generator. Spin one by hand and a voltage appears at its terminals.',
      scene: { kind: 'statement', lines: ['It is also', 'a generator'] } },
    { text: 'So when a wheel is pushed, current flows back into your circuit, and the diode handles that too.',
      scene: { kind: 'statement', lines: ['Pushed, it', 'pushes back'] } },
    { text: 'Third problem, and it is the one that produces the maddening symptom.',
      scene: { kind: 'statement', lines: ['The maddening one'] } },
    { text: 'Your robot drives fine, then bumps a wall, and the whole board reboots.',
      scene: { kind: 'statement', lines: ['It bumps.', 'It reboots.'] } },
    { text: 'Because a stalled motor draws several times its running current, in a sharp surge.',
      scene: { kind: 'compare', left: 'Running: 200mA', right: 'Stalled: 1A', caption: 'The same motor, held still' } },
    { text: 'That surge drags the five volt rail down, the microcontroller browns out, and your code restarts.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'ripple', label: 'The rail, sagging' } },
    { text: 'So motors get their own supply, sized for the stall current, not for the running current.',
      scene: { kind: 'statement', lines: ['Their own supply.', 'Sized for stall.'] } },
    { text: 'But two supplies still need one shared reference, so you tie the two grounds together.',
      scene: { kind: 'statement', lines: ['One common', 'ground'] } },
    { text: 'Forget that and the driver sees no valid logic level at all, because there is no agreed nought volts.',
      scene: { kind: 'statement', lines: ['No shared zero,', 'no control'] } },
    { text: 'And put a bulk capacitor right at the driver, so the surge is supplied locally.',
      scene: { kind: 'statement', lines: ['A reservoir,', 'at the driver'] } },
    { text: 'One transistor only switches the motor on and off, in one direction. For a robot, that is not enough.',
      scene: { kind: 'statement', lines: ['One direction', 'is not enough'] } },
    { text: 'To reverse a wheel you need four switches, arranged with the motor in the crossbar of an H.',
      scene: { kind: 'statement', lines: ['Four switches,', 'in an H'] } },
    { text: 'Close the top left and bottom right and current runs one way. Close the other diagonal and it reverses.',
      scene: { kind: 'compare', left: 'One diagonal: forward', right: 'The other: back', caption: 'The same motor, either way' } },
    { text: 'That is an H bridge, and it has four useful states. Coast, forward, backward, and brake.',
      scene: { kind: 'statement', lines: ['Coast, forward,', 'back, brake'] } },
    { text: 'Brake means shorting the motor terminals together, which dumps its momentum as current and stops it fast.',
      scene: { kind: 'statement', lines: ['Brake is', 'a deliberate short'] } },
    { text: 'And there is one forbidden move, which is closing both switches on the same side at once.',
      scene: { kind: 'statement', lines: ['One forbidden', 'move'] } },
    { text: 'That connects the supply straight to ground. It is called shoot through, and it destroys the bridge.',
      scene: { kind: 'compare', left: 'Four transistors: possible', right: 'An L293D: impossible', caption: 'Why an integrated driver is safer' } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. A motor needs a transistor for the current and a flyback diode for the spike.',
      scene: { kind: 'recap', items: ['A transistor, and a diode'] } },
    { text: 'Two. Give motors their own supply and tie the grounds together, or the board will reboot.',
      scene: { kind: 'recap', items: ['A transistor, and a diode', 'Separate supply, common ground'] } },
    { text: 'Three. An H bridge reverses a motor, and both switches on one side is a dead short.',
      scene: { kind: 'recap', items: ['A transistor, and a diode', 'Separate supply, common ground', 'An H bridge reverses it'] } },
    { text: 'Go and measure your motor’s stall current by holding the shaft. Carefully.',
      scene: { kind: 'outro' } },
  ],
};
