import type { LessonScript } from '../types';

/**
 * Unit 7, Transistors & Switching. Checkpoint for "Driving Loads".
 *
 * Chosen because it is the skill whose failure mode costs real hardware. A
 * learner who wires a motor straight to a pin does not get a wrong answer, they
 * get a dead board, and no quiz step can show them the moment it happens.
 */
export const drivingLoads: LessonScript = {
  id: 'driving-loads',
  title: 'Driving Loads',
  unitTitle: 'Transistors & Switching',
  unitId: 'transistors',
  skillId: 'driving-loads',
  skillTitle: 'Driving Loads',
  accent: '#84cc30',
  segments: [
    { text: 'Your microcontroller can decide anything. What it cannot do is push very much current.',
      scene: { kind: 'title' } },
    { text: 'An Arduino output pin will give you about twenty milliamps safely. Forty is the absolute limit.',
      scene: { kind: 'formula', expr: '20mA safe, 40mA absolute' } },
    { text: 'That is plenty for an LED. An LED is happy at ten to twenty milliamps.',
      scene: { kind: 'circuit', variant: 'pin-direct', flow: true, label: 'An LED is fine' } },
    { text: 'Now try a small hobby motor. It wants two hundred milliamps, and much more the instant it starts.',
      scene: { kind: 'circuit', variant: 'pin-direct', flow: true, highlight: 'load', label: 'A motor wants 200mA' } },
    { text: 'Ask a twenty milliamp pin for two hundred and you do not get a slow motor. You get a damaged pin.',
      scene: { kind: 'statement', lines: ['Not a slow motor.', 'A damaged pin.'] } },
    { text: 'Sometimes it fails immediately. More often it half works for a week and then stops forever.',
      scene: { kind: 'statement', lines: ['Half works.', 'Then never again.'] } },
    { text: 'So we stop asking the pin to do the work, and ask it to give an instruction instead.',
      scene: { kind: 'statement', lines: ['Instruct.', 'Do not power.'] } },
    { text: 'That is what a transistor is for. A small current controls a much larger one.',
      scene: { kind: 'circuit', variant: 'transistor', flow: false, label: 'Small controls large' } },
    { text: 'Here is the arrangement. The pin goes to the base. The load and the supply go to the collector.',
      scene: { kind: 'circuit', variant: 'transistor', flow: false, highlight: 'base', label: 'Pin to base' } },
    { text: 'The emitter goes to ground, and that ground must be shared with the microcontroller.',
      scene: { kind: 'circuit', variant: 'transistor', flow: false, highlight: 'emitter', label: 'Shared ground' } },
    { text: 'Set the pin high and a milliamp or two flows into the base.',
      scene: { kind: 'circuit', variant: 'transistor', flow: true, highlight: 'base', label: '1 to 2mA into the base' } },
    { text: 'The transistor responds by letting hundreds of milliamps through the load. The motor runs.',
      scene: { kind: 'circuit', variant: 'transistor', flow: true, highlight: 'load', label: 'Hundreds of mA through the load' } },
    { text: 'The pin never carried that current. It only ever supplied the instruction.',
      scene: { kind: 'compare', left: '2mA decides', right: '200mA flows', caption: 'The pin never carried the load' } },
    { text: 'The ratio between them is the gain, often written as h F E, and for a small transistor it is around a hundred.',
      scene: { kind: 'formula', expr: 'hFE = collector / base', note: 'Around 100 for a small transistor' } },
    { text: 'Now the part beginners leave out, and it is not optional.',
      scene: { kind: 'statement', lines: ['The part people', 'leave out'] } },
    { text: 'You must put a resistor between the pin and the base.',
      scene: { kind: 'circuit', variant: 'transistor', flow: false, highlight: 'baseresistor', label: 'Base resistor, always' } },
    { text: 'Without it the base looks almost like a short circuit to your pin, and you are back to a damaged pin.',
      scene: { kind: 'statement', lines: ['No resistor,', 'no pin'] } },
    { text: 'Size it with Ohm’s law. Five volts from the pin, minus about nought point seven across the base junction.',
      scene: { kind: 'formula', expr: '5V - 0.7V = 4.3V' } },
    { text: 'Divide that by the base current you want. Two milliamps gives about two thousand ohms.',
      scene: { kind: 'formula', expr: '4.3V / 2mA = 2.2kΩ' } },
    { text: 'A one or two point two kilohm resistor is the usual answer, and it is why you see them everywhere.',
      scene: { kind: 'statement', lines: ['1k to 2.2k', 'is the usual answer'] } },
    { text: 'One more thing, and it decides whether your transistor survives.',
      scene: { kind: 'statement', lines: ['One more thing'] } },
    { text: 'Drive the base hard enough and the transistor turns fully on, which is called saturation.',
      scene: { kind: 'compare', left: 'Partly on', right: 'Saturated', caption: 'Only one of these stays cool' } },
    { text: 'A partly on transistor drops voltage across itself and turns that into heat.',
      scene: { kind: 'statement', lines: ['Partly on', 'means hot'] } },
    { text: 'A saturated one drops almost nothing and stays cool. As a switch, you always want saturation.',
      scene: { kind: 'statement', lines: ['As a switch,', 'always saturate'] } },
    { text: 'So give the base more current than the calculation strictly demands. Five to ten times more is normal.',
      scene: { kind: 'statement', lines: ['Overdrive the base', 'on purpose'] } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. A pin instructs, it does not power. Anything above twenty milliamps needs a transistor.',
      scene: { kind: 'recap', items: ['A pin instructs, it does not power'] } },
    { text: 'Two. Always put a resistor between the pin and the base, around one to two point two kilohms.',
      scene: { kind: 'recap', items: ['A pin instructs, it does not power', 'Always use a base resistor'] } },
    { text: 'Three. Drive it into saturation, because a half open switch is a heater.',
      scene: { kind: 'recap', items: ['A pin instructs, it does not power', 'Always use a base resistor', 'Saturate, or it runs hot'] } },
    { text: 'Next you will meet the motor fighting back, and the diode that stops it.',
      scene: { kind: 'outro' } },
  ],
};
