import type { LessonScript } from '../types';

/**
 * Unit 11, Digital Logic & Embedded. Checkpoint for "The Embedded Bridge".
 *
 * The film that connects the discrete logic the unit has just taught to the
 * chip the learner has been using since unit four. Interrupts and bus choice
 * get the time, because both are decisions rather than facts.
 */
export const embeddedBridge: LessonScript = {
  id: 'embedded-bridge',
  title: 'The Embedded Bridge',
  unitTitle: 'Digital Logic & Embedded',
  unitId: 'digital-logic',
  skillId: 'embedded-bridge',
  skillTitle: 'The Embedded Bridge',
  accent: '#549cf0',
  segments: [
    { text: 'You have been using a microcontroller for six units. Now you know what is inside it.',
      scene: { kind: 'title' } },
    { text: 'Gates, flip-flops, counters and registers, several million of them on one piece of silicon.',
      scene: { kind: 'circuit', variant: 'board', flow: false, highlight: 'mcu', label: 'All of it, in there' } },
    { text: 'But you can still buy the discrete parts, and the classic family is the 74 series.',
      scene: { kind: 'circuit', variant: 'gate', flow: true, highlight: 'nand 1 1', label: 'Four gates in one package' } },
    { text: 'A 74HC00 holds four two input NAND gates. A 74HC08 holds four ANDs.',
      scene: { kind: 'formula', expr: '74HC00 = four NANDs' } },
    { text: 'H C means high speed C MOS, and it is the everyday default now.',
      scene: { kind: 'statement', lines: ['74HC is', 'the default'] } },
    { text: 'Two of the pins are power. V C C at the top corner, ground diagonally opposite.',
      scene: { kind: 'statement', lines: ['Vcc, and', 'ground'] } },
    { text: 'And one thing is not optional on any logic chip, ever.',
      scene: { kind: 'statement', lines: ['One thing is', 'not optional'] } },
    { text: 'A hundred nanofarad ceramic, right at the chip’s power pins. You have met this three times now.',
      scene: { kind: 'statement', lines: ['100nF, at the', 'power pins'] } },
    { text: 'Every output that switches snatches a gulp of current, and the capacitor supplies it locally.',
      scene: { kind: 'statement', lines: ['A local gulp,', 'supplied locally'] } },
    { text: 'Skip it and the chip behaves erratically in ways that look like a logic error and are not.',
      scene: { kind: 'compare', left: 'With: reliable', right: 'Without: erratic', caption: 'And the logic is identical' } },
    { text: 'Now back to the microcontroller, and the pins your code actually drives.',
      scene: { kind: 'circuit', variant: 'board', flow: false, highlight: 'digital', label: 'The GPIO pins' } },
    { text: 'They are called G P I O, for general purpose input output, and each can be either.',
      scene: { kind: 'statement', lines: ['General purpose,', 'either direction'] } },
    { text: 'Most of them are multiplexed, meaning one physical pin can be several different things.',
      scene: { kind: 'statement', lines: ['One pin,', 'several jobs'] } },
    { text: 'A nought is a digital pin, or an analog input, depending only on how you configure it.',
      scene: { kind: 'circuit', variant: 'board', flow: false, highlight: 'analog', label: 'The same pin, two roles' } },
    { text: 'And the P W M you used in unit five is a hardware timer inside the chip, not a loop in your code.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'pwm50', label: 'A timer, not your loop' } },
    { text: 'Which is why it keeps switching perfectly while your program is busy doing something else.',
      scene: { kind: 'statement', lines: ['It runs while', 'you are busy'] } },
    { text: 'Now the idea that changes how you write embedded code.',
      scene: { kind: 'statement', lines: ['One idea,', 'and it changes things'] } },
    { text: 'So far you have polled. Your loop goes round, checking an input over and over.',
      scene: { kind: 'statement', lines: ['Polling: check,', 'and check again'] } },
    { text: 'Simple, and it works, right up until your loop is busy when the thing you care about happens.',
      scene: { kind: 'compare', left: 'Polling: might miss it', right: 'Interrupt: cannot miss it', caption: 'A brief event, two outcomes' } },
    { text: 'An interrupt pauses your program the instant an event fires, runs a short handler, and returns.',
      scene: { kind: 'statement', lines: ['Pause. Handle.', 'Return.'] } },
    { text: 'Use one for anything fast or brief you must not miss, like a pulse from a motor encoder.',
      scene: { kind: 'statement', lines: ['For fast things', 'you must not miss'] } },
    { text: 'But keep the handler tiny, because your main program is frozen while it runs.',
      scene: { kind: 'statement', lines: ['Keep the handler', 'tiny'] } },
    { text: 'And do not attach one to a bouncing button, or one press fires it five times.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'bounce', label: 'Five interrupts, one press' } },
    { text: 'Last, how chips talk to each other, which is always one bit at a time down a few wires.',
      scene: { kind: 'statement', lines: ['Three buses'] } },
    { text: 'U A R T has no clock wire, so both ends must agree a baud rate in advance. Two devices, two wires.',
      scene: { kind: 'formula', expr: 'UART: 2 wires, no clock' } },
    { text: 'I squared C shares two wires among many devices, each picked out by its own address.',
      scene: { kind: 'compare', left: 'I2C: 2 wires, many devices', right: 'SPI: fast, one select each', caption: 'Wires, or speed' } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. A hundred nanofarads at every logic chip’s power pins, every time.',
      scene: { kind: 'recap', items: ['Decouple every chip'] } },
    { text: 'Two. Poll a slow input. Interrupt on a fast one, and keep the handler short.',
      scene: { kind: 'recap', items: ['Decouple every chip', 'Poll slow things, interrupt fast ones'] } },
    { text: 'Three. U A R T for two devices, I squared C for many slow ones, S P I when you need speed.',
      scene: { kind: 'recap', items: ['Decouple every chip', 'Poll slow things, interrupt fast ones', 'UART, I2C, or SPI, by the job'] } },
    { text: 'Go and attach an interrupt to something, then measure how long your handler takes.',
      scene: { kind: 'outro' } },
  ],
};
