import type { LessonScript } from '../types';

/**
 * Unit 9, Filters, Oscillators & Signals. Checkpoint for "Filters".
 *
 * One RC pair, four filters, depending only on where you take the output and
 * how you stack them. The decibel section is kept short and concrete: what
 * matters at the bench is that minus three is the corner and that one pole
 * rolls off slowly.
 */
export const filters: LessonScript = {
  id: 'filters',
  title: 'Filters',
  unitTitle: 'Filters, Oscillators & Signals',
  unitId: 'filters-oscillators',
  skillId: 'filters',
  skillTitle: 'Filters',
  accent: '#549cf0',
  segments: [
    { text: 'A filter keeps the frequencies you want and throws away the ones you do not.',
      scene: { kind: 'title' } },
    { text: 'And the simplest one is a resistor and a capacitor, which you have already built.',
      scene: { kind: 'circuit', variant: 'rc', flow: true, label: 'A resistor, and a capacitor' } },
    { text: 'Resistor in series, capacitor to ground, output taken across the capacitor.',
      scene: { kind: 'circuit', variant: 'rc', flow: true, highlight: 'resistor', label: 'Output across the capacitor' } },
    { text: 'That is a low pass filter. Slow signals get through, fast ones are shunted to ground.',
      scene: { kind: 'circuit', variant: 'bode', highlight: 'lowpass', label: 'Low pass' } },
    { text: 'It works because a capacitor’s opposition to a signal falls as the frequency rises.',
      scene: { kind: 'formula', expr: 'Xc = 1 / (2π f C)' } },
    { text: 'High frequency, low reactance, so the capacitor looks almost like a wire to ground.',
      scene: { kind: 'statement', lines: ['To fast signals,', 'almost a short'] } },
    { text: 'Now swap the two parts over. Capacitor in series, resistor to ground.',
      scene: { kind: 'statement', lines: ['Swap them', 'over'] } },
    { text: 'Take the output across the resistor and you have the exact opposite filter.',
      scene: { kind: 'circuit', variant: 'bode', highlight: 'highpass', label: 'High pass' } },
    { text: 'A high pass. Fast signals through, slow ones blocked, and DC blocked completely.',
      scene: { kind: 'statement', lines: ['Highs through.', 'DC blocked.'] } },
    { text: 'Which means the coupling capacitor you met in unit six was a high pass filter all along.',
      scene: { kind: 'statement', lines: ['Coupling is', 'high pass'] } },
    { text: 'Same two components. Same values. The only difference is where you take the output.',
      scene: { kind: 'compare', left: 'Across C: low pass', right: 'Across R: high pass', caption: 'The identical parts, both ways' } },
    { text: 'And the frequency where either one turns over is the same formula.',
      scene: { kind: 'formula', expr: 'fc = 1 / (2π R C)' } },
    { text: 'One point six kilohms and nought point one microfarads gives about one kilohertz.',
      scene: { kind: 'formula', expr: '1.6kΩ, 0.1µF → 1kHz' } },
    { text: 'Make the resistor ten times bigger and the cutoff drops to a hundred hertz.',
      scene: { kind: 'formula', expr: '16kΩ, 0.1µF → 100Hz' } },
    { text: 'Now be careful about what happens at the cutoff, because it is not a wall.',
      scene: { kind: 'statement', lines: ['It is not', 'a wall'] } },
    { text: 'At the cutoff frequency the output is still seventy point seven percent of the input.',
      scene: { kind: 'circuit', variant: 'bode', highlight: 'lowpass', label: '70.7% at the corner' } },
    { text: 'That figure is not arbitrary. Power goes as voltage squared, and nought point seven zero seven squared is a half.',
      scene: { kind: 'formula', expr: '0.707² = 0.5' } },
    { text: 'So the cutoff is where the filter passes half the power, which is why it is also called the half power point.',
      scene: { kind: 'statement', lines: ['Half the power.', 'Not half the volts.'] } },
    { text: 'In decibels that is minus three, and decibels are how filters are always described.',
      scene: { kind: 'formula', expr: 'dB = 20 x log10(Vout/Vin)' } },
    { text: 'A gain of one is nought decibels. A gain of ten is twenty. Nought point seven zero seven is minus three.',
      scene: { kind: 'statement', lines: ['x1 is 0dB.', 'x10 is 20dB.'] } },
    { text: 'And past the cutoff, a single R C filter falls away rather gently.',
      scene: { kind: 'statement', lines: ['It falls away', 'gently'] } },
    { text: 'Twenty decibels per decade, meaning ten times the frequency gets you ten times less signal.',
      scene: { kind: 'formula', expr: '−20dB per decade' } },
    { text: 'Which is often not enough. To cut harder you cascade more stages, and each one steepens the slope.',
      scene: { kind: 'compare', left: 'One stage: −20dB', right: 'Two stages: −40dB', caption: 'Per decade of frequency' } },
    { text: 'Put a high pass and a low pass together and you keep only what is between them.',
      scene: { kind: 'circuit', variant: 'bode', highlight: 'bandpass', label: 'Band pass' } },
    { text: 'That is a band pass, and the distance between its two corners is its bandwidth.',
      scene: { kind: 'formula', expr: 'BW = f2 - f1' } },
    { text: 'A radio tuner is a very narrow band pass. Narrow enough to pick one station out of hundreds.',
      scene: { kind: 'statement', lines: ['A tuner is', 'a band pass'] } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. The same R and C give a low pass across the capacitor, or a high pass across the resistor.',
      scene: { kind: 'recap', items: ['Same parts, output decides'] } },
    { text: 'Two. The cutoff is one over two pi R C, and there the output is seventy percent, not nothing.',
      scene: { kind: 'recap', items: ['Same parts, output decides', 'fc = 1 / 2πRC, at −3dB'] } },
    { text: 'Three. One stage rolls off at twenty decibels a decade, and stages stack to get steeper.',
      scene: { kind: 'recap', items: ['Same parts, output decides', 'fc = 1 / 2πRC, at −3dB', 'Cascade stages for a sharper cut'] } },
    { text: 'Go and design a low pass that keeps a sensor signal and drops mains hum.',
      scene: { kind: 'outro' } },
  ],
};
