import type { LessonScript } from '../types';

/**
 * Unit 4, Meet the Arduino. Checkpoint for "Your First Sketch".
 *
 * Four lines of code and one failure mode that looks like a hardware fault: a
 * pin left as an input still lights an LED faintly, so the learner concludes
 * the LED is dying rather than that pinMode is missing.
 */
export const firstSketch: LessonScript = {
  id: 'first-sketch',
  title: 'Your First Sketch',
  unitTitle: 'Meet the Arduino',
  unitId: 'arduino',
  skillId: 'first-sketch',
  skillTitle: 'Your First Sketch',
  accent: '#f2b705',
  segments: [
    { text: 'Blink is four instructions long, and every one of them earns its place.',
      scene: { kind: 'title' } },
    { text: 'Start above the code, with a name.',
      scene: { kind: 'formula', expr: 'const int LED = 13;' } },
    { text: 'That gives the number thirteen a name, so the rest of your code never mentions thirteen again.',
      scene: { kind: 'statement', lines: ['Name it once,', 'use the name'] } },
    { text: 'Move the wire to pin eight and you change one line, not seven scattered ones.',
      scene: { kind: 'compare', left: 'One edit', right: 'Seven edits', caption: 'The reason to name a pin' } },
    { text: 'Const means the value will not change while the program runs, and the compiler will hold you to it.',
      scene: { kind: 'statement', lines: ['const means', 'it will not move'] } },
    { text: 'Next, inside setup, tell the pin which direction it works in.',
      scene: { kind: 'formula', expr: 'pinMode(LED, OUTPUT);' } },
    { text: 'Output means the pin drives something. Input means the pin reads something.',
      scene: { kind: 'compare', left: 'OUTPUT drives', right: 'INPUT reads', caption: 'A pin does one or the other' } },
    { text: 'This matters more than it looks, because pins do not default to output.',
      scene: { kind: 'statement', lines: ['They default', 'to input'] } },
    { text: 'They default to input, and here is what that actually does to your circuit.',
      scene: { kind: 'circuit', variant: 'board', flow: false, highlight: 'pin13', label: 'A pin left as an input' } },
    { text: 'Forget the pinMode line and your LED still lights, but very faintly.',
      scene: { kind: 'circuit', variant: 'led', flow: true, label: 'Faint, not dark' } },
    { text: 'Not dark, which would be an obvious clue. Faint, which sends people hunting for a dying LED.',
      scene: { kind: 'compare', left: 'Dark: a clue', right: 'Faint: a wild goose chase', caption: 'Why this one costs an hour' } },
    { text: 'So pinMode goes in setup, once, before anything tries to drive that pin.',
      scene: { kind: 'statement', lines: ['pinMode first.', 'Always.'] } },
    { text: 'Now the line that actually does something.',
      scene: { kind: 'formula', expr: 'digitalWrite(LED, HIGH);' } },
    { text: 'High puts five volts on the pin. Current flows through your resistor and the LED lights.',
      scene: { kind: 'circuit', variant: 'led', flow: true, highlight: 'led', label: 'HIGH: five volts out' } },
    { text: 'And low puts nought volts on it, so the LED goes out.',
      scene: { kind: 'formula', expr: 'digitalWrite(LED, LOW);' } },
    { text: 'The pin holds whatever you last told it. It does not need reminding thousands of times a second.',
      scene: { kind: 'statement', lines: ['It holds', 'its state'] } },
    { text: 'Which is why the fourth instruction is the one that makes it visible.',
      scene: { kind: 'formula', expr: 'delay(1000);' } },
    { text: 'Delay pauses for a number of milliseconds. A thousand milliseconds is one second.',
      scene: { kind: 'statement', lines: ['1000ms', 'is one second'] } },
    { text: 'On, wait a second, off, wait a second. That is a two second cycle, and that is Blink.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'pwm50', label: 'On, off, on, off' } },
    { text: 'Take both delays out and the code still runs perfectly.',
      scene: { kind: 'statement', lines: ['It still runs.', 'You still see nothing.'] } },
    { text: 'It just toggles the pin tens of thousands of times a second, so the LED looks dimly, steadily on.',
      scene: { kind: 'compare', left: 'With delays: blink', right: 'Without: a dim glow', caption: 'Too fast to be a blink' } },
    { text: 'Change both delays to fifty and you get about ten blinks a second, which reads as a flicker.',
      scene: { kind: 'formula', expr: 'delay(50) → ~10Hz' } },
    { text: 'Somewhere around twenty times a second your eye stops seeing separate flashes.',
      scene: { kind: 'statement', lines: ['Above about 20Hz,', 'it blends'] } },
    { text: 'That fact is not a curiosity. It is the whole reason the next lesson on P W M works.',
      scene: { kind: 'statement', lines: ['Remember that.', 'PWM needs it.'] } },
    { text: 'One habit to build now. Delay stops everything, including reading a button.',
      scene: { kind: 'statement', lines: ['delay stops', 'everything'] } },
    { text: 'It is fine for Blink and it is a trap the moment your sketch has two jobs.',
      scene: { kind: 'statement', lines: ['Fine now.', 'A trap later.'] } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. Name your pins with const, so moving a wire is a one line change.',
      scene: { kind: 'recap', items: ['Name pins with const'] } },
    { text: 'Two. Set pinMode in setup, because a forgotten one gives you a faint LED and a long evening.',
      scene: { kind: 'recap', items: ['Name pins with const', 'pinMode in setup, every time'] } },
    { text: 'Three. digitalWrite holds its state, and delay is what makes the change visible.',
      scene: { kind: 'recap', items: ['Name pins with const', 'pinMode in setup, every time', 'The pin holds, delay reveals'] } },
    { text: 'Go and blink it at two hertz, then at fifty, and watch where your eye gives up.',
      scene: { kind: 'outro' } },
  ],
};
