import type { LessonScript } from '../types';

/**
 * Unit 7, Transistors & Switching. Checkpoint for "Inductive Loads & Protection".
 *
 * The failure here is delayed, which is what makes it worth a film: the
 * transistor survives the first hundred switch-offs and dies on the two
 * hundredth, so nothing at the bench connects the cause to the effect.
 */
export const inductiveProtection: LessonScript = {
  id: 'inductive-protection',
  title: 'Taming the Spike',
  unitTitle: 'Transistors & Switching',
  unitId: 'transistors',
  skillId: 'inductive-protection',
  skillTitle: 'Inductive Loads & Protection',
  accent: '#84cc30',
  segments: [
    { text: 'Your transistor drives the motor perfectly. Then, a week later, it is dead.',
      scene: { kind: 'title' } },
    { text: 'Nothing you did was wrong at the moment it broke. The damage was done at every switch off.',
      scene: { kind: 'statement', lines: ['Every switch off', 'did a little'] } },
    { text: 'A motor, a relay, a solenoid, all of them are coils of wire.',
      scene: { kind: 'circuit', variant: 'flyback', flow: true, broken: 'right', highlight: 'coil', label: 'A coil, not a resistor' } },
    { text: 'And a coil with current flowing in it stores energy in a magnetic field.',
      scene: { kind: 'statement', lines: ['A coil stores', 'energy'] } },
    { text: 'A capacitor opposes a change in voltage. An inductor is its mirror image, and opposes a change in current.',
      scene: { kind: 'compare', left: 'Capacitor: voltage', right: 'Inductor: current', caption: 'Each resists a change in one thing' } },
    { text: 'Which is fine while it is running. The trouble is the instant you switch it off.',
      scene: { kind: 'statement', lines: ['The trouble is', 'switching off'] } },
    { text: 'The field collapses and the coil tries desperately to keep the current flowing.',
      scene: { kind: 'statement', lines: ['It will not', 'let go'] } },
    { text: 'But you have just opened the path, so there is nowhere for that current to go.',
      scene: { kind: 'statement', lines: ['Nowhere', 'to go'] } },
    { text: 'So it generates whatever voltage it takes to try, and that voltage is enormous.',
      scene: { kind: 'circuit', variant: 'flyback', flow: false, broken: 'right', highlight: 'spike', label: 'Hundreds of volts, from twelve' } },
    { text: 'A twelve volt relay coil can produce a spike of two or three hundred volts on switch off.',
      scene: { kind: 'compare', left: 'Supply: 12V', right: 'Spike: 300V', caption: 'From the same coil, a millisecond later' } },
    { text: 'That is called back E M F, and it appears directly across your transistor.',
      scene: { kind: 'statement', lines: ['Back EMF,', 'across your switch'] } },
    { text: 'A small transistor is rated for perhaps forty volts. Three hundred punches straight through it.',
      scene: { kind: 'statement', lines: ['Rated 40V.', 'Given 300.'] } },
    { text: 'Sometimes it fails at once. More often it degrades a little at a time and dies next week.',
      scene: { kind: 'statement', lines: ['A little damage,', 'many times'] } },
    { text: 'The fix costs about two pence, and it is one diode.',
      scene: { kind: 'circuit', variant: 'flyback', flow: true, highlight: 'diode', label: 'One diode across the coil' } },
    { text: 'It goes directly across the coil, not across the transistor.',
      scene: { kind: 'statement', lines: ['Across the coil.', 'Not the transistor.'] } },
    { text: 'While the circuit is running normally, it is reverse biased and does absolutely nothing.',
      scene: { kind: 'circuit', variant: 'flyback', flow: true, highlight: 'diode', label: 'Normally: doing nothing' } },
    { text: 'Then at switch off the coil reverses its voltage, which forward biases the diode.',
      scene: { kind: 'statement', lines: ['The coil reverses.', 'The diode opens.'] } },
    { text: 'Now the collapsing current has a loop to circulate in, and it dies away gently instead of spiking.',
      scene: { kind: 'circuit', variant: 'flyback', flow: false, highlight: 'recirculate diode', label: 'A private loop to die in' } },
    { text: 'This is called a flyback diode, or a freewheeling diode. Both names describe the same part.',
      scene: { kind: 'statement', lines: ['Flyback, or', 'freewheeling'] } },
    { text: 'Now the part you must not get wrong, because backwards it is worse than absent.',
      scene: { kind: 'statement', lines: ['Do not fit it', 'backwards'] } },
    { text: 'The banded end, the cathode, goes to the positive supply. The other end goes to the collector.',
      scene: { kind: 'circuit', variant: 'flyback', flow: false, highlight: 'diode', label: 'Band to the positive rail' } },
    { text: 'That way it blocks the normal supply current and only ever conducts the reverse spike.',
      scene: { kind: 'compare', left: 'Band to plus', right: 'Band to collector', caption: 'The second one shorts your supply' } },
    { text: 'Fit it the other way and it conducts the moment you power on. A dead short, straight across the rail.',
      scene: { kind: 'statement', lines: ['Backwards is', 'a dead short'] } },
    { text: 'A one N four zero zero one is fine for most small coils, and it costs almost nothing.',
      scene: { kind: 'formula', expr: '1N4001: 1A, 50V' } },
    { text: 'One exception. On an AC load a diode would conduct half of every cycle, so you use an R C snubber instead.',
      scene: { kind: 'statement', lines: ['On AC, use', 'an RC snubber'] } },
    { text: 'And the rule does not care what kind of switch you used. A MOSFET needs the diode just as much.',
      scene: { kind: 'statement', lines: ['The load decides,', 'not the switch'] } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. Any coil kicks back a spike far above the supply when you switch it off.',
      scene: { kind: 'recap', items: ['Coils spike when switched off'] } },
    { text: 'Two. A flyback diode across the coil gives that current a loop, and it is never optional.',
      scene: { kind: 'recap', items: ['Coils spike when switched off', 'A flyback diode, across the coil'] } },
    { text: 'Three. The banded end goes to the positive rail, and backwards it is a short circuit.',
      scene: { kind: 'recap', items: ['Coils spike when switched off', 'A flyback diode, across the coil', 'Band to plus, always'] } },
    { text: 'Go and check every motor and relay you have already built for its diode.',
      scene: { kind: 'outro' } },
  ],
};
