import type { LessonScript } from '../types';

/**
 * Unit 1, Foundations. Checkpoint for "LEDs & Current Limiting".
 *
 * The one calculation in the whole unit that a learner gets wrong in the same
 * way every time: forgetting to subtract the forward voltage. The film puts the
 * right answer and the wrong answer on screen next to each other rather than
 * only teaching the right one.
 */
export const ledsLimiting: LessonScript = {
  id: 'leds-limiting',
  title: 'Lighting an LED',
  unitTitle: 'Foundations',
  unitId: 'foundations',
  skillId: 'leds-limiting',
  skillTitle: 'LEDs & Current Limiting',
  accent: '#f2b705',
  segments: [
    { text: 'An LED is the easiest thing in your kit to light up, and the easiest to destroy.',
      scene: { kind: 'title' } },
    { text: 'It is a diode, which means current goes through it one way and not the other.',
      scene: { kind: 'circuit', variant: 'led', flow: true, label: 'One way only' } },
    { text: 'The longer leg is the anode, the positive side. The short leg beside the flat edge is the cathode.',
      scene: { kind: 'statement', lines: ['Long leg positive.', 'Short leg negative.'] } },
    { text: 'Put it in backwards and nothing at all happens. No light, no damage, no clue.',
      scene: { kind: 'circuit', variant: 'led', flow: true, highlight: 'reversed', label: 'Backwards, nothing' } },
    { text: 'So when an LED stays dark, turning it round is the very first thing to try.',
      scene: { kind: 'statement', lines: ['Dark?', 'Turn it round.'] } },
    { text: 'Now the part that does real damage. An LED barely resists current on its own.',
      scene: { kind: 'statement', lines: ['It does not', 'resist current'] } },
    { text: 'Connect one straight across five volts and the only thing limiting the current is your wire.',
      scene: { kind: 'circuit', variant: 'led', flow: true, highlight: 'nores', label: 'Nothing limiting it' } },
    { text: 'That is hundreds of milliamps through a part that wants twenty. It dies in a fraction of a second.',
      scene: { kind: 'statement', lines: ['Hundreds of mA', 'into a 20mA part'] } },
    { text: 'So an LED always gets a resistor in series with it. Every time, on every supply.',
      scene: { kind: 'circuit', variant: 'led', flow: true, highlight: 'resistor', label: 'Always a series resistor' } },
    { text: 'Sizing that resistor is where people go wrong, so let us do it properly.',
      scene: { kind: 'statement', lines: ['Now size it'] } },
    { text: 'An LED does not obey Ohm’s law. It holds a roughly fixed voltage across itself, called the forward voltage.',
      scene: { kind: 'statement', lines: ['A fixed drop,', 'not a resistance'] } },
    { text: 'A red LED sits around one point eight volts. Blue and white ones are near three.',
      scene: { kind: 'compare', left: 'Red 1.8V', right: 'Blue 3.0V', caption: 'The forward voltage is not yours to choose' } },
    { text: 'Whatever the LED takes, the resistor has to drop the rest. That is the whole calculation.',
      scene: { kind: 'statement', lines: ['The resistor gets', 'what is left'] } },
    { text: 'Five volt supply, two volt LED. Three volts left for the resistor.',
      scene: { kind: 'formula', expr: '5V - 2V = 3V' } },
    { text: 'Now pick a current. Fifteen milliamps is bright and safe for a small indicator LED.',
      scene: { kind: 'statement', lines: ['15mA is', 'a good target'] } },
    { text: 'Three volts divided by fifteen milliamps is two hundred ohms.',
      scene: { kind: 'formula', expr: '3V / 15mA = 200Ω' } },
    { text: 'Two hundred is not a value you can buy, so round up to two hundred and twenty.',
      scene: { kind: 'formula', expr: '200Ω → 220Ω', note: 'The nearest real part' } },
    { text: 'Always round up. Up means slightly less current, and slightly less current is always safe.',
      scene: { kind: 'compare', left: 'Round up', right: 'Round down', caption: 'Only one of these is safe' } },
    { text: 'Here is the mistake, and nearly everyone makes it once.',
      scene: { kind: 'statement', lines: ['The mistake'] } },
    { text: 'Forgetting to subtract the forward voltage. Five divided by two hundred and twenty gives twenty three milliamps.',
      scene: { kind: 'formula', expr: '5V / 220Ω = 23mA', note: 'Wrong' } },
    { text: 'The real answer is three divided by two hundred and twenty, which is thirteen point six.',
      scene: { kind: 'formula', expr: '3V / 220Ω = 13.6mA', note: 'Right' } },
    { text: 'Subtract the LED first. If your predicted current looks suspiciously round, you probably forgot.',
      scene: { kind: 'statement', lines: ['Subtract the LED', 'first'] } },
    { text: 'Change the supply and the resistor changes with it. Nine volts and the same LED needs four hundred and seventy ohms.',
      scene: { kind: 'formula', expr: '(9V - 2V) / 15mA = 470Ω' } },
    { text: 'Two LEDs in series drop their voltage twice. Two red ones take three point six volts out of your five.',
      scene: { kind: 'formula', expr: '5V - 3.6V = 1.4V' } },
    { text: 'Which leaves almost nothing for the resistor, and that is why stacking LEDs on five volts gets awkward fast.',
      scene: { kind: 'statement', lines: ['Not much left', 'to work with'] } },
    { text: 'Last check. Three volts at fourteen milliamps is forty two milliwatts, well inside a quarter watt part.',
      scene: { kind: 'formula', expr: '3V x 14mA = 42mW' } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. An LED is one way, and the long leg goes to the positive side.',
      scene: { kind: 'recap', items: ['Long leg to positive'] } },
    { text: 'Two. Never connect one without a series resistor, on any supply.',
      scene: { kind: 'recap', items: ['Long leg to positive', 'Never without a resistor'] } },
    { text: 'Three. Subtract the forward voltage, then divide by the current you want.',
      scene: { kind: 'recap', items: ['Long leg to positive', 'Never without a resistor', 'Subtract Vf, then divide'] } },
    { text: 'Go and work out the resistor for a blue LED on nine volts.',
      scene: { kind: 'outro' } },
  ],
};
