import type { LessonScript } from '../types';

/**
 * Unit 3, Sensors & Signals. Checkpoint for "The Light-Activated Alarm".
 *
 * The flagship build, and the first time the three stages appear as one thing.
 * The threshold gets the most screen time because it is the only part of this
 * circuit that cannot be looked up: it has to be measured on the bench the
 * learner is actually sitting at.
 */
export const lightAlarm: LessonScript = {
  id: 'light-alarm',
  title: 'The Light Alarm',
  unitTitle: 'Sensors & Signals',
  unitId: 'sensors',
  skillId: 'light-alarm',
  skillTitle: 'The Light-Activated Alarm',
  accent: '#84cc30',
  segments: [
    { text: 'Every useful circuit you will ever build has the same three stages.',
      scene: { kind: 'title' } },
    { text: 'Sense. Decide. Act.',
      scene: { kind: 'statement', lines: ['Sense.', 'Decide.', 'Act.'] } },
    { text: 'The light activated alarm is the smallest honest example, and you have already built both ends of it.',
      scene: { kind: 'statement', lines: ['You have built', 'both ends already'] } },
    { text: 'Sense is the LDR and a ten kilohm resistor in a divider.',
      scene: { kind: 'circuit', variant: 'divider', flow: true, highlight: 'ldr', label: 'Sense' } },
    { text: 'The midpoint goes to an analog pin, and that voltage rises and falls with the light.',
      scene: { kind: 'circuit', variant: 'divider', flow: true, highlight: 'ldr tap', label: 'The midpoint, to A0' } },
    { text: 'Act is an LED with its own series resistor, driven from a digital pin.',
      scene: { kind: 'circuit', variant: 'led', flow: true, highlight: 'resistor', label: 'Act' } },
    { text: 'Yes, the output LED still needs its resistor. Being an output does not exempt it.',
      scene: { kind: 'formula', expr: '(5V - 2V) / 220Ω = 13.6mA' } },
    { text: 'Decide sits between them, and it is one comparison in your code.',
      scene: { kind: 'statement', lines: ['Decide is one', 'comparison'] } },
    { text: 'If the reading falls below a threshold, turn the output on. Otherwise turn it off.',
      scene: { kind: 'formula', expr: 'if (reading < threshold)' } },
    { text: 'Which leaves exactly one number to choose, and it is the only real design decision here.',
      scene: { kind: 'statement', lines: ['One number', 'to choose'] } },
    { text: 'You cannot look up the threshold. It depends on your LDR, your resistor, and your room.',
      scene: { kind: 'statement', lines: ['Nobody can', 'look it up'] } },
    { text: 'So measure it. Print the reading, with the lights on, and write the number down.',
      scene: { kind: 'circuit', variant: 'board', flow: true, highlight: 'usb', label: 'Print it and read it' } },
    { text: 'Then cover the sensor with your hand and write that number down too.',
      scene: { kind: 'statement', lines: ['Bright number.', 'Dark number.'] } },
    { text: 'Say bright reads about eight hundred and dark reads about two hundred.',
      scene: { kind: 'compare', left: 'Bright ≈ 800', right: 'Dark ≈ 200', caption: 'Your two measured ends' } },
    { text: 'Put the threshold between them. Five hundred is the obvious choice.',
      scene: { kind: 'formula', expr: 'threshold = 500' } },
    { text: 'Set it at seven ninety instead and every passing shadow triggers your alarm.',
      scene: { kind: 'compare', left: '500: reliable', right: '790: twitchy', caption: 'Margin is the whole point' } },
    { text: 'Set it at two ten and it only fires in near total darkness, which is not what you asked for.',
      scene: { kind: 'statement', lines: ['Too close either way', 'and it misbehaves'] } },
    { text: 'Midway gives you three hundred counts of margin on both sides, and margin is what makes it feel solid.',
      scene: { kind: 'statement', lines: ['Margin is what', 'feels solid'] } },
    { text: 'There is one more refinement worth knowing, and it fixes the flicker at the boundary.',
      scene: { kind: 'statement', lines: ['One refinement'] } },
    { text: 'Right at the threshold, tiny changes in light make the reading cross back and forth.',
      scene: { kind: 'statement', lines: ['At the line,', 'it chatters'] } },
    { text: 'So the alarm flickers on and off several times a second, and it looks broken.',
      scene: { kind: 'statement', lines: ['Flickering looks', 'like a fault'] } },
    { text: 'The fix is two thresholds instead of one. Turn on below four fifty, turn off above five fifty.',
      scene: { kind: 'formula', expr: 'on below 450, off above 550' } },
    { text: 'That gap is called hysteresis, and it is in every thermostat you have ever used.',
      scene: { kind: 'statement', lines: ['That gap has', 'a name: hysteresis'] } },
    { text: 'Now wire the whole thing, and be careful about one node.',
      scene: { kind: 'circuit', variant: 'divider', flow: true, highlight: 'ldr tap', label: 'The one node to get right' } },
    { text: 'Five volts to the LDR. LDR to the junction. Junction to the ten kilohm, and on to ground.',
      scene: { kind: 'statement', lines: ['5V, LDR,', 'junction, 10k, ground'] } },
    { text: 'And the junction also goes to the analog pin. Miss that wire and the reading never moves.',
      scene: { kind: 'statement', lines: ['The junction feeds', 'the pin as well'] } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. Sense, decide, act. The divider senses, your code decides, the LED acts.',
      scene: { kind: 'recap', items: ['Sense, decide, act'] } },
    { text: 'Two. Measure your bright and dark readings, then put the threshold midway between them.',
      scene: { kind: 'recap', items: ['Sense, decide, act', 'Measure both ends, then split them'] } },
    { text: 'Three. Two thresholds instead of one stop the flicker at the boundary.',
      scene: { kind: 'recap', items: ['Sense, decide, act', 'Measure both ends, then split them', 'Hysteresis stops the chatter'] } },
    { text: 'Go and build it, then find the light level where yours actually trips.',
      scene: { kind: 'outro' } },
  ],
};
