import type { LessonScript } from '../types';

/**
 * Unit 10, Power Supplies & Regulation. Checkpoint for "Linear Regulation".
 *
 * Two numbers decide every linear regulator design and a learner rarely
 * calculates either: the dropout that sets the minimum input, and the wattage
 * that decides whether the chip needs a heatsink or a different topology.
 */
export const linearRegulation: LessonScript = {
  id: 'linear-regulation',
  title: 'Linear Regulation',
  unitTitle: 'Power Supplies & Regulation',
  unitId: 'power-supplies',
  skillId: 'linear-regulation',
  skillTitle: 'Linear Regulation',
  accent: '#f2b705',
  segments: [
    { text: 'A regulator takes a voltage that moves and gives you one that does not. Here is what that costs.',
      scene: { kind: 'title' } },
    { text: 'Start with the simplest one, which is a single diode used backwards.',
      scene: { kind: 'statement', lines: ['A diode,', 'used backwards'] } },
    { text: 'A zener diode breaks down at a precise reverse voltage, and then holds it.',
      scene: { kind: 'statement', lines: ['It breaks down,', 'on purpose'] } },
    { text: 'Wire it in reverse with a series resistor, and the node it sits on is pinned at the zener voltage.',
      scene: { kind: 'statement', lines: ['Pinned at', 'the zener voltage'] } },
    { text: 'The resistor drops the difference and sets the current, so you size it with Ohm’s law.',
      scene: { kind: 'formula', expr: 'R = (Vin − Vz) / I' } },
    { text: 'Nine volts in, a three point three volt zener, five milliamps. Five point seven over five is about one kilohm.',
      scene: { kind: 'formula', expr: '5.7V / 5mA = 1.1kΩ' } },
    { text: 'That gives you a solid voltage reference, useful for a comparator threshold.',
      scene: { kind: 'statement', lines: ['A reference,', 'not a supply'] } },
    { text: 'But the resistor has to pass the load current too, so it cannot feed anything real.',
      scene: { kind: 'statement', lines: ['It cannot', 'feed a load'] } },
    { text: 'So for a real supply you use a chip, and the classic one has three pins.',
      scene: { kind: 'circuit', variant: 'regulator', flow: true, highlight: 'reg', label: 'In, ground, out' } },
    { text: 'A 7805. Feed it a higher, roughly smoothed DC and it hands you a steady five volts.',
      scene: { kind: 'statement', lines: ['The last two digits', 'are the output'] } },
    { text: 'Inside, a feedback loop adjusts a pass transistor continuously to hold the output steady.',
      scene: { kind: 'statement', lines: ['A transistor,', 'constantly adjusted'] } },
    { text: 'It needs a capacitor on the input and one on the output, or the feedback loop can oscillate.',
      scene: { kind: 'circuit', variant: 'regulator', flow: true, highlight: 'cin cout', label: 'Both capacitors, always' } },
    { text: 'Now the first number that decides your design. Dropout.',
      scene: { kind: 'statement', lines: ['Number one:', 'dropout'] } },
    { text: 'A linear regulator only goes downhill, and it needs headroom to do it.',
      scene: { kind: 'statement', lines: ['Downhill only,', 'with headroom'] } },
    { text: 'A standard 7805 needs about two volts, so you must feed it seven or more to get a clean five.',
      scene: { kind: 'formula', expr: '5V + 2V dropout = 7V in' } },
    { text: 'Feed it six and the output is neither six nor five. It just follows the input down.',
      scene: { kind: 'statement', lines: ['Below dropout,', 'it stops regulating'] } },
    { text: 'Which is why a 7805 cannot make five volts from a three point seven volt lithium cell. Nothing will.',
      scene: { kind: 'compare', left: 'Needs 7V in', right: 'Battery gives 3.7V', caption: 'A linear regulator cannot go up' } },
    { text: 'There is a family called low dropout, or L D O, that needs only a few tenths of a volt.',
      scene: { kind: 'formula', expr: 'LDO: 5V + 0.3V = 5.3V in' } },
    { text: 'On a draining battery an L D O keeps regulating far longer.',
      scene: { kind: 'statement', lines: ['Less headroom,', 'longer life'] } },
    { text: 'Now the second number, and it is the one that surprises people at the bench.',
      scene: { kind: 'statement', lines: ['Number two:', 'the heat'] } },
    { text: 'The voltage a linear regulator does not pass on, it turns into heat. All of it.',
      scene: { kind: 'formula', expr: 'P = (Vin − Vout) x Iout' } },
    { text: 'Twelve volts down to five at half an amp. Seven times nought point five is three and a half watts.',
      scene: { kind: 'formula', expr: '7V x 0.5A = 3.5W' } },
    { text: 'Three and a half watts out of a chip the size of your fingernail, and it will burn you.',
      scene: { kind: 'circuit', variant: 'regulator', flow: true, highlight: 'heat', label: 'All of it, as heat' } },
    { text: 'At one amp it is seven watts, and without a heatsink it shuts down or fails.',
      scene: { kind: 'compare', left: '0.5A: warm', right: '1A: needs a heatsink', caption: 'The same circuit, twice the current' } },
    { text: 'Efficiency is just the output voltage over the input voltage. Twelve to five is forty two percent.',
      scene: { kind: 'formula', expr: '5V / 12V = 42%' } },
    { text: 'So more than half the energy is heat. That is the trade a linear regulator asks you to make.',
      scene: { kind: 'statement', lines: ['Simple and quiet.', 'And wasteful.'] } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. A zener plus a resistor is a reference, not a supply, and the resistor sets its current.',
      scene: { kind: 'recap', items: ['A zener is a reference, not a supply'] } },
    { text: 'Two. A linear regulator only goes downhill, and it needs its dropout voltage of headroom.',
      scene: { kind: 'recap', items: ['A zener is a reference, not a supply', 'Downhill only, and it needs headroom'] } },
    { text: 'Three. The voltage it drops times the current is heat, and that number decides your design.',
      scene: { kind: 'recap', items: ['A zener is a reference, not a supply', 'Downhill only, and it needs headroom', 'The dropped voltage becomes heat'] } },
    { text: 'Go and work out the wattage of the regulator in something you already own.',
      scene: { kind: 'outro' } },
  ],
};
