import type { LessonScript } from '../types';

/**
 * Unit 11, Digital Logic & Embedded. Checkpoint for "Logic Gates".
 *
 * Gates are the one topic in the curriculum where the drawing IS the content,
 * so the film runs each gate as a picture with real input chips and a computed
 * output rather than as a truth table read aloud.
 */
export const logicGates: LessonScript = {
  id: 'logic-gates',
  title: 'Logic Gates',
  unitTitle: 'Digital Logic & Embedded',
  unitId: 'digital-logic',
  skillId: 'logic-gates',
  skillTitle: 'Logic Gates',
  accent: '#549cf0',
  segments: [
    { text: 'A logic gate takes bits in and gives one bit out, following a rule that never changes.',
      scene: { kind: 'title' } },
    { text: 'There are three you have to know, and everything else is built from them.',
      scene: { kind: 'statement', lines: ['Three to start'] } },
    { text: 'An AND gate outputs a one only when every input is a one.',
      scene: { kind: 'circuit', variant: 'gate', flow: true, highlight: 'and 1 1', label: 'AND: both, or nothing' } },
    { text: 'Drop either input to nought and the output goes to nought immediately.',
      scene: { kind: 'circuit', variant: 'gate', flow: true, highlight: 'and 1 0', label: 'One low is enough' } },
    { text: 'An OR gate outputs a one when any input is a one.',
      scene: { kind: 'circuit', variant: 'gate', flow: true, highlight: 'or 1 0', label: 'OR: any one will do' } },
    { text: 'And a NOT gate, an inverter, simply gives you the opposite of its single input.',
      scene: { kind: 'circuit', variant: 'gate', flow: true, highlight: 'not 1', label: 'NOT: the opposite' } },
    { text: 'The small circle on the output is what marks an inversion, and you will see it everywhere.',
      scene: { kind: 'statement', lines: ['The bubble', 'means inverted'] } },
    { text: 'Because the useful gates are the inverted ones. Put a bubble on an AND and you get a NAND.',
      scene: { kind: 'circuit', variant: 'gate', flow: true, highlight: 'nand 1 1', label: 'NAND: AND, inverted' } },
    { text: 'NAND is low only when every input is high, and high in every other case.',
      scene: { kind: 'statement', lines: ['Low in one case.', 'High in three.'] } },
    { text: 'A bubble on an OR gives a NOR, low whenever any input is high.',
      scene: { kind: 'circuit', variant: 'gate', flow: true, highlight: 'nor 0 0', label: 'NOR: OR, inverted' } },
    { text: 'And the odd one out is exclusive OR, written XOR. High only when the inputs differ.',
      scene: { kind: 'circuit', variant: 'gate', flow: true, highlight: 'xor 1 0', label: 'XOR: only when they differ' } },
    { text: 'Feed it two ones and it goes low, which is what makes it different from a plain OR.',
      scene: { kind: 'circuit', variant: 'gate', flow: true, highlight: 'xor 1 1', label: 'Both high, so low' } },
    { text: 'Now the fact that built the computer you are watching this on.',
      scene: { kind: 'statement', lines: ['One fact,', 'and it is big'] } },
    { text: 'NAND is universal. Any logic function at all can be built from nothing but NAND gates.',
      scene: { kind: 'statement', lines: ['NAND alone', 'is enough'] } },
    { text: 'Tie both inputs of a NAND together and it behaves as an inverter, because NAND of X with X is not X.',
      scene: { kind: 'circuit', variant: 'gate', flow: true, highlight: 'nand 0 0', label: 'A NAND, tied, is a NOT' } },
    { text: 'Get NOT, and you can get AND, and then OR, and then everything.',
      scene: { kind: 'statement', lines: ['NOT, then AND,', 'then everything'] } },
    { text: 'NOR is universal too, and whole generations of chips were built from one gate type for exactly this reason.',
      scene: { kind: 'statement', lines: ['One gate type,', 'whole machines'] } },
    { text: 'Wire gates together and the output depends only on the inputs right now. That is combinational logic.',
      scene: { kind: 'statement', lines: ['No memory.', 'Just now.'] } },
    { text: 'And here is the classic example, which is how a computer actually adds.',
      scene: { kind: 'statement', lines: ['How a computer', 'adds'] } },
    { text: 'Add two single bits. Nought and nought is nought. One and nought is one.',
      scene: { kind: 'formula', expr: '0+0=0, 1+0=1' } },
    { text: 'And one plus one is two, which in binary is one nought. So you need two output bits.',
      scene: { kind: 'formula', expr: '1 + 1 = 10' } },
    { text: 'The right hand bit, the sum, is high when the inputs differ. That is exactly XOR.',
      scene: { kind: 'circuit', variant: 'gate', flow: true, highlight: 'xor 1 1', label: 'Sum: an XOR gate' } },
    { text: 'The left hand bit, the carry, is high only when both inputs are high. That is exactly AND.',
      scene: { kind: 'circuit', variant: 'gate', flow: true, highlight: 'and 1 1', label: 'Carry: an AND gate' } },
    { text: 'Two gates, and you have a half adder. Stack them properly and you can add any two numbers.',
      scene: { kind: 'statement', lines: ['Two gates.', 'One adder.'] } },
    { text: 'It is called a half adder because it cannot accept a carry coming in from the bit below.',
      scene: { kind: 'statement', lines: ['Half, because', 'no carry in'] } },
    { text: 'One tool for simplifying all of this. De Morgan says break the bar, and flip the operator underneath.',
      scene: { kind: 'formula', expr: 'NOT(A AND B) = NOT A OR NOT B' } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. AND needs all, OR needs any, NOT flips, and a bubble on the output means inverted.',
      scene: { kind: 'recap', items: ['AND all, OR any, NOT flips'] } },
    { text: 'Two. NAND and NOR are universal, so either one alone can build every other gate.',
      scene: { kind: 'recap', items: ['AND all, OR any, NOT flips', 'NAND alone can build anything'] } },
    { text: 'Three. XOR gives the sum bit and AND gives the carry, and that is binary addition.',
      scene: { kind: 'recap', items: ['AND all, OR any, NOT flips', 'NAND alone can build anything', 'XOR and AND make an adder'] } },
    { text: 'Go and build an inverter from a NAND gate, and check it with a meter.',
      scene: { kind: 'outro' } },
  ],
};
