import type { LessonScript } from '../types';

/**
 * Unit 10, Power Supplies & Regulation. Checkpoint for "Making Clean DC".
 *
 * The chain from a wall transformer to a usable rail, in the order the parts
 * physically sit. The film is careful about the one number that surprises
 * everyone: a smoothed rail sits at the PEAK of the AC, not at its RMS value.
 */
export const makingDc: LessonScript = {
  id: 'making-dc',
  title: 'Making Clean DC',
  unitTitle: 'Power Supplies & Regulation',
  unitId: 'power-supplies',
  skillId: 'making-dc',
  skillTitle: 'Making Clean DC',
  accent: '#f2b705',
  segments: [
    { text: 'Your circuit wants a steady voltage. Almost nothing in the real world gives you one.',
      scene: { kind: 'title' } },
    { text: 'A battery sags as it drains. A wall adapter is noisy. And your own circuit’s demand keeps changing.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'ripple', label: 'What you actually have' } },
    { text: 'A microcontroller wants five volts, or three point three, and it is fussy in both directions.',
      scene: { kind: 'compare', left: 'Too high: damage', right: 'Too low: resets', caption: 'Neither of these is subtle' } },
    { text: 'So we build a chain that turns something messy into something steady, one stage at a time.',
      scene: { kind: 'statement', lines: ['A chain,', 'stage by stage'] } },
    { text: 'Start from mains AC, which swings above and below zero fifty times a second.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'sine', label: 'What comes in' } },
    { text: 'A transformer drops it to something safe first, and that part is not yours to improvise.',
      scene: { kind: 'statement', lines: ['Mains is not', 'for improvising'] } },
    { text: 'Then rectification, which is turning an AC that goes both ways into a DC that goes one way.',
      scene: { kind: 'statement', lines: ['Rectify:', 'one way only'] } },
    { text: 'A diode passes current one way and blocks the other, so one diode chops off half the wave.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'halfwave', label: 'Half wave: one diode' } },
    { text: 'That works, but you have thrown away half your power and left enormous gaps to fill.',
      scene: { kind: 'statement', lines: ['Half wasted.', 'Big gaps.'] } },
    { text: 'Four diodes in a bridge do far better. Whichever way the input swings, the load sees the same polarity.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'fullwave', label: 'Full wave: four diodes' } },
    { text: 'Now you get two humps per cycle instead of one, so the gaps are half as long.',
      scene: { kind: 'statement', lines: ['Twice the humps,', 'half the gaps'] } },
    { text: 'It is still not DC, though. It is a series of humps, and nothing wants to run on that.',
      scene: { kind: 'statement', lines: ['Humps are', 'not DC'] } },
    { text: 'So next comes the reservoir capacitor, and it does exactly what you learned in unit six.',
      scene: { kind: 'circuit', variant: 'regulator', flow: true, highlight: 'cin', label: 'A big electrolytic' } },
    { text: 'It charges to the top of each hump and then discharges into your load through the gap.',
      scene: { kind: 'statement', lines: ['Charge at the top.', 'Give in the gap.'] } },
    { text: 'What is left is a mostly flat voltage with a small sawtooth on it, and that wobble is called ripple.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'ripple', label: 'Ripple: what is left over' } },
    { text: 'More capacitance means less ripple. So does drawing less current.',
      scene: { kind: 'compare', left: 'Bigger C: less ripple', right: 'More load: more ripple', caption: 'Both pull on the same wobble' } },
    { text: 'And now the number that catches almost everyone out.',
      scene: { kind: 'statement', lines: ['The number that', 'catches people'] } },
    { text: 'A nine volt transformer output is nine volts R M S. That is not what your capacitor charges to.',
      scene: { kind: 'statement', lines: ['9V RMS is not', '9V on the cap'] } },
    { text: 'The capacitor charges to the peak, which is one point four one times the R M S value.',
      scene: { kind: 'formula', expr: '1.414 x 9V = 12.7V' } },
    { text: 'Take off about one and a half volts for the two diodes in the bridge, and you have around eleven.',
      scene: { kind: 'formula', expr: '12.7V - 1.4V ≈ 11.3V' } },
    { text: 'So a nine volt transformer gives you eleven volts of DC, and a capacitor rated at ten will not survive it.',
      scene: { kind: 'compare', left: 'Expected 9V', right: 'Got 11.3V', caption: 'Rate your capacitor for the peak' } },
    { text: 'Even after all that, the rail still moves. It has ripple, and it drops as the load rises.',
      scene: { kind: 'statement', lines: ['It still', 'moves'] } },
    { text: 'Which is why a regulator comes last, and why smoothing alone is never the whole answer.',
      scene: { kind: 'circuit', variant: 'regulator', flow: true, highlight: 'reg', label: 'And then a regulator' } },
    { text: 'The regulator’s job is to take that wobbling eleven volts and hold five volts steady, whatever happens.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'smooth', label: 'What comes out' } },
    { text: 'And it needs headroom to do it, so it needs an input comfortably above its output.',
      scene: { kind: 'statement', lines: ['It needs', 'headroom'] } },
    { text: 'That is why the smoothing stage still matters. The regulator has to be fed something that never dips too low.',
      scene: { kind: 'statement', lines: ['Feed it something', 'that never dips'] } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. Rectify with a bridge, because four diodes use both halves and leave smaller gaps.',
      scene: { kind: 'recap', items: ['A bridge uses both halves'] } },
    { text: 'Two. A reservoir capacitor fills the gaps, and what is left over is ripple.',
      scene: { kind: 'recap', items: ['A bridge uses both halves', 'The reservoir fills the gaps'] } },
    { text: 'Three. The capacitor charges to the peak, so a nine volt winding gives about eleven volts of DC.',
      scene: { kind: 'recap', items: ['A bridge uses both halves', 'The reservoir fills the gaps', 'It charges to the peak, not the RMS'] } },
    { text: 'Go and work out what a twelve volt transformer actually puts on your capacitor.',
      scene: { kind: 'outro' } },
  ],
};
