import type { LessonScript } from '../types';

/**
 * Unit 6, Capacitors, RC & Timing. Checkpoint for "Meet the Capacitor".
 *
 * Two things a learner has to get right before any RC circuit works: the prefix
 * ladder, where a slip is a thousandfold error in the timing, and the stripe on
 * an electrolytic, where a slip is a component venting on the bench.
 */
export const meetCapacitor: LessonScript = {
  id: 'meet-capacitor',
  title: 'Meet the Capacitor',
  unitTitle: 'Capacitors, RC & Timing',
  unitId: 'capacitors-rc',
  skillId: 'meet-capacitor',
  skillTitle: 'Meet the Capacitor',
  accent: '#549cf0',
  segments: [
    { text: 'A resistor decides how much current flows. A capacitor decides how fast a voltage is allowed to change.',
      scene: { kind: 'title' } },
    { text: 'Inside are two conducting plates with an insulator between them, called the dielectric.',
      scene: { kind: 'circuit', variant: 'rc', flow: false, label: 'Two plates, an insulator' } },
    { text: 'Nothing crosses that gap. Charge simply piles up on one plate and is pushed off the other.',
      scene: { kind: 'statement', lines: ['Nothing crosses.', 'Charge piles up.'] } },
    { text: 'Connect it to a supply and the voltage across it climbs until it matches.',
      scene: { kind: 'circuit', variant: 'rc', flow: true, label: 'It fills up' } },
    { text: 'Disconnect it and the charge stays there, so the capacitor holds its voltage.',
      scene: { kind: 'statement', lines: ['Disconnected,', 'still charged'] } },
    { text: 'And here is the one property everything else follows from. It resists a change in its own voltage.',
      scene: { kind: 'statement', lines: ['It resists', 'a change'] } },
    { text: 'Not current. Voltage. A capacitor voltage cannot jump, it can only charge or discharge.',
      scene: { kind: 'compare', left: 'Voltage: gradual', right: 'Voltage: instant', caption: 'Only one of these is possible' } },
    { text: 'That is why it smooths a wobbly supply, and why it can be a timer, and why it passes a signal.',
      scene: { kind: 'statement', lines: ['One property.', 'Three jobs.'] } },
    { text: 'Now the value, and the unit that will trip you up.',
      scene: { kind: 'statement', lines: ['Now the value'] } },
    { text: 'Capacitance is measured in farads. One farad is an enormous amount.',
      scene: { kind: 'statement', lines: ['A farad is', 'enormous'] } },
    { text: 'So real parts are fractions of one. Microfarads, nanofarads and picofarads.',
      scene: { kind: 'formula', expr: 'pF → nF → µF → F' } },
    { text: 'Each step up the ladder is a thousand times bigger, and every step matters.',
      scene: { kind: 'formula', expr: '1µF = 1000nF = 1000000pF' } },
    { text: 'One hundred nanofarads and nought point one microfarads are the same part, written two ways.',
      scene: { kind: 'compare', left: '100nF', right: '0.1µF', caption: 'The same capacitor' } },
    { text: 'And ceramic capacitors are marked like resistors, in picofarads. A part marked one nought four is not one hundred and four.',
      scene: { kind: 'formula', expr: '104 = 10 with 4 zeros pF' } },
    { text: 'It is ten, followed by four zeros, in picofarads. One hundred thousand picofarads, which is one hundred nanofarads.',
      scene: { kind: 'statement', lines: ['A 104 is', '100nF'] } },
    { text: 'Get a prefix wrong and you are out by a factor of a thousand.',
      scene: { kind: 'statement', lines: ['Wrong prefix,', 'wrong by 1000'] } },
    { text: 'Fit ten nanofarads where you needed ten microfarads and your one second delay lasts a millisecond.',
      scene: { kind: 'compare', left: 'Wanted 1 second', right: 'Got 1 millisecond', caption: 'One prefix, the whole design' } },
    { text: 'Two families, and you will use both constantly.',
      scene: { kind: 'statement', lines: ['Two families'] } },
    { text: 'Ceramics are small, cheap and have no polarity. Either leg either way, every time.',
      scene: { kind: 'statement', lines: ['Ceramic:', 'no polarity'] } },
    { text: 'They cover picofarads up to a few microfarads, and the hundred nanofarad ceramic is the most used part in electronics.',
      scene: { kind: 'statement', lines: ['100nF is', 'everywhere'] } },
    { text: 'Electrolytics pack far more into a small can. Microfarads up to thousands of them.',
      scene: { kind: 'statement', lines: ['Electrolytic:', 'much bigger values'] } },
    { text: 'And they are polarised, which is the part that matters.',
      scene: { kind: 'compare', left: 'Ceramic: either way', right: 'Electrolytic: one way', caption: 'This one is not a preference' } },
    { text: 'The negative lead is marked with a stripe down the can, and it is usually the shorter leg.',
      scene: { kind: 'statement', lines: ['The stripe is', 'the negative'] } },
    { text: 'Wire one backwards and it heats, the electrolyte boils, and it vents or pops.',
      scene: { kind: 'statement', lines: ['Backwards,', 'it vents'] } },
    { text: 'One last warning, and it is a genuine safety point.',
      scene: { kind: 'statement', lines: ['A safety point'] } },
    { text: 'A large charged capacitor stays charged after you remove power. Unplugged does not mean empty.',
      scene: { kind: 'statement', lines: ['Unplugged is', 'not empty'] } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. A capacitor stores charge, and it resists a change in its own voltage.',
      scene: { kind: 'recap', items: ['It resists a change in voltage'] } },
    { text: 'Two. Each prefix step is a thousand, and one hundred nanofarads is nought point one microfarads.',
      scene: { kind: 'recap', items: ['It resists a change in voltage', 'Each prefix step is 1000'] } },
    { text: 'Three. Ceramics go either way. Electrolytics have a stripe, and it is not optional.',
      scene: { kind: 'recap', items: ['It resists a change in voltage', 'Each prefix step is 1000', 'The stripe is the negative lead'] } },
    { text: 'Go and find a part marked one nought four in your kit, and work out its value.',
      scene: { kind: 'outro' } },
  ],
};
