import type { LessonScript } from '../types';

/**
 * Unit 11, Digital Logic & Embedded. Checkpoint for "Memory & Sequencing".
 *
 * Where a circuit stops being a function and starts being a machine. The film
 * leans on the shift register at the end because it is the moment a learner
 * sees why any of this matters: eight LEDs from two pins.
 */
export const memoryAndSequencing: LessonScript = {
  id: 'memory-and-sequencing',
  title: 'Memory and Sequencing',
  unitTitle: 'Digital Logic & Embedded',
  unitId: 'digital-logic',
  skillId: 'memory-and-sequencing',
  skillTitle: 'Memory & Sequencing',
  accent: '#549cf0',
  segments: [
    { text: 'Every gate you have met forgets instantly. Change the inputs and the output changes with them.',
      scene: { kind: 'title' } },
    { text: 'To build anything that behaves like a machine, you need a circuit that remembers.',
      scene: { kind: 'statement', lines: ['Something that', 'remembers'] } },
    { text: 'The smallest one holds a single bit, and it is called a flip-flop.',
      scene: { kind: 'circuit', variant: 'gate', flow: true, highlight: 'ff 1 1', label: 'One bit of memory' } },
    { text: 'It has two outputs, Q and not Q, and they are always in opposite states.',
      scene: { kind: 'statement', lines: ['Q, and not Q,', 'always opposite'] } },
    { text: 'And the trick that makes it remember is beautifully simple. You cross couple two gates.',
      scene: { kind: 'statement', lines: ['Two gates,', 'crossed over'] } },
    { text: 'Each gate’s output feeds the other gate’s input, so each one holds the other in place.',
      scene: { kind: 'statement', lines: ['Each one holds', 'the other'] } },
    { text: 'That gives you an S R latch. Set drives Q high, reset drives Q low, and neither means hold.',
      scene: { kind: 'compare', left: 'Set: Q goes high', right: 'Reset: Q goes low', caption: 'And neither means keep what you had' } },
    { text: 'But it has an illegal state. Assert set and reset together and the two outputs cannot stay opposite.',
      scene: { kind: 'statement', lines: ['Both at once', 'is forbidden'] } },
    { text: 'So the standard memory cell is a D flip-flop, and it removes that problem entirely.',
      scene: { kind: 'circuit', variant: 'gate', flow: true, highlight: 'ff 1 1', label: 'One data input, one clock' } },
    { text: 'One data input, one clock input. Whatever D is at the clock edge is what gets stored.',
      scene: { kind: 'statement', lines: ['Whatever D is', 'at the edge'] } },
    { text: 'Because there is only one input, set and reset can never be asserted together. The illegal state is gone.',
      scene: { kind: 'statement', lines: ['One input,', 'no illegal state'] } },
    { text: 'Now the clock, which is the other half of everything in this film.',
      scene: { kind: 'statement', lines: ['Now the clock'] } },
    { text: 'A clock is a free running square wave, ticking high and low at a fixed rate.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'square', label: 'A steady heartbeat' } },
    { text: 'Logic that uses memory and a clock together is called sequential logic.',
      scene: { kind: 'compare', left: 'Combinational: now', right: 'Sequential: now and before', caption: 'Memory is the difference' } },
    { text: 'And almost everything clocked acts on an edge, not on the level.',
      scene: { kind: 'statement', lines: ['On the edge,', 'not the level'] } },
    { text: 'A rising edge is the instant it goes from low to high. A falling edge is the opposite.',
      scene: { kind: 'statement', lines: ['Rising: low to high.', 'Falling: high to low.'] } },
    { text: 'Using the instant rather than the whole high period is what keeps a system in step.',
      scene: { kind: 'statement', lines: ['One instant', 'per tick'] } },
    { text: 'Every flip-flop updates on the same tick, so data ripples through in order rather than racing.',
      scene: { kind: 'statement', lines: ['In order,', 'not racing'] } },
    { text: 'Now chain flip-flops together and you get something that counts.',
      scene: { kind: 'statement', lines: ['Chain them,', 'and they count'] } },
    { text: 'A counter adds one to its stored value on every clock pulse. Four bits counts nought to fifteen.',
      scene: { kind: 'formula', expr: '4 bits = 0 to 15, then 0' } },
    { text: 'Then it rolls over to nought and starts again, which is where an overflow bug comes from.',
      scene: { kind: 'statement', lines: ['It rolls over.', 'Quietly.'] } },
    { text: 'A row of flip-flops clocked together instead of chained is called a register.',
      scene: { kind: 'statement', lines: ['A row of them', 'is a register'] } },
    { text: 'Eight flip-flops hold a byte. Counters count, and registers store.',
      scene: { kind: 'formula', expr: '8 flip-flops = 1 byte' } },
    { text: 'And one variation of a register is genuinely useful the first week you own one.',
      scene: { kind: 'statement', lines: ['One variation,', 'immediately useful'] } },
    { text: 'A shift register passes its bits along one position on every clock tick.',
      scene: { kind: 'statement', lines: ['Each tick,', 'everything shifts'] } },
    { text: 'So you clock eight bits in from one pin, and it holds all eight out at once. Eight LEDs, two pins.',
      scene: { kind: 'compare', left: 'Eight pins', right: 'Data and clock', caption: 'The same eight LEDs' } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. A flip-flop holds one bit, and cross coupled gates are what make it hold.',
      scene: { kind: 'recap', items: ['A flip-flop holds one bit'] } },
    { text: 'Two. A D flip-flop stores its data input on a clock edge, and has no illegal state.',
      scene: { kind: 'recap', items: ['A flip-flop holds one bit', 'D captures on the clock edge'] } },
    { text: 'Three. Chained they count, in a row they store, and shifted they turn two pins into eight.',
      scene: { kind: 'recap', items: ['A flip-flop holds one bit', 'D captures on the clock edge', 'Counters count, registers store'] } },
    { text: 'Go and drive eight LEDs from a shift register. It is the cheapest upgrade there is.',
      scene: { kind: 'outro' } },
  ],
};
