import type { LessonScript } from '../types';

/**
 * Unit 11, Digital Logic & Embedded. Checkpoint for "Numbers & Logic Levels".
 *
 * The film answers a question the lessons only imply: why is digital MORE
 * robust than analog, when it is built out of the same imperfect voltages? The
 * answer is noise margin, and it is worth the screen time.
 */
export const numbersAndLevels: LessonScript = {
  id: 'numbers-and-levels',
  title: 'Numbers and Levels',
  unitTitle: 'Digital Logic & Embedded',
  unitId: 'digital-logic',
  skillId: 'numbers-and-levels',
  skillTitle: 'Numbers & Logic Levels',
  accent: '#549cf0',
  segments: [
    { text: 'Digital counts in twos, and not because binary is elegant. Because a wire is.',
      scene: { kind: 'title' } },
    { text: 'A digital wire has two states. Pushed up to the supply, or pulled down to ground.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'square', label: 'Two states, nothing between' } },
    { text: 'So each wire carries one binary digit, one bit, and a bit is nought or one.',
      scene: { kind: 'statement', lines: ['One wire.', 'One bit.'] } },
    { text: 'In binary each place is worth twice the one to its right. One, two, four, eight, and on.',
      scene: { kind: 'formula', expr: '1011 = 8 + 2 + 1 = 11' } },
    { text: 'Eight bits together make a byte, and a byte holds two hundred and fifty six different values.',
      scene: { kind: 'formula', expr: '2⁸ = 256 values' } },
    { text: 'Which is why so many limits in code are two fifty five. That is one byte.',
      scene: { kind: 'statement', lines: ['255 is not', 'arbitrary'] } },
    { text: 'Long binary is unreadable, so we group it in fours and write each group in hex.',
      scene: { kind: 'formula', expr: '1011 0010 = B2' } },
    { text: 'Hex runs nought to nine, then A to F. Four bits, one character, and nothing is lost.',
      scene: { kind: 'statement', lines: ['Four bits fit', 'in one character'] } },
    { text: 'Now the electrical side, and the thing that makes any of this work on a real board.',
      scene: { kind: 'statement', lines: ['Now the', 'electrical side'] } },
    { text: 'A digital input does not need an exact voltage. It needs to be clearly one side of a line.',
      scene: { kind: 'statement', lines: ['Clearly one side.', 'That is all.'] } },
    { text: 'On five volt logic, anything below about nought point eight volts reads as a low.',
      scene: { kind: 'formula', expr: 'below 0.8V = LOW' } },
    { text: 'Anything above about two volts reads as a high. Two volts, on a five volt system.',
      scene: { kind: 'formula', expr: 'above 2.0V = HIGH' } },
    { text: 'Between them is a band the input is not supposed to sit in, called the forbidden zone.',
      scene: { kind: 'compare', left: 'Below 0.8V', right: 'Above 2.0V', caption: 'And a forbidden band between' } },
    { text: 'Now notice what the outputs do, because this is where the robustness comes from.',
      scene: { kind: 'statement', lines: ['Now look at', 'the outputs'] } },
    { text: 'An output driving high goes to nearly five volts, not to the two it needs to be believed.',
      scene: { kind: 'statement', lines: ['It drives to 5,', 'and 2 would do'] } },
    { text: 'And driving low it goes to nearly nought, not to the nought point eight it could get away with.',
      scene: { kind: 'statement', lines: ['It drives to 0,', 'and 0.8 would do'] } },
    { text: 'That leftover slack is called noise margin, and it is worth about three volts at each end.',
      scene: { kind: 'formula', expr: '5V driven, 2V needed' } },
    { text: 'So a few hundred millivolts of picked up noise changes nothing. The level is still unambiguous.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'noise', label: 'Noise, and it still reads right' } },
    { text: 'That is why digital survives noise that would ruin an analog voltage.',
      scene: { kind: 'compare', left: 'Analog: noise is error', right: 'Digital: noise is ignored', caption: 'The same noise, two fates' } },
    { text: 'With one exception, and it is the one that produces baffling glitches.',
      scene: { kind: 'statement', lines: ['With one', 'exception'] } },
    { text: 'A slowly rising signal lingers inside the forbidden zone as it crosses.',
      scene: { kind: 'statement', lines: ['A slow edge', 'lingers'] } },
    { text: 'While it is in there, small wobbles flip the input back and forth, and the output glitches.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'bounce', label: 'Glitching on a slow edge' } },
    { text: 'Which is exactly what a Schmitt trigger input is for. Two thresholds, and the wobble fits between them.',
      scene: { kind: 'statement', lines: ['Hysteresis,', 'again'] } },
    { text: 'Last piece. The world outside is analog, and something has to translate.',
      scene: { kind: 'circuit', variant: 'divider', flow: true, highlight: 'tap', label: 'A smooth voltage, coming in' } },
    { text: 'An analog to digital converter samples a voltage and rounds it to the nearest of a fixed set of steps.',
      scene: { kind: 'statement', lines: ['Sample.', 'Then round.'] } },
    { text: 'Ten bits gives one thousand and twenty four steps, and that rounding error is called quantisation.',
      scene: { kind: 'formula', expr: '2¹⁰ = 1024 steps' } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. A bit is one wire in one of two states, and eight of them make two fifty six values.',
      scene: { kind: 'recap', items: ['One wire, one bit, two states'] } },
    { text: 'Two. Low is below nought point eight, high is above two, and the band between is forbidden.',
      scene: { kind: 'recap', items: ['One wire, one bit, two states', 'Thresholds, not exact voltages'] } },
    { text: 'Three. Outputs drive far past the thresholds, and that noise margin is why digital is robust.',
      scene: { kind: 'recap', items: ['One wire, one bit, two states', 'Thresholds, not exact voltages', 'Noise margin is the whole trick'] } },
    { text: 'Go and measure a logic high on a real pin. It will not be exactly five volts.',
      scene: { kind: 'outro' } },
  ],
};
