import type { LessonScript } from '../types';

/**
 * Unit 8, Op-Amps & Signal Conditioning. Checkpoint for "The Op-Amp".
 *
 * The film exists to make one counter-intuitive move land: a part with a gain
 * of a hundred thousand is USEFUL because you throw almost all of that gain
 * away. The golden rules are presented as the consequence of that, not as two
 * facts to memorise.
 */
export const opampBasics: LessonScript = {
  id: 'opamp-basics',
  title: 'The Op-Amp',
  unitTitle: 'Op-Amps & Signal Conditioning',
  unitId: 'op-amps',
  skillId: 'opamp-basics',
  skillTitle: 'The Op-Amp',
  accent: '#ff6f5e',
  segments: [
    { text: 'An op-amp has a gain of about one hundred thousand, and that is exactly why it is useful.',
      scene: { kind: 'title' } },
    { text: 'Not because you want a gain of a hundred thousand. Because you are going to throw almost all of it away.',
      scene: { kind: 'statement', lines: ['You will throw', 'most of it away'] } },
    { text: 'The symbol is a triangle. Two inputs on the left, one output on the right.',
      scene: { kind: 'circuit', variant: 'opamp', flow: false, highlight: 'openloop', label: 'Two in, one out' } },
    { text: 'The one marked minus is the inverting input. The one marked plus is the non inverting input.',
      scene: { kind: 'circuit', variant: 'opamp', flow: false, highlight: 'openloop minus', label: 'Inverting, and non inverting' } },
    { text: 'Those signs are not the power supply. The power pins are separate and usually left off the drawing.',
      scene: { kind: 'statement', lines: ['Not the power.', 'The signals.'] } },
    { text: 'What it amplifies is the difference between those two inputs, and nothing else.',
      scene: { kind: 'formula', expr: 'Vout = A x (V+ - V−)' } },
    { text: 'Now put a real number in. Suppose the plus input is ten millivolts above the minus input.',
      scene: { kind: 'statement', lines: ['Ten millivolts', 'of difference'] } },
    { text: 'Ten millivolts times one hundred thousand is one thousand volts.',
      scene: { kind: 'formula', expr: '0.01V x 100000 = 1000V' } },
    { text: 'Which it obviously cannot produce. So the output slams to whatever supply rail it has, and stops there.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'clip', label: 'It just hits the rail' } },
    { text: 'Raw, an op-amp is nearly an on off device. It is far too sensitive to use as an amplifier.',
      scene: { kind: 'statement', lines: ['Too sensitive', 'to be useful'] } },
    { text: 'And then you add one wire, and it becomes the most useful analog part there is.',
      scene: { kind: 'circuit', variant: 'opamp', flow: true, highlight: 'feedback', label: 'One wire changes everything' } },
    { text: 'Route some of the output back to the inverting input. That is negative feedback.',
      scene: { kind: 'circuit', variant: 'opamp', flow: true, highlight: 'feedback minus', label: 'Output, back to the minus input' } },
    { text: 'Watch what that does. If the output rises too far, the fed back signal raises the minus input.',
      scene: { kind: 'statement', lines: ['Output rises,', 'minus input rises'] } },
    { text: 'And raising the inverting input pushes the output back down. It corrects itself, continuously.',
      scene: { kind: 'statement', lines: ['So the output', 'comes back down'] } },
    { text: 'It settles wherever the two inputs are almost exactly equal, because that is the only stable place.',
      scene: { kind: 'statement', lines: ['It settles where', 'the inputs match'] } },
    { text: 'And that gives you the two golden rules that let you solve nearly any op-amp circuit in your head.',
      scene: { kind: 'statement', lines: ['Two golden rules'] } },
    { text: 'Rule one. The output does whatever it takes to make the two inputs equal.',
      scene: { kind: 'formula', expr: 'V+ = V−' } },
    { text: 'Rule two. The inputs draw no current at all. Their impedance is effectively infinite.',
      scene: { kind: 'formula', expr: 'Iin = 0' } },
    { text: 'Be careful with rule one, because it describes a result, not a mechanism.',
      scene: { kind: 'statement', lines: ['A result,', 'not a mechanism'] } },
    { text: 'The op-amp cannot touch its own inputs. All it can do is move the output.',
      scene: { kind: 'compare', left: 'It moves the output', right: 'It moves the inputs', caption: 'Only one of these is true' } },
    { text: 'The feedback network is what carries that movement back and brings the inputs together.',
      scene: { kind: 'statement', lines: ['The feedback does', 'the equalising'] } },
    { text: 'Which is why both rules only hold when there is negative feedback present.',
      scene: { kind: 'statement', lines: ['No feedback,', 'no rules'] } },
    { text: 'And here is the payoff, and the reason the enormous gain matters.',
      scene: { kind: 'statement', lines: ['Here is the', 'payoff'] } },
    { text: 'The circuit gain no longer depends on the op-amp at all. It depends on your two resistors.',
      scene: { kind: 'compare', left: 'Set by resistors', right: 'Set by the chip', caption: 'One of these you can trust' } },
    { text: 'A resistor is accurate to one percent. An op-amp’s raw gain varies by a factor of ten between samples.',
      scene: { kind: 'statement', lines: ['Trust resistors,', 'not silicon'] } },
    { text: 'You spent a gain of a hundred thousand to buy a gain of ten that never drifts. That is the trade.',
      scene: { kind: 'statement', lines: ['Huge gain, spent', 'on precision'] } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. An op-amp amplifies the difference between its inputs, enormously, so raw it just hits a rail.',
      scene: { kind: 'recap', items: ['It amplifies the difference, hugely'] } },
    { text: 'Two. Negative feedback to the minus input makes it self correcting and predictable.',
      scene: { kind: 'recap', items: ['It amplifies the difference, hugely', 'Feedback to minus tames it'] } },
    { text: 'Three. Inputs end up equal and draw no current, and your resistors set the gain.',
      scene: { kind: 'recap', items: ['It amplifies the difference, hugely', 'Feedback to minus tames it', 'Equal inputs, no input current'] } },
    { text: 'Go and look at a 741 or an LM358 datasheet, and find the open loop gain figure.',
      scene: { kind: 'outro' } },
  ],
};
