import type { LessonScript } from '../types';

/**
 * Unit 8, Op-Amps & Signal Conditioning. Checkpoint for "The Amplifier Circuits".
 *
 * Three configurations, derived from the golden rules rather than presented as
 * formulas to remember. The follower gets the last third because a gain of one
 * looks pointless until you have watched a sensor divider sag under load.
 */
export const opampAmplifiers: LessonScript = {
  id: 'opamp-amplifiers',
  title: 'The Amplifier Circuits',
  unitTitle: 'Op-Amps & Signal Conditioning',
  unitId: 'op-amps',
  skillId: 'opamp-amplifiers',
  skillTitle: 'The Amplifier Circuits',
  accent: '#ff6f5e',
  segments: [
    { text: 'Three op-amp circuits do most of the work in the world, and all three come from the golden rules.',
      scene: { kind: 'title' } },
    { text: 'Start with the inverting amplifier, because the golden rules show their whole trick in it.',
      scene: { kind: 'circuit', variant: 'opamp', flow: true, highlight: 'rin', label: 'The inverting amplifier' } },
    { text: 'The plus input goes to ground. The signal comes in through a resistor to the minus input.',
      scene: { kind: 'circuit', variant: 'opamp', flow: true, highlight: 'minus', label: 'Signal in, through Rin' } },
    { text: 'And a feedback resistor runs from the output back to that same minus input.',
      scene: { kind: 'circuit', variant: 'opamp', flow: true, highlight: 'feedback', label: 'Rf, output back to minus' } },
    { text: 'Now apply rule one. The plus input is at nought volts, so the minus input must also be at nought.',
      scene: { kind: 'statement', lines: ['Plus is at zero,', 'so minus is too'] } },
    { text: 'It is not wired to ground. It just behaves exactly as though it were. That is called a virtual ground.',
      scene: { kind: 'statement', lines: ['A virtual', 'ground'] } },
    { text: 'So one volt in, through a ten kilohm input resistor, pushes one tenth of a milliamp toward that node.',
      scene: { kind: 'formula', expr: '1V / 10kΩ = 0.1mA' } },
    { text: 'Rule two says none of it goes into the pin, so all of it goes through the feedback resistor.',
      scene: { kind: 'statement', lines: ['None into the pin.', 'All through Rf.'] } },
    { text: 'And that gives you the gain, as a plain ratio of the two resistors, with a minus sign.',
      scene: { kind: 'formula', expr: 'Av = − Rf / Rin' } },
    { text: 'A hundred kilohms of feedback over ten kilohms in is a gain of minus ten.',
      scene: { kind: 'formula', expr: '−100k / 10k = −10' } },
    { text: 'Minus means the output is upside down. Push the input up and the output goes down.',
      scene: { kind: 'compare', left: 'Input rises', right: 'Output falls', caption: 'That is what inverting means' } },
    { text: 'Now flip it round. The non inverting amplifier puts the signal on the plus input instead.',
      scene: { kind: 'circuit', variant: 'opamp', flow: true, highlight: 'plus', label: 'The non inverting amplifier' } },
    { text: 'The feedback network is still there, but now it goes from the output to minus, and on to ground.',
      scene: { kind: 'circuit', variant: 'opamp', flow: true, highlight: 'feedback', label: 'A divider, on the feedback' } },
    { text: 'Its gain is one plus the ratio of the two resistors, and it is not inverted.',
      scene: { kind: 'formula', expr: 'Av = 1 + Rf / Rg' } },
    { text: 'Ninety kilohms over ten kilohms gives one plus nine, so a gain of ten, right way up.',
      scene: { kind: 'formula', expr: '1 + 90k / 10k = 10' } },
    { text: 'Notice the one. This circuit can never have a gain below one, however you choose the resistors.',
      scene: { kind: 'compare', left: 'Non inverting: 1 upward', right: 'Inverting: any ratio', caption: 'Only one of them can attenuate' } },
    { text: 'Which brings us to the third circuit, and the one that looks pointless.',
      scene: { kind: 'statement', lines: ['The one that', 'looks pointless'] } },
    { text: 'Wire the output straight back to the minus input, with no resistors at all.',
      scene: { kind: 'circuit', variant: 'opamp', flow: true, highlight: 'out', label: 'Output straight back' } },
    { text: 'That is a non inverting amplifier with a feedback resistor of nought, so the gain is exactly one.',
      scene: { kind: 'formula', expr: 'Av = 1 + 0 = 1' } },
    { text: 'The output simply copies the input. As an amplifier it does nothing whatsoever.',
      scene: { kind: 'statement', lines: ['It copies', 'the input'] } },
    { text: 'And it is one of the most used circuits there is, because of what it does to impedance.',
      scene: { kind: 'statement', lines: ['It is about', 'impedance'] } },
    { text: 'Think back to your sensor divider. Two resistors, and a midpoint you want to read.',
      scene: { kind: 'circuit', variant: 'divider', flow: true, highlight: 'tap', label: 'A high impedance source' } },
    { text: 'Connect anything that draws real current to that midpoint and the midpoint sags.',
      scene: { kind: 'statement', lines: ['Load it,', 'and it sags'] } },
    { text: 'Because the divider can only supply current through its own resistors, and they are large.',
      scene: { kind: 'statement', lines: ['A weak source,', 'through big resistors'] } },
    { text: 'Put a follower in between. It takes almost nothing from the divider, and supplies real current out.',
      scene: { kind: 'compare', left: 'Takes nothing in', right: 'Gives current out', caption: 'The point of a gain of one' } },
    { text: 'That is called buffering, and it is why a gain of one earns its own chip.',
      scene: { kind: 'statement', lines: ['A gain of one,', 'and a real job'] } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. Inverting gain is minus the feedback resistor over the input resistor, around a virtual ground.',
      scene: { kind: 'recap', items: ['Inverting: −Rf over Rin'] } },
    { text: 'Two. Non inverting gain is one plus the ratio, in phase, and never below one.',
      scene: { kind: 'recap', items: ['Inverting: −Rf over Rin', 'Non inverting: 1 + Rf over Rg'] } },
    { text: 'Three. A follower has a gain of one, and it stops a weak source being loaded down.',
      scene: { kind: 'recap', items: ['Inverting: −Rf over Rin', 'Non inverting: 1 + Rf over Rg', 'A follower buffers, it does not amplify'] } },
    { text: 'Go and load a ten kilohm divider with something hungry, and watch the midpoint move.',
      scene: { kind: 'outro' } },
  ],
};
