import type { LessonScript } from '../types';

/**
 * Unit 8, Op-Amps & Signal Conditioning. Checkpoint for "Comparing & Switching".
 *
 * The film that closes a loop opened in unit three: the learner already fixed a
 * flickering light alarm with two thresholds in code. Here the same fix appears
 * in hardware, and gets its name.
 */
export const opampComparators: LessonScript = {
  id: 'opamp-comparators',
  title: 'Comparing and Switching',
  unitTitle: 'Op-Amps & Signal Conditioning',
  unitId: 'op-amps',
  skillId: 'opamp-comparators',
  skillTitle: 'Comparing & Switching',
  accent: '#ff6f5e',
  segments: [
    { text: 'The last film spent an enormous gain to buy precision. Now we spend it on a decision instead.',
      scene: { kind: 'title' } },
    { text: 'Take the feedback away and the op-amp goes back to slamming at the smallest difference.',
      scene: { kind: 'circuit', variant: 'opamp', flow: true, highlight: 'openloop', label: 'No feedback, on purpose' } },
    { text: 'Which was useless for amplifying. It is exactly what you want for comparing.',
      scene: { kind: 'compare', left: 'Useless for gain', right: 'Perfect for deciding', caption: 'The same behaviour, a different job' } },
    { text: 'Put a fixed reference on one input and your signal on the other.',
      scene: { kind: 'circuit', variant: 'opamp', flow: true, highlight: 'openloop plus', label: 'A reference, and a signal' } },
    { text: 'Signal above the reference and the output goes to the top rail. Below it, to the bottom.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'square', label: 'One bit of output' } },
    { text: 'That is a comparator, and it has just turned an analog level into a clean digital decision.',
      scene: { kind: 'statement', lines: ['Analog in,', 'one bit out'] } },
    { text: 'Which is your light alarm’s decide stage, in hardware, with no microcontroller anywhere.',
      scene: { kind: 'circuit', variant: 'divider', flow: true, highlight: 'ldr tap', label: 'The sensor still senses' } },
    { text: 'LDR divider into one input. A reference from a potentiometer into the other. That is the whole alarm.',
      scene: { kind: 'circuit', variant: 'divider', flow: true, highlight: 'pot', label: 'And a pot sets the threshold' } },
    { text: 'You can use an op-amp for this, and it works. But dedicated comparator chips exist for a reason.',
      scene: { kind: 'statement', lines: ['Dedicated chips', 'exist'] } },
    { text: 'They switch far faster, because an op-amp is designed to be stable, not quick.',
      scene: { kind: 'compare', left: 'Op-amp: microseconds', right: 'Comparator: nanoseconds', caption: 'Built for different jobs' } },
    { text: 'And many of them have an open collector output, which catches people out.',
      scene: { kind: 'statement', lines: ['Open collector', 'output'] } },
    { text: 'That kind of output can pull down to ground, but it cannot push up to anything.',
      scene: { kind: 'statement', lines: ['It pulls down.', 'It cannot push up.'] } },
    { text: 'So it needs a pull up resistor, exactly like the one on your button, or it never reads high.',
      scene: { kind: 'circuit', variant: 'pullup', flow: false, highlight: 'resistor', label: 'It needs a pull up' } },
    { text: 'An output stuck low forever, on a comparator, is nearly always a missing pull up.',
      scene: { kind: 'statement', lines: ['Stuck low means', 'missing pull up'] } },
    { text: 'Now the problem every comparator has, and it is one you have already met.',
      scene: { kind: 'statement', lines: ['Now the problem'] } },
    { text: 'A real signal is never perfectly clean. There is always a little noise on it.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'noise', label: 'A real signal, close up' } },
    { text: 'When it sits right at the threshold, that noise crosses the line over and over.',
      scene: { kind: 'statement', lines: ['At the line,', 'it crosses often'] } },
    { text: 'So the output chatters, dozens of times a second, and your alarm flickers at dusk.',
      scene: { kind: 'statement', lines: ['So the output', 'chatters'] } },
    { text: 'The fix is the same one you used in code, and in hardware it has a proper name.',
      scene: { kind: 'statement', lines: ['The same fix,', 'in hardware'] } },
    { text: 'Two thresholds instead of one. The level that switches it on is higher than the level that switches it off.',
      scene: { kind: 'formula', expr: 'on at 3.0V, off at 2.0V' } },
    { text: 'Between them is a dead band, and inside that band nothing at all happens.',
      scene: { kind: 'compare', left: 'One threshold', right: 'A dead band', caption: 'Noise fits inside a band' } },
    { text: 'That is hysteresis, and a comparator with it is called a Schmitt trigger.',
      scene: { kind: 'statement', lines: ['Hysteresis.', 'A Schmitt trigger.'] } },
    { text: 'You build it with a resistor from the output back to the plus input.',
      scene: { kind: 'circuit', variant: 'opamp', flow: true, highlight: 'openloop plus', label: 'Feedback, but to the plus input' } },
    { text: 'Notice that is positive feedback, going to the non inverting input rather than the inverting one.',
      scene: { kind: 'compare', left: 'To minus: stabilises', right: 'To plus: latches', caption: 'The same wire, the opposite effect' } },
    { text: 'It reinforces whatever the output just did, which is exactly what moves the threshold out of the way.',
      scene: { kind: 'statement', lines: ['It reinforces', 'the decision'] } },
    { text: 'Once it has flipped, the signal has to make a real move back before it flips again.',
      scene: { kind: 'statement', lines: ['A real move,', 'or nothing'] } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. A comparator is an op-amp with no feedback, turning an analog level into one bit.',
      scene: { kind: 'recap', items: ['Open loop turns a level into a bit'] } },
    { text: 'Two. Many comparators have open collector outputs and need a pull up resistor.',
      scene: { kind: 'recap', items: ['Open loop turns a level into a bit', 'Open collector needs a pull up'] } },
    { text: 'Three. Positive feedback to the plus input gives two thresholds, and kills the chatter.',
      scene: { kind: 'recap', items: ['Open loop turns a level into a bit', 'Open collector needs a pull up', 'Hysteresis makes a Schmitt trigger'] } },
    { text: 'Go and watch a comparator chatter without hysteresis. It is worth seeing once.',
      scene: { kind: 'outro' } },
  ],
};
