import type { LessonScript } from '../types';

/**
 * Unit 8, Op-Amps & Signal Conditioning. Checkpoint for "Real Op-Amps & Conditioning".
 *
 * Where the ideal model is taken back, carefully. Single supply operation gets
 * the most time because it is the situation a learner is actually in: a five
 * volt rail, a ground, and no negative supply anywhere on the bench.
 */
export const opampRealWorld: LessonScript = {
  id: 'opamp-real-world',
  title: 'Real Op-Amps',
  unitTitle: 'Op-Amps & Signal Conditioning',
  unitId: 'op-amps',
  skillId: 'opamp-real-world',
  skillTitle: 'Real Op-Amps & Conditioning',
  accent: '#ff6f5e',
  segments: [
    { text: 'The golden rules describe an ideal op-amp. Here is where a real one stops obeying them.',
      scene: { kind: 'title' } },
    { text: 'First, the inputs are not perfectly matched inside the chip.',
      scene: { kind: 'circuit', variant: 'opamp', flow: false, highlight: 'minus', label: 'Not quite identical' } },
    { text: 'So even with both inputs at exactly the same voltage, the output is not exactly nought.',
      scene: { kind: 'statement', lines: ['Equal inputs,', 'unequal output'] } },
    { text: 'That mismatch is called input offset voltage, and a cheap part might have a few millivolts of it.',
      scene: { kind: 'formula', expr: 'offset ≈ 1 to 5mV' } },
    { text: 'Amplify that by a hundred and you have half a volt of error before your signal even arrives.',
      scene: { kind: 'formula', expr: '5mV x 100 = 0.5V of error' } },
    { text: 'And it drifts with temperature, which is why a precision measurement wanders as the room warms.',
      scene: { kind: 'statement', lines: ['It drifts as', 'the room warms'] } },
    { text: 'Second, rule two is not quite true either. The inputs draw a tiny bias current.',
      scene: { kind: 'statement', lines: ['A tiny current,', 'not none'] } },
    { text: 'Nanoamps, usually. Irrelevant with ten kilohm resistors, and a real problem with ten megohm ones.',
      scene: { kind: 'compare', left: '10kΩ: ignore it', right: '10MΩ: it dominates', caption: 'The same current, two verdicts' } },
    { text: 'Third, the output cannot move infinitely fast. Its maximum rate is called the slew rate.',
      scene: { kind: 'formula', expr: 'slew rate, in V per µs' } },
    { text: 'One volt per microsecond means a five volt step takes five microseconds, and no less.',
      scene: { kind: 'formula', expr: '5V / (1V/µs) = 5µs' } },
    { text: 'Ask for something faster and your clean square wave comes out as a ramp.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'clip', label: 'Asked for a square, given a ramp' } },
    { text: 'Fourth, gain and bandwidth trade against each other. Their product is roughly fixed.',
      scene: { kind: 'formula', expr: 'gain x bandwidth ≈ constant' } },
    { text: 'A one megahertz part at a gain of ten works to a hundred kilohertz. At a gain of a hundred, only ten.',
      scene: { kind: 'circuit', variant: 'bode', highlight: 'lowpass', label: 'More gain, less bandwidth' } },
    { text: 'And fifth, the output cannot quite reach the supply rails. Most parts stop a volt or so short.',
      scene: { kind: 'statement', lines: ['It stops short', 'of the rails'] } },
    { text: 'Which matters enormously in the situation you are actually in.',
      scene: { kind: 'statement', lines: ['And here is', 'your situation'] } },
    { text: 'Op-amps were designed for a split supply, plus fifteen and minus fifteen volts, around ground.',
      scene: { kind: 'compare', left: 'Classic: ±15V', right: 'Yours: 5V and 0V', caption: 'You have no negative rail' } },
    { text: 'Your bench has five volts and ground. There is no negative rail anywhere.',
      scene: { kind: 'statement', lines: ['No negative', 'supply'] } },
    { text: 'So the output can only swing between nought and five volts. It cannot go below ground.',
      scene: { kind: 'statement', lines: ['It cannot go', 'below ground'] } },
    { text: 'Feed it an audio signal centred on nought volts and the entire bottom half is cut off.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'halfwave', label: 'Half the signal, gone' } },
    { text: 'The fix is to stop referencing the signal to ground and reference it to the middle instead.',
      scene: { kind: 'statement', lines: ['Reference it to', 'the middle'] } },
    { text: 'Make two point five volts with a divider, and treat that as your new zero.',
      scene: { kind: 'circuit', variant: 'divider', flow: true, highlight: 'tap', label: 'A mid rail, at 2.5V' } },
    { text: 'Now the signal swings above and below two point five, and all of it fits inside nought to five.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'sine', label: 'All of it fits now' } },
    { text: 'But do not use that divider directly. Anything you connect to it drags it off centre.',
      scene: { kind: 'statement', lines: ['Do not use it', 'directly'] } },
    { text: 'Buffer it with a follower, and you have a stiff two point five volt reference that will not move.',
      scene: { kind: 'circuit', variant: 'opamp', flow: true, highlight: 'out', label: 'Buffer it first' } },
    { text: 'And the last job is to fill the converter’s range, because an unused range is wasted resolution.',
      scene: { kind: 'statement', lines: ['Fill the range'] } },
    { text: 'A sensor giving nought to half a volt into a five volt converter uses a tenth of it. Amplify by ten.',
      scene: { kind: 'formula', expr: '5V / 0.5V = gain of 10' } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. Real parts have offset, bias current, a slew rate, and they cannot reach the rails.',
      scene: { kind: 'recap', items: ['The ideal model has real limits'] } },
    { text: 'Two. On a single supply, bias the signal to half the rail and buffer that reference.',
      scene: { kind: 'recap', items: ['The ideal model has real limits', 'Single supply means bias to mid rail'] } },
    { text: 'Three. Buffer a weak source, then amplify to fill the converter’s range.',
      scene: { kind: 'recap', items: ['The ideal model has real limits', 'Single supply means bias to mid rail', 'Buffer, then amplify to fill the range'] } },
    { text: 'Go and find the slew rate and the offset voltage on an LM358 datasheet.',
      scene: { kind: 'outro' } },
  ],
};
