import type { LessonScript } from '../types';

/**
 * Unit 3, Sensors & Signals. Checkpoint for "Reading Sensors".
 *
 * The bridge between a resistance and a number. A learner can recite the
 * divider formula and still not see why the sensor has to be in a divider at
 * all, so the film leads with the constraint: a pin measures voltage and
 * nothing else.
 */
export const readingSensors: LessonScript = {
  id: 'reading-sensors',
  title: 'Reading a Sensor',
  unitTitle: 'Sensors & Signals',
  unitId: 'sensors',
  skillId: 'reading-sensors',
  skillTitle: 'Reading Sensors',
  accent: '#84cc30',
  segments: [
    { text: 'Your sensor changes its resistance. Your microcontroller cannot measure resistance at all.',
      scene: { kind: 'title' } },
    { text: 'A pin measures one thing. Voltage, against ground.',
      scene: { kind: 'statement', lines: ['A pin measures', 'voltage'] } },
    { text: 'So the whole job is turning a changing resistance into a changing voltage.',
      scene: { kind: 'statement', lines: ['Resistance in,', 'voltage out'] } },
    { text: 'And the circuit that does it is two resistors in series. A voltage divider.',
      scene: { kind: 'circuit', variant: 'divider', flow: true, label: 'Two resistors, one tap' } },
    { text: 'The supply is split between them, and you read the point in the middle.',
      scene: { kind: 'circuit', variant: 'divider', flow: true, highlight: 'tap', label: 'Read the middle' } },
    { text: 'The formula is the output equals the input times the bottom resistor over the sum of both.',
      scene: { kind: 'formula', expr: 'Vout = Vin x R2 / (R1 + R2)' } },
    { text: 'Two equal resistors on five volts put two point five in the middle. Half each, as you would expect.',
      scene: { kind: 'formula', expr: 'equal → 2.5V' } },
    { text: 'A one kilohm on top and a two kilohm below gives three point three volts, because the bottom takes more.',
      scene: { kind: 'formula', expr: '5V x 2k / 3k = 3.33V' } },
    { text: 'That is the rule to hold on to. Whichever resistor is larger keeps the larger share.',
      scene: { kind: 'statement', lines: ['The bigger one', 'keeps more'] } },
    { text: 'Now swap the top resistor for something the world can change.',
      scene: { kind: 'circuit', variant: 'divider', flow: true, highlight: 'ldr', label: 'An LDR on top' } },
    { text: 'An LDR on top, a ten kilohm resistor below, five volts across the pair.',
      scene: { kind: 'circuit', variant: 'divider', flow: true, highlight: 'ldr r2', label: 'LDR and 10k' } },
    { text: 'In bright light the LDR drops to about one kilohm, so the ten kilohm below keeps most of the voltage.',
      scene: { kind: 'formula', expr: 'bright: 5V x 10k / 11k = 4.5V' } },
    { text: 'Cover it and the LDR shoots to two hundred kilohms, so it takes almost everything.',
      scene: { kind: 'formula', expr: 'dark: 5V x 10k / 210k = 0.24V' } },
    { text: 'Bright reads high, dark reads low. Four and a half volts down to a quarter of a volt.',
      scene: { kind: 'compare', left: 'Bright 4.5V', right: 'Dark 0.24V', caption: 'From one hand over the sensor' } },
    { text: 'Swap the two around, sensor below and fixed resistor on top, and the whole thing reads backwards.',
      scene: { kind: 'statement', lines: ['Swap them,', 'invert the reading'] } },
    { text: 'Neither way is wrong. Just know which one you built, because your code depends on it.',
      scene: { kind: 'statement', lines: ['Know which way', 'round you built it'] } },
    { text: 'Choosing the fixed resistor matters too. Pick it near the middle of your sensor’s range.',
      scene: { kind: 'statement', lines: ['Match the fixed', 'resistor to the range'] } },
    { text: 'Ten kilohms suits an LDR because the interesting readings sit either side of it.',
      scene: { kind: 'statement', lines: ['10k, because that', 'is where the action is'] } },
    { text: 'Now the number your code sees. The pin does not report volts.',
      scene: { kind: 'circuit', variant: 'board', flow: true, highlight: 'analog', label: 'The analog inputs' } },
    { text: 'An analog to digital converter measures the voltage and hands your program a whole number.',
      scene: { kind: 'statement', lines: ['A voltage in,', 'a number out'] } },
    { text: 'An Arduino Uno has a ten bit converter, so nought to five volts becomes nought to one thousand and twenty three.',
      scene: { kind: 'formula', expr: '0 to 5V → 0 to 1023' } },
    { text: 'Two point five volts reads about five hundred and twelve. Three quarters of the range reads about seven six eight.',
      scene: { kind: 'formula', expr: '2.5V → 512' } },
    { text: 'That is roughly five millivolts per step, which is far finer than any of these sensors deserve.',
      scene: { kind: 'statement', lines: ['About 5mV', 'per step'] } },
    { text: 'Last thing, and it will save you an hour. Sanity check the reading before you trust it.',
      scene: { kind: 'statement', lines: ['Check it before', 'you trust it'] } },
    { text: 'A value stuck at one thousand and twenty three usually means the pin is wired straight to five volts.',
      scene: { kind: 'compare', left: 'Stuck at 1023', right: 'Stuck at 0', caption: 'Shorted to the rail, or to nothing' } },
    { text: 'A value stuck at nought means it is grounded or floating. A healthy sensor moves when you touch it.',
      scene: { kind: 'statement', lines: ['A live sensor', 'moves'] } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. A pin reads voltage, so a divider is how a resistance becomes readable.',
      scene: { kind: 'recap', items: ['A divider turns R into V'] } },
    { text: 'Two. The output is the input times the bottom resistor over the sum, and the bigger resistor keeps more.',
      scene: { kind: 'recap', items: ['A divider turns R into V', 'The bigger resistor keeps more'] } },
    { text: 'Three. Ten bits means nought to one thousand and twenty three, and a stuck value is a wiring fault.',
      scene: { kind: 'recap', items: ['A divider turns R into V', 'The bigger resistor keeps more', '0 to 1023, and stuck means faulty'] } },
    { text: 'Go and print your own sensor’s reading, bright and covered, and write both numbers down.',
      scene: { kind: 'outro' } },
  ],
};
