import type { LessonScript } from '../types';

/**
 * Unit 5, Inputs, Outputs & Code. Checkpoint for "Reading Inputs".
 *
 * A floating pin is invisible on a schematic and unmistakable on a scope, which
 * makes it exactly the thing a film should carry. The internal pull-up gets
 * proper time here because it is what a learner will actually use and it
 * inverts the logic under them.
 */
export const readingInputs: LessonScript = {
  id: 'reading-inputs',
  title: 'Reading Inputs',
  unitTitle: 'Inputs, Outputs & Code',
  unitId: 'inputs-outputs',
  skillId: 'reading-inputs',
  skillTitle: 'Reading Inputs',
  accent: '#ff6f5e',
  segments: [
    { text: 'A button is the simplest input there is, and it is the one that goes wrong most often.',
      scene: { kind: 'title' } },
    { text: 'In code it takes two lines. Set the pin as an input, then read it.',
      scene: { kind: 'formula', expr: 'digitalRead(BUTTON);' } },
    { text: 'Digital read gives you high or low. Nothing in between, because a button has nothing in between.',
      scene: { kind: 'statement', lines: ['HIGH', 'or LOW'] } },
    { text: 'A button is not a source of anything. It is two pieces of metal that either touch or do not.',
      scene: { kind: 'circuit', variant: 'pullup', flow: false, highlight: 'button', label: 'Metal that touches, or does not' } },
    { text: 'And that is the whole problem, because when they are not touching, what is the pin connected to?',
      scene: { kind: 'statement', lines: ['Not touching.', 'So, connected to what?'] } },
    { text: 'Nothing. And a pin connected to nothing is called floating.',
      scene: { kind: 'circuit', variant: 'pullup', flow: false, broken: 'right', highlight: 'float', label: 'Connected to nothing' } },
    { text: 'A floating pin does not read low. It reads whatever the last stray charge left on it.',
      scene: { kind: 'statement', lines: ['Not low.', 'Just undefined.'] } },
    { text: 'Wave your hand near it and it changes. Mains hum, your body, a nearby wire, all of it moves the reading.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'noise', label: 'A floating pin, actually measured' } },
    { text: 'So your code sees random presses that you never made, and the board looks possessed.',
      scene: { kind: 'statement', lines: ['Presses you', 'never made'] } },
    { text: 'The fix is one resistor, and it is called a pull resistor.',
      scene: { kind: 'circuit', variant: 'pullup', flow: false, highlight: 'resistor', label: 'One resistor fixes it' } },
    { text: 'A pull up ties the pin gently to five volts, so when nothing else is happening it reads high.',
      scene: { kind: 'circuit', variant: 'pullup', flow: false, highlight: 'resistor pin', label: 'Pull up: rests HIGH' } },
    { text: 'Press the button and it connects the pin hard to ground, so it reads low.',
      scene: { kind: 'circuit', variant: 'pullup', flow: true, highlight: 'button', label: 'Pressed: pulled LOW' } },
    { text: 'Notice that this inverts your logic. Not pressed is high, pressed is low.',
      scene: { kind: 'compare', left: 'Released: HIGH', right: 'Pressed: LOW', caption: 'Backwards, and correct' } },
    { text: 'A pull down does the mirror image. It ties the pin to ground, so resting is low and pressed is high.',
      scene: { kind: 'statement', lines: ['Pull down is', 'the mirror'] } },
    { text: 'Ten kilohms is the usual value for either. Big enough to waste no current, small enough to beat the noise.',
      scene: { kind: 'formula', expr: '5V / 10kΩ = 0.5mA' } },
    { text: 'Half a milliamp while the button is held, and nothing at all while it is not.',
      scene: { kind: 'statement', lines: ['Half a milliamp,', 'only when pressed'] } },
    { text: 'And the chip has these built in, so you often need no resistor on the board at all.',
      scene: { kind: 'formula', expr: 'pinMode(BTN, INPUT_PULLUP);' } },
    { text: 'That one word turns on an internal pull up of about twenty to fifty kilohms.',
      scene: { kind: 'statement', lines: ['Internal.', 'Free.'] } },
    { text: 'Wire your button between the pin and ground, use input pull up, and remember the logic is inverted.',
      scene: { kind: 'statement', lines: ['Pin to button,', 'button to ground'] } },
    { text: 'There is no internal pull down on an Arduino Uno, so a pull down needs a real resistor.',
      scene: { kind: 'compare', left: 'Pull up: built in', right: 'Pull down: fit one', caption: 'Only one of them is free' } },
    { text: 'One more thing, and it is mechanical rather than electrical.',
      scene: { kind: 'statement', lines: ['One more thing'] } },
    { text: 'The contacts inside a button are springs, and when they meet they bounce apart and back.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'bounce', label: 'One press, close up' } },
    { text: 'For a few milliseconds the pin flips several times. Your finger felt one press.',
      scene: { kind: 'compare', left: 'You: one press', right: 'The pin: five', caption: 'Both readings are honest' } },
    { text: 'If your code just reads the level, this never matters, because it has settled long before you let go.',
      scene: { kind: 'statement', lines: ['Reading a level?', 'It does not matter.'] } },
    { text: 'If your code counts changes, or toggles something, it matters enormously.',
      scene: { kind: 'statement', lines: ['Counting changes?', 'It matters a lot.'] } },
    { text: 'The simplest fix is to wait about twenty milliseconds after a change before reading again.',
      scene: { kind: 'formula', expr: 'delay(20);' } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. An unconnected input floats and reads noise, so every button needs a pull resistor.',
      scene: { kind: 'recap', items: ['A floating input reads noise'] } },
    { text: 'Two. Input pull up gives you one for free, and it makes pressed read low.',
      scene: { kind: 'recap', items: ['A floating input reads noise', 'INPUT_PULLUP is free, and inverted'] } },
    { text: 'Three. Contacts bounce for a few milliseconds, so anything counting presses must debounce.',
      scene: { kind: 'recap', items: ['A floating input reads noise', 'INPUT_PULLUP is free, and inverted', 'Debounce anything that counts'] } },
    { text: 'Go and print a floating pin for ten seconds. Then add the resistor and print it again.',
      scene: { kind: 'outro' } },
  ],
};
