import type { LessonScript } from '../types';

/**
 * Unit 1, Foundations. Checkpoint for "Resistance & Ohm's Law".
 *
 * The skill teaches three separate things, the equation, the colour code and
 * the power rating, and a learner who has answered questions on all three
 * usually still holds them as three unrelated facts. The film's job is to put
 * them in one line: choose a current, that picks a resistor, that decides how
 * hot it runs.
 */
export const resistanceOhms: LessonScript = {
  id: 'resistance-ohms',
  title: 'Ohm’s Law',
  unitTitle: 'Foundations',
  unitId: 'foundations',
  skillId: 'resistance-ohms',
  skillTitle: 'Resistance & Ohm’s Law',
  accent: '#f2b705',
  segments: [
    { text: 'Three quantities describe every circuit you will ever build, and one equation ties them together.',
      scene: { kind: 'title' } },
    { text: 'Voltage pushes. Current flows. Resistance pushes back.',
      scene: { kind: 'statement', lines: ['Push.', 'Flow.', 'Push back.'] } },
    { text: 'Resistance is how hard a component fights the current going through it, measured in ohms.',
      scene: { kind: 'circuit', variant: 'led', flow: true, highlight: 'resistor', label: 'Resistance, in ohms' } },
    { text: 'A resistor is a part built to have one known value, unlike a random length of wire that also resists a little.',
      scene: { kind: 'statement', lines: ['A known value,', 'on purpose'] } },
    { text: 'Here is the equation. Voltage equals current times resistance.',
      scene: { kind: 'formula', expr: 'V = I x R' } },
    { text: 'Rearranged, current equals voltage divided by resistance. That is the form you will actually use.',
      scene: { kind: 'formula', expr: 'I = V / R' } },
    { text: 'Five volts across a one kilohm resistor. Five divided by a thousand is five milliamps.',
      scene: { kind: 'formula', expr: '5V / 1kΩ = 5mA' } },
    { text: 'Halve the resistance and the current doubles. Five volts across five hundred ohms gives ten.',
      scene: { kind: 'formula', expr: '5V / 500Ω = 10mA' } },
    { text: 'Which tells you something useful. Resistance is your dial for current.',
      scene: { kind: 'statement', lines: ['Resistance is', 'your dial'] } },
    { text: 'You almost never set a current directly. You choose a resistor, and the current follows from it.',
      scene: { kind: 'compare', left: 'Choose R', right: 'Get I', caption: 'You only ever pick one of them' } },
    { text: 'So the third form matters too. Resistance equals voltage divided by current.',
      scene: { kind: 'formula', expr: 'R = V / I' } },
    { text: 'Decide the current you want, work out the voltage the resistor has to drop, then divide.',
      scene: { kind: 'statement', lines: ['Current first.', 'Resistor second.'] } },
    { text: 'Now, reading one. A resistor is too small to print a number on, so the value is in coloured bands.',
      scene: { kind: 'circuit', variant: 'led', flow: false, highlight: 'resistor', label: 'Four bands, not a number' } },
    { text: 'The first two bands are digits. The third says how many zeros to add. The fourth is the tolerance.',
      scene: { kind: 'statement', lines: ['Digit, digit,', 'zeros, tolerance'] } },
    { text: 'Black is nought, brown is one, red is two, orange is three, and it runs on up to white for nine.',
      scene: { kind: 'statement', lines: ['Black 0, brown 1,', 'red 2, orange 3'] } },
    { text: 'So brown, black, red reads one, then nought, then two more zeros. One thousand ohms.',
      scene: { kind: 'formula', expr: 'brown black red = 1kΩ' } },
    { text: 'Red, red, brown is two, two, and one zero. Two hundred and twenty ohms, the one you will reach for most.',
      scene: { kind: 'formula', expr: 'red red brown = 220Ω' } },
    { text: 'A gold fourth band means the real value is within five percent of the marking. Silver means ten.',
      scene: { kind: 'compare', left: 'Gold, 5%', right: 'Silver, 10%', caption: 'How close the marking really is' } },
    { text: 'That tolerance is why nobody sells a two hundred ohm resistor, and everybody sells two hundred and twenty.',
      scene: { kind: 'statement', lines: ['The values exist', 'because of the spread'] } },
    { text: 'One quantity left, and it is the one that sets things on fire.',
      scene: { kind: 'statement', lines: ['One more'] } },
    { text: 'Power is energy per second, measured in watts. Power equals voltage times current.',
      scene: { kind: 'formula', expr: 'P = V x I' } },
    { text: 'A resistor turns every watt it uses into heat. That is not a side effect. That is the job.',
      scene: { kind: 'statement', lines: ['Every watt', 'becomes heat'] } },
    { text: 'Three volts across a resistor at fourteen milliamps is forty two milliwatts.',
      scene: { kind: 'formula', expr: '3V x 14mA = 42mW' } },
    { text: 'The quarter watt resistors in your kit handle two hundred and fifty, so that is nowhere near trouble.',
      scene: { kind: 'compare', left: '42mW used', right: '250mW allowed', caption: 'Comfortable' } },
    { text: 'Now twelve volts at a quarter of an amp. Three watts, into a part rated for a quarter of one.',
      scene: { kind: 'formula', expr: '12V x 0.25A = 3W' } },
    { text: 'It discolours, it smells, and then it stops. Check the wattage whenever the current passes about fifty milliamps.',
      scene: { kind: 'statement', lines: ['Check the watts', 'above 50mA'] } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. V equals I times R, and the form you use most is current equals voltage over resistance.',
      scene: { kind: 'recap', items: ['V = I x R, in all three forms'] } },
    { text: 'Two. The bands are two digits, a multiplier, and a tolerance. Red, red, brown is two hundred and twenty.',
      scene: { kind: 'recap', items: ['V = I x R, in all three forms', 'Two digits, zeros, tolerance'] } },
    { text: 'Three. Power is voltage times current, and it all comes out as heat.',
      scene: { kind: 'recap', items: ['V = I x R, in all three forms', 'Two digits, zeros, tolerance', 'P = V x I, and it is all heat'] } },
    { text: 'Go and measure a resistor you thought you knew the value of.',
      scene: { kind: 'outro' } },
  ],
};
