import type { LessonScript } from '../types';

/**
 * Unit 9, Filters, Oscillators & Signals. Checkpoint for "Resonance & Oscillators".
 *
 * The film that names the thing a learner has already built twice without
 * knowing it: the 555 astable is a relaxation oscillator, and the hysteresis
 * they added to a comparator is the positive feedback that makes one possible.
 */
export const resonanceOscillators: LessonScript = {
  id: 'resonance-oscillators',
  title: 'Resonance and Oscillators',
  unitTitle: 'Filters, Oscillators & Signals',
  unitId: 'filters-oscillators',
  skillId: 'resonance-oscillators',
  skillTitle: 'Resonance & Oscillators',
  accent: '#549cf0',
  segments: [
    { text: 'Every circuit so far has responded to something. Now we build one that starts on its own.',
      scene: { kind: 'title' } },
    { text: 'Begin with the component you have only met as a problem. The inductor.',
      scene: { kind: 'circuit', variant: 'flyback', flow: true, highlight: 'coil', label: 'A coil, on purpose this time' } },
    { text: 'A coil stores energy in a magnetic field, and it opposes a change in the current through it.',
      scene: { kind: 'compare', left: 'Inductor: current', right: 'Capacitor: voltage', caption: 'Each resists a change in one thing' } },
    { text: 'Now put an inductor and a capacitor together, and something rather beautiful happens.',
      scene: { kind: 'statement', lines: ['Put them', 'together'] } },
    { text: 'The capacitor discharges into the coil, building a magnetic field.',
      scene: { kind: 'statement', lines: ['Charge becomes', 'magnetic field'] } },
    { text: 'Then that field collapses and pushes the charge back, filling the capacitor the other way round.',
      scene: { kind: 'statement', lines: ['And the field', 'becomes charge'] } },
    { text: 'Energy sloshes back and forth between them, and it does it at one particular rate.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'sine', label: 'It rings' } },
    { text: 'That is the resonant frequency, and it depends only on the inductance and the capacitance.',
      scene: { kind: 'formula', expr: 'f = 1 / (2π √(L x C))' } },
    { text: 'Notice the square root, because it changes how you tune things.',
      scene: { kind: 'statement', lines: ['Notice the', 'square root'] } },
    { text: 'To halve the frequency you do not double the capacitance. You quadruple it.',
      scene: { kind: 'formula', expr: '4x the C, half the f' } },
    { text: 'An L C circuit with low losses rings for a long time, and that gives a very sharp filter.',
      scene: { kind: 'circuit', variant: 'bode', highlight: 'bandpass', label: 'A sharp band pass' } },
    { text: 'Sharp enough to pick one radio station out of a whole crowded band, which is what a tuner does.',
      scene: { kind: 'statement', lines: ['Sharp enough', 'to tune a radio'] } },
    { text: 'Now, an L C circuit rings, but the ringing dies away, because every real part has some resistance.',
      scene: { kind: 'statement', lines: ['It rings.', 'Then it stops.'] } },
    { text: 'To keep it going forever you have to put energy back in, in time with the ringing.',
      scene: { kind: 'statement', lines: ['Put energy back,', 'in time'] } },
    { text: 'And that is what an oscillator is. An amplifier that feeds its own output back to its input.',
      scene: { kind: 'circuit', variant: 'opamp', flow: true, highlight: 'feedback', label: 'An amplifier, fed back' } },
    { text: 'But fed back in phase, so it reinforces itself. That is positive feedback.',
      scene: { kind: 'compare', left: 'Negative: settles', right: 'Positive: builds', caption: 'The same wire, the opposite result' } },
    { text: 'You have already met positive feedback. It is what gave a comparator its hysteresis.',
      scene: { kind: 'statement', lines: ['You have seen', 'this before'] } },
    { text: 'Push it a little further and instead of latching, it swings back and forth on its own.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'square', label: 'And now it runs itself' } },
    { text: 'The simplest useful oscillator does not use a coil at all. It uses R C timing and a threshold.',
      scene: { kind: 'circuit', variant: 'rc', flow: true, label: 'Just a resistor and a capacitor' } },
    { text: 'A capacitor charges through a resistor until it crosses an upper threshold.',
      scene: { kind: 'plot', upTo: 0.66, marker: 'Charging to the upper line' } },
    { text: 'The output flips, which discharges the capacitor until it crosses a lower threshold, and it flips back.',
      scene: { kind: 'statement', lines: ['Flip. Discharge.', 'Flip. Charge.'] } },
    { text: 'Round and round, forever, and the output is a square wave.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'square', label: 'A square wave, from nothing' } },
    { text: 'That is a relaxation oscillator, and you have built one already. It is the 555 in astable mode.',
      scene: { kind: 'statement', lines: ['You built one.', 'It was the 555.'] } },
    { text: 'Which is why a bigger resistor or a bigger capacitor slows the blink. It takes longer to reach the thresholds.',
      scene: { kind: 'formula', expr: 'double R and C → quarter the f' } },
    { text: 'And the output is square rather than sine, because the threshold device snaps rather than glides.',
      scene: { kind: 'compare', left: 'LC: a smooth sine', right: 'RC: a hard square', caption: 'The shape follows the mechanism' } },
    { text: 'To see any of this properly you need an oscilloscope, which plots voltage against time.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'sine', label: 'Volts up, time across' } },
    { text: 'Count divisions across one cycle for the period, and divisions tall for the amplitude. Then f is one over T.',
      scene: { kind: 'formula', expr: '4 div x 0.5ms = 2ms → 500Hz' } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. An inductor and a capacitor swap energy and resonate at one over two pi root L C.',
      scene: { kind: 'recap', items: ['LC resonates at one frequency'] } },
    { text: 'Two. An oscillator is an amplifier with positive feedback, keeping itself going.',
      scene: { kind: 'recap', items: ['LC resonates at one frequency', 'An oscillator feeds itself'] } },
    { text: 'Three. A relaxation oscillator charges and discharges between thresholds, and gives a square wave.',
      scene: { kind: 'recap', items: ['LC resonates at one frequency', 'An oscillator feeds itself', 'RC plus a threshold gives a square wave'] } },
    { text: 'Go and change one capacitor in a 555 blinker, and predict the new rate before you power it.',
      scene: { kind: 'outro' } },
  ],
};
