import type { LessonScript } from '../types';

/**
 * Unit 12, Comms, Motors & Robotics. Checkpoint for "Robot Sensing & Comms".
 *
 * Two halves that belong together: how a robot finds out about the world, and
 * how the modules that do the finding out talk back. The film is honest about
 * what ultrasonic sensing actually gets wrong, because a learner will meet both
 * failures in an afternoon.
 */
export const robotSensingComms: LessonScript = {
  id: 'robot-sensing-comms',
  title: 'Sensing and Buses',
  unitTitle: 'Comms, Motors & Robotics',
  unitId: 'comms-motors-robotics',
  skillId: 'robot-sensing-comms',
  skillTitle: 'Robot Sensing & Comms',
  accent: '#549cf0',
  segments: [
    { text: 'A robot needs to know how far away things are. There are two common ways to find out.',
      scene: { kind: 'title' } },
    { text: 'The first one measures time rather than anything else. Ultrasonic time of flight.',
      scene: { kind: 'statement', lines: ['It measures', 'time'] } },
    { text: 'The module sends a short burst of sound at about forty kilohertz, well above hearing.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'square', label: 'A burst, then silence' } },
    { text: 'Then it listens for the echo and reports how long it took to come back.',
      scene: { kind: 'statement', lines: ['Send.', 'Then listen.'] } },
    { text: 'Sound travels at about three hundred and forty metres per second in room temperature air.',
      scene: { kind: 'formula', expr: '340 m/s in air' } },
    { text: 'So the time gives the distance, but you must halve it, because the pulse went out and came back.',
      scene: { kind: 'formula', expr: 'distance = (speed x time) / 2' } },
    { text: 'A six millisecond round trip is two point zero four metres of travel, so the object is one metre away.',
      scene: { kind: 'formula', expr: '2.04m / 2 = 1.02m' } },
    { text: 'On a common module you can skip the arithmetic. Divide the echo microseconds by fifty eight for centimetres.',
      scene: { kind: 'formula', expr: 'µs / 58 = cm' } },
    { text: 'Now be honest about where it fails, because it will look like a broken sensor.',
      scene: { kind: 'statement', lines: ['Where it', 'fails'] } },
    { text: 'The speed of sound changes with temperature, so a fixed number is only right at one temperature.',
      scene: { kind: 'compare', left: 'Cold morning', right: 'Hot afternoon', caption: 'The same object, different readings' } },
    { text: 'And a soft or angled surface scatters the pulse, so no echo comes back at all.',
      scene: { kind: 'statement', lines: ['A sofa returns', 'nothing'] } },
    { text: 'Aim one at a cushion at an angle and your robot confidently reports empty space.',
      scene: { kind: 'statement', lines: ['It reports', 'empty space'] } },
    { text: 'The second method uses light instead. An infrared reflectance sensor.',
      scene: { kind: 'circuit', variant: 'divider', flow: true, highlight: 'ldr', label: 'Light out, light back' } },
    { text: 'It shines infrared and measures how much comes back, as an analog voltage on a pin.',
      scene: { kind: 'circuit', variant: 'divider', flow: true, highlight: 'ldr tap', label: 'More reflection, more voltage' } },
    { text: 'That is short range, and it is the sensor a line follower uses to see the line under it.',
      scene: { kind: 'statement', lines: ['Short range,', 'and quick'] } },
    { text: 'It is fooled by colour and surface finish, so it needs calibrating for each floor.',
      scene: { kind: 'statement', lines: ['Every floor', 'is different'] } },
    { text: 'Now the other half. A robot is full of modules, and they all have to talk.',
      scene: { kind: 'circuit', variant: 'board', flow: true, highlight: 'mcu', label: 'Everything talks to this' } },
    { text: 'A motor driver, a distance sensor, a display. Each one is a chip with a bus.',
      scene: { kind: 'statement', lines: ['Every module', 'has a bus'] } },
    { text: 'You met the three in unit eleven, and the choice matters more on a robot than anywhere else.',
      scene: { kind: 'statement', lines: ['Three buses,', 'one choice'] } },
    { text: 'U A R T is two wires between exactly two devices, with no shared clock and an agreed baud rate.',
      scene: { kind: 'formula', expr: 'UART: 2 devices, 2 wires' } },
    { text: 'I squared C shares two wires, S D A for data and S C L for clock, among many devices at once.',
      scene: { kind: 'formula', expr: 'I2C: SDA and SCL' } },
    { text: 'Every device listens, and only the one whose address the controller names replies.',
      scene: { kind: 'statement', lines: ['They all listen.', 'One answers.'] } },
    { text: 'So a dozen slow sensors live on two wires, plus their pull up resistors, and nothing else.',
      scene: { kind: 'circuit', variant: 'pullup', flow: false, highlight: 'resistor', label: 'And it needs pull ups' } },
    { text: 'S P I is the fast one. A clock, data out, data in, and one chip select wire for every device.',
      scene: { kind: 'compare', left: 'I2C: 2 wires, always', right: 'SPI: a wire per device', caption: 'Scaling, or speed' } },
    { text: 'So on a real robot you mix them. S P I for the fast driver, I squared C for the crowd of slow sensors.',
      scene: { kind: 'statement', lines: ['Mix them,', 'by the job'] } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. Ultrasonic timing is speed times time over two, and soft or angled surfaces return nothing.',
      scene: { kind: 'recap', items: ['Ultrasonic: halve the round trip'] } },
    { text: 'Two. Infrared reflectance gives an analog voltage, and it needs calibrating on every surface.',
      scene: { kind: 'recap', items: ['Ultrasonic: halve the round trip', 'Infrared reflectance needs calibrating'] } },
    { text: 'Three. I squared C scales on two addressed wires, and S P I buys speed with a wire per device.',
      scene: { kind: 'recap', items: ['Ultrasonic: halve the round trip', 'Infrared reflectance needs calibrating', 'I2C for many, SPI for fast'] } },
    { text: 'Go and point an ultrasonic sensor at a cushion, and then at a wall.',
      scene: { kind: 'outro' } },
  ],
};
