import type { LessonScript } from '../types';

/**
 * Unit 12, Comms, Motors & Robotics. Checkpoint for "Robot Control".
 *
 * The last checkpoint in the curriculum, so the film closes the arc it opened
 * in unit three: sense, decide, act, now with feedback around it. The line
 * follower is the capstone and the proportional steering at the end is the
 * first genuinely closed loop a learner writes.
 */
export const robotControl: LessonScript = {
  id: 'robot-control',
  title: 'Robot Control',
  unitTitle: 'Comms, Motors & Robotics',
  unitId: 'comms-motors-robotics',
  skillId: 'robot-control',
  skillTitle: 'Robot Control',
  accent: '#549cf0',
  segments: [
    { text: 'A robot runs the same loop your light alarm did. What changes is the size of each stage.',
      scene: { kind: 'title' } },
    { text: 'Sensing is no longer one divider. It is line sensors, a distance sensor and an encoder.',
      scene: { kind: 'statement', lines: ['Sense.', 'Decide.', 'Act.'] } },
    { text: 'Deciding is logic across all of them together, rather than one comparison against a threshold.',
      scene: { kind: 'statement', lines: ['Several inputs,', 'one decision'] } },
    { text: 'And acting drives two motors through an H bridge, at two different speeds.',
      scene: { kind: 'circuit', variant: 'flyback', flow: true, highlight: 'coil', label: 'A motor, driven properly' } },
    { text: 'The loop repeats, and how fast it repeats is what decides whether your robot reacts in time.',
      scene: { kind: 'statement', lines: ['How fast it loops', 'is how fast it reacts'] } },
    { text: 'Which is why a long delay in a control loop is so damaging.',
      scene: { kind: 'formula', expr: 'delay(500);' } },
    { text: 'During that half second the robot senses nothing and decides nothing. It is blind, and still moving.',
      scene: { kind: 'compare', left: 'Loops 100 times a second', right: 'Loops twice a second', caption: 'The same code, one delay apart' } },
    { text: 'Polling everything each pass is fine for slow inputs, and that is most of them.',
      scene: { kind: 'statement', lines: ['Poll the', 'slow things'] } },
    { text: 'But an encoder pulse from a spinning wheel is brief, and a busy loop will miss it.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'square', label: 'Pulses, faster than your loop' } },
    { text: 'So those go on an interrupt, caught the instant they happen, while the loop carries on.',
      scene: { kind: 'statement', lines: ['Interrupt the', 'fast things'] } },
    { text: 'Now the idea that separates a toy from a machine.',
      scene: { kind: 'statement', lines: ['One idea'] } },
    { text: 'Open loop control commands an action and trusts that it happened.',
      scene: { kind: 'statement', lines: ['Command it.', 'Hope.'] } },
    { text: 'Drive both motors at half power for one second, and assume you went forward in a straight line.',
      scene: { kind: 'statement', lines: ['Half power,', 'one second'] } },
    { text: 'That is called dead reckoning, and everything conspires against it.',
      scene: { kind: 'statement', lines: ['Dead reckoning'] } },
    { text: 'A draining battery slows both wheels. A heavier load slows them unequally.',
      scene: { kind: 'statement', lines: ['The battery drains.', 'The load changes.'] } },
    { text: 'And no two motors are identical, so equal commands never produce equal motion.',
      scene: { kind: 'compare', left: 'Equal commands', right: 'Equal movement', caption: 'These are not the same thing' } },
    { text: 'So it veers, nothing notices, and the error accumulates for as long as it runs.',
      scene: { kind: 'statement', lines: ['Nothing notices.', 'It just drifts.'] } },
    { text: 'Closed loop control adds a sensor that measures what actually happened, and feeds it back.',
      scene: { kind: 'statement', lines: ['Measure it.', 'Feed it back.'] } },
    { text: 'An encoder counts how far each wheel really turned, so the controller can correct the difference.',
      scene: { kind: 'statement', lines: ['It corrects', 'the difference'] } },
    { text: 'That is feedback, and it is the same self correcting idea as the op-amp in unit eight.',
      scene: { kind: 'circuit', variant: 'opamp', flow: true, highlight: 'feedback', label: 'The same idea, again' } },
    { text: 'Which is why a stepper can be open loop and stay accurate. Its steps are countable, so counting is the feedback.',
      scene: { kind: 'statement', lines: ['A stepper counts,', 'so it can guess'] } },
    { text: 'Now put all of it together in the build this unit exists for. The line follower.',
      scene: { kind: 'statement', lines: ['The line', 'follower'] } },
    { text: 'Two infrared sensors underneath read a dark line on a light floor.',
      scene: { kind: 'circuit', variant: 'divider', flow: true, highlight: 'ldr tap', label: 'Dark reads low, light reads high' } },
    { text: 'You pick a threshold between the dark reading and the light one, exactly as you did for the alarm.',
      scene: { kind: 'compare', left: 'Over the line', right: 'Over the floor', caption: 'And a threshold measured between them' } },
    { text: 'Measure it on the floor you are actually using, because a glossier floor reflects completely differently.',
      scene: { kind: 'statement', lines: ['Calibrate on', 'this floor'] } },
    { text: 'Then steer by running the wheels at different speeds, which is called differential drive.',
      scene: { kind: 'statement', lines: ['Slow one wheel', 'to turn'] } },
    { text: 'And the last upgrade is the one that makes it look smooth instead of drunk.',
      scene: { kind: 'statement', lines: ['One last', 'upgrade'] } },
    { text: 'Do not just steer left or right. Steer in proportion to how far off centre the line actually is.',
      scene: { kind: 'compare', left: 'Full turn, either way', right: 'A turn sized to the error', caption: 'Proportional control' } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. Sense, decide, act, and keep the loop fast, because a delay makes a moving robot blind.',
      scene: { kind: 'recap', items: ['Keep the loop fast'] } },
    { text: 'Two. Open loop drifts and never knows it. Closed loop measures the result and corrects it.',
      scene: { kind: 'recap', items: ['Keep the loop fast', 'Feedback turns guessing into knowing'] } },
    { text: 'Three. Calibrate on the surface you are on, and steer in proportion to the error.',
      scene: { kind: 'recap', items: ['Keep the loop fast', 'Feedback turns guessing into knowing', 'Correct in proportion to the error'] } },
    { text: 'That is the whole curriculum, from one loop to a robot that closes its own. Go and build it.',
      scene: { kind: 'outro' } },
  ],
};
