import type { LessonScript } from '../types';

/**
 * Unit 12, Comms, Motors & Robotics. Sits at the checkpoint for "Fusing
 * Sensors".
 *
 * Chosen for video because both failures are shapes over time and neither is
 * visible in a single reading. An accelerometer's noise looks like a correct
 * angle if you sample it once; a gyro's drift looks perfect for the first two
 * seconds and is useless by the thirtieth. Watching one trace jitter while the
 * other slides quietly away is the entire argument for fusing them.
 */
export const sensorFusion: LessonScript = {
  id: 'sensor-fusion',
  title: 'Fusing Sensors',
  unitTitle: 'Comms, Motors & Robotics',
  unitId: 'comms-motors-robotics',
  skillId: 'sensor-fusion',
  skillTitle: 'Fusing Sensors',
  accent: '#549cf0',
  segments: [
    { text: 'You want to know which way up your robot is. You have two sensors, and both of them lie.',
      scene: { kind: 'title' } },
    { text: 'They lie in opposite directions, which turns out to be the most useful thing about them.',
      scene: { kind: 'statement', lines: ['Two liars.', 'Opposite lies.'] } },
    { text: 'An accelerometer measures gravity, which tells you which way down is.',
      scene: { kind: 'circuit', variant: 'board', flow: true, highlight: 'chip', label: 'Where is down?' } },
    { text: 'It also measures every other acceleration acting on it at that instant. It cannot tell them apart.',
      scene: { kind: 'statement', lines: ['Gravity,', 'plus everything else'] } },
    { text: 'A bump, a motor starting, the robot changing speed. All of it lands in the same reading as gravity.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'noise', label: 'Gravity, under all the noise' } },
    { text: 'So on a moving robot the accelerometer angle jumps around several degrees, several times a second.',
      scene: { kind: 'statement', lines: ['Noisy.', 'Every sample.'] } },
    { text: 'But here is the thing. It is jumping around the RIGHT answer, and it never stops being centred on it.',
      scene: { kind: 'compare', left: 'Noisy sample to sample', right: 'Correct on average, forever', caption: 'The accelerometer never drifts' } },
    { text: 'The gyroscope has the exact opposite personality.',
      scene: { kind: 'statement', lines: ['The exact', 'opposite'] } },
    { text: 'It does not measure angle at all. It measures how fast the angle is changing, in degrees per second.',
      scene: { kind: 'formula', expr: 'angle += gyro × dt', note: 'Add up the rate to get the angle' } },
    { text: 'To get an angle you add those rates up, over and over, hundreds of times a second.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'smooth', label: 'Beautifully smooth' } },
    { text: 'And it is beautiful. Smooth, immediate, completely unbothered by bumps and motors.',
      scene: { kind: 'statement', lines: ['Smooth.', 'Immediate.'] } },
    { text: 'For about ten seconds.',
      scene: { kind: 'statement', lines: ['For about', 'ten seconds'] } },
    { text: 'The rate reading has a tiny constant error in it. A fraction of a degree per second that should be zero.',
      scene: { kind: 'compare', left: 'Error per sample: tiny', right: 'Error after a minute: huge', caption: 'What adding up does to a small bias' } },
    { text: 'You are adding that error up too. Sit the robot perfectly still and watch the angle slide away.',
      scene: { kind: 'compare', left: 'Robot: perfectly still', right: 'Gyro: 40° and climbing', caption: 'A stationary robot, according to its gyro' } },
    { text: 'That is drift, and integration guarantees it. Any bias at all, added up, goes to infinity.',
      scene: { kind: 'statement', lines: ['Small error.', 'Added up forever.'] } },
    { text: 'So. One sensor is noisy but never drifts. The other is smooth but drifts without limit.',
      scene: { kind: 'compare', left: 'Accel: noisy, no drift', right: 'Gyro: smooth, drifts', caption: 'Each fixes the other exactly' } },
    { text: 'They fail in ways that have nothing in common, and that is what makes fusing them work.',
      scene: { kind: 'statement', lines: ['Different failures', 'cancel'] } },
    { text: 'The complementary filter does it in a single line of code.',
      scene: { kind: 'formula', expr: 'angle = 0.98 × (angle + gyro×dt) + 0.02 × accel', note: 'Trust the gyro short term, the accelerometer long term' } },
    { text: 'Ninety eight percent of the new angle comes from the gyro estimate. Two percent comes from the accelerometer.',
      scene: { kind: 'statement', lines: ['98% gyro.', '2% accelerometer.'] } },
    { text: 'That two percent looks negligible. It is doing all the work that matters.',
      scene: { kind: 'statement', lines: ['Two percent,', 'doing the work'] } },
    { text: 'Over one sample it barely moves the answer, so the accelerometer noise almost entirely disappears.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'smooth', label: 'The noise, filtered out' } },
    { text: 'But it applies again on every single sample, and it always pulls toward the sensor that cannot drift.',
      scene: { kind: 'compare', left: 'Gyro pulls it away', right: 'Accel pulls it back', caption: 'A tug of war the accelerometer wins' } },
    { text: 'Drift never accumulates, because something is quietly correcting it hundreds of times a second.',
      scene: { kind: 'statement', lines: ['Smooth now.', 'Right in an hour.'] } },
    { text: 'The two weights must add to one. If they do not, the output is not an angle any more.',
      scene: { kind: 'formula', expr: 'a + (1 − a) = 1', note: 'Otherwise the estimate scales away from reality' } },
    { text: 'And the weight is a choice, not a constant handed down. It sets how much you trust each sensor.',
      scene: { kind: 'compare', left: '0.98: trusts the gyro more', right: '0.90: reacts faster, noisier', caption: 'Tune it to your machine' } },
    { text: 'A quiet wheeled robot can trust the accelerometer more. A drone being thrown about cannot.',
      scene: { kind: 'statement', lines: ['Tune it to', 'the machine'] } },
    { text: 'A Kalman filter does the same job with a model of how much each sensor is actually trusted, updated live.',
      scene: { kind: 'compare', left: 'Complementary: one line', right: 'Kalman: a model of trust', caption: 'Better, and far more to get wrong' } },
    { text: 'For most robots, the one line version is genuinely good enough, and you can debug it.',
      scene: { kind: 'statement', lines: ['Good enough,', 'and debuggable'] } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. The accelerometer is noisy and never drifts. The gyro is smooth and always drifts.',
      scene: { kind: 'recap', items: ['Noisy but honest, smooth but drifting'] } },
    { text: 'Two. Integrating any rate integrates its error too. Drift is not a fault, it is arithmetic.',
      scene: { kind: 'recap', items: ['Noisy but honest, smooth but drifting', 'Integration always drifts'] } },
    { text: 'Three. One line, weights adding to one, and both sensors stop lying.',
      scene: { kind: 'recap', items: ['Noisy but honest, smooth but drifting', 'Integration always drifts', 'Weights must sum to one'] } },
    { text: 'Go and log a gyro angle with the board sitting still, and watch how long it stays believable.',
      scene: { kind: 'outro' } },
  ],
};
