import type { LessonScript } from '../types';

/**
 * Unit 1, Foundations. Checkpoint for "Series, Parallel & Measuring".
 *
 * Two ideas that only make sense together: how the parts are joined, and how
 * you find out what they are doing. The meter half is here rather than in its
 * own film because measuring is meaningless until you know what reading to
 * expect.
 */
export const seriesParallel: LessonScript = {
  id: 'series-parallel',
  title: 'Series, Parallel, Meter',
  unitTitle: 'Foundations',
  unitId: 'foundations',
  skillId: 'series-parallel',
  skillTitle: 'Series, Parallel & Measuring',
  accent: '#f2b705',
  segments: [
    { text: 'There are only two ways to join two components, and everything else is a combination of them.',
      scene: { kind: 'title' } },
    { text: 'Series means one path. Parallel means more than one.',
      scene: { kind: 'compare', left: 'One path', right: 'Many paths', caption: 'That is the whole distinction' } },
    { text: 'Here is series. A single loop, so the same current goes through every part in it.',
      scene: { kind: 'circuit', variant: 'loop', flow: true, label: 'Series: one path' } },
    { text: 'There is nowhere else for it to go, so resistances in series simply add up.',
      scene: { kind: 'formula', expr: '10kΩ + 10kΩ = 20kΩ' } },
    { text: 'Five volts across twenty kilohms gives a quarter of a milliamp.',
      scene: { kind: 'formula', expr: '5V / 20kΩ = 0.25mA' } },
    { text: 'And break any part of that loop and everything stops. One path means one break is enough.',
      scene: { kind: 'circuit', variant: 'loop', flow: false, broken: 'right', label: 'One break stops it all' } },
    { text: 'Parallel is the other arrangement.',
      scene: { kind: 'circuit', variant: 'parallel', flow: true, label: 'Parallel: branches' } },
    { text: 'Each branch connects straight across the supply, so every branch sees the full voltage.',
      scene: { kind: 'circuit', variant: 'parallel', flow: true, highlight: 'r1', label: 'Each branch sees all of it' } },
    { text: 'What splits is the current. Two branches at twelve milliamps each pull twenty four from the supply.',
      scene: { kind: 'formula', expr: '12mA + 12mA = 24mA' } },
    { text: 'Branch currents add. That is the rule to carry around.',
      scene: { kind: 'statement', lines: ['Branch currents', 'add'] } },
    { text: 'Parallel resistance goes the other way. Two equal resistors in parallel give half of one of them.',
      scene: { kind: 'formula', expr: 'two 1kΩ = 500Ω' } },
    { text: 'That surprises people. You added a resistor and the resistance went down.',
      scene: { kind: 'statement', lines: ['Add a resistor,', 'get less resistance'] } },
    { text: 'It makes sense in paths. You opened a second road, so more traffic gets through for the same pressure.',
      scene: { kind: 'statement', lines: ['A second road,', 'more traffic'] } },
    { text: 'This is why two LEDs in parallel each get their own resistor.',
      scene: { kind: 'circuit', variant: 'parallel', flow: true, highlight: 'r1 r2', label: 'One resistor per branch' } },
    { text: 'No two LEDs are identical. Share one resistor and the greedier LED takes most of the current.',
      scene: { kind: 'compare', left: 'Own resistor', right: 'Shared resistor', caption: 'One of these gives matched brightness' } },
    { text: 'And if one parallel branch fails open, the others carry on exactly as before.',
      scene: { kind: 'statement', lines: ['Branches are', 'independent'] } },
    { text: 'Now, how you find out what your circuit is really doing.',
      scene: { kind: 'statement', lines: ['Now measure it'] } },
    { text: 'A multimeter gives you two readings constantly, and they are connected in opposite ways.',
      scene: { kind: 'statement', lines: ['Two readings,', 'two connections'] } },
    { text: 'Voltage is measured across a component. The meter sits in parallel with it and changes nothing.',
      scene: { kind: 'circuit', variant: 'divider', flow: true, highlight: 'tap', label: 'Voltage: across' } },
    { text: 'Current is measured through the path. You break the loop and put the meter in it, in series.',
      scene: { kind: 'circuit', variant: 'loop', flow: false, broken: 'right', label: 'Current: in the loop' } },
    { text: 'That difference is not a detail. On its current range a meter is almost a piece of wire.',
      scene: { kind: 'compare', left: 'Across: fine', right: 'Across on amps: short', caption: 'The mistake that blows the fuse' } },
    { text: 'Put that across a battery and you have made a short circuit with your own meter.',
      scene: { kind: 'statement', lines: ['A short circuit', 'you built'] } },
    { text: 'So reach for voltage first. It is the safe measurement, and it tells you most of what you need.',
      scene: { kind: 'statement', lines: ['Voltage first,', 'always'] } },
    { text: 'Two equal resistors across five volts should read two point five volts at the midpoint.',
      scene: { kind: 'formula', expr: '5V, equal resistors → 2.5V' } },
    { text: 'If your meter says something else, you have just found a fault without touching a single wire.',
      scene: { kind: 'statement', lines: ['A fault found', 'without touching it'] } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. Series shares one current and adds resistance. Parallel shares one voltage and adds current.',
      scene: { kind: 'recap', items: ['Series adds R, parallel adds I'] } },
    { text: 'Two. Give every parallel LED its own resistor, or they will not match.',
      scene: { kind: 'recap', items: ['Series adds R, parallel adds I', 'One resistor per branch'] } },
    { text: 'Three. Voltage across, current through, and never current across anything.',
      scene: { kind: 'recap', items: ['Series adds R, parallel adds I', 'One resistor per branch', 'Voltage across, current through'] } },
    { text: 'Go and predict a reading before you take it. That is the whole skill.',
      scene: { kind: 'outro' } },
  ],
};
