import type { LessonScript } from '../types';

/**
 * Unit 9, Filters, Oscillators & Signals. Checkpoint for "Signals & AC".
 *
 * The unit opens by changing what a learner thinks a signal IS, from a shape
 * over time to a set of frequencies. The film ends there rather than starting
 * there, because the frequency view only lands once the time view is solid.
 */
export const signals: LessonScript = {
  id: 'signals',
  title: 'Signals and AC',
  unitTitle: 'Filters, Oscillators & Signals',
  unitId: 'filters-oscillators',
  skillId: 'signals',
  skillTitle: 'Signals & AC',
  accent: '#549cf0',
  segments: [
    { text: 'Everything you have measured so far held still. Now the voltage moves, and we need a language for it.',
      scene: { kind: 'title' } },
    { text: 'A signal is a voltage that changes over time, and the shape it traces is its waveform.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'sine', label: 'A voltage, over time' } },
    { text: 'The sine wave is the smooth one, and it is the natural shape of alternating current.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'sine', label: 'The sine: smooth' } },
    { text: 'The square wave snaps between two levels, which is what a digital pin does.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'square', label: 'The square: two levels' } },
    { text: 'Two measurements describe any repeating wave, and they are two views of the same thing.',
      scene: { kind: 'statement', lines: ['Two numbers,', 'one fact'] } },
    { text: 'The period is how long one full cycle takes. The frequency is how many cycles fit in a second.',
      scene: { kind: 'formula', expr: 'f = 1 / T' } },
    { text: 'A wave that repeats every twenty milliseconds runs at fifty hertz.',
      scene: { kind: 'formula', expr: '1 / 0.020s = 50Hz' } },
    { text: 'And a one kilohertz signal has a period of one millisecond. Faster means shorter.',
      scene: { kind: 'formula', expr: '1 / 1000Hz = 1ms' } },
    { text: 'Now the height, which is where AC gets genuinely confusing.',
      scene: { kind: 'statement', lines: ['Now the height'] } },
    { text: 'There are three different numbers you could quote, and they are all correct.',
      scene: { kind: 'statement', lines: ['Three answers,', 'all correct'] } },
    { text: 'Peak is from the middle to the top. Peak to peak is the whole swing, bottom to top.',
      scene: { kind: 'formula', expr: 'Vpp = 2 x Vp' } },
    { text: 'On a scope you read peak to peak, because that is the height you can actually see.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'sine', label: 'What a scope shows you' } },
    { text: 'And the third one is R M S, which is the number that actually matters for power.',
      scene: { kind: 'statement', lines: ['RMS is the', 'power number'] } },
    { text: 'It is the steady DC voltage that would heat a resistor by exactly the same amount.',
      scene: { kind: 'compare', left: 'AC at 7V RMS', right: 'DC at 7V', caption: 'The same heat in the same resistor' } },
    { text: 'For a sine wave, R M S is the peak divided by the square root of two.',
      scene: { kind: 'formula', expr: 'Vrms = Vp / √2' } },
    { text: 'A ten volt peak sine is seven point zero seven volts R M S.',
      scene: { kind: 'formula', expr: '10V peak = 7.07V RMS' } },
    { text: 'Careful, though. That ratio is for sine waves only. A square wave has a completely different one.',
      scene: { kind: 'statement', lines: ['Sines only.', 'Not squares.'] } },
    { text: 'And this explains a number you already know. Mains is quoted as two hundred and thirty volts.',
      scene: { kind: 'statement', lines: ['230 volts', 'is an RMS figure'] } },
    { text: 'That is R M S. The actual peak is one point four one times higher, at about three hundred and twenty five.',
      scene: { kind: 'formula', expr: '1.414 x 230V = 325V' } },
    { text: 'Which is why insulation and capacitor ratings for mains are specified far above two thirty.',
      scene: { kind: 'statement', lines: ['Rate for the peak,', 'not the label'] } },
    { text: 'Now the idea the rest of this unit is built on.',
      scene: { kind: 'statement', lines: ['One more idea'] } },
    { text: 'Any signal, of any shape, can be seen as a sum of sine waves at different frequencies.',
      scene: { kind: 'statement', lines: ['Every signal is', 'a sum of sines'] } },
    { text: 'A pure tone is a single frequency. Nothing else in it at all.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'sine', label: 'One frequency' } },
    { text: 'A square wave is a sine at its own frequency, plus a stack of higher harmonics on top.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'square', label: 'A fundamental, plus harmonics' } },
    { text: 'Those harmonics are what make its corners sharp. Take them away and the corners round off.',
      scene: { kind: 'statement', lines: ['The harmonics', 'are the corners'] } },
    { text: 'And noise is energy spread thinly across a huge range of frequencies at once.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'noise', label: 'Noise: everywhere at once' } },
    { text: 'Which is exactly why filtering works. If your signal and your noise sit in different places, you can separate them.',
      scene: { kind: 'circuit', variant: 'bode', highlight: 'lowpass', label: 'Keep some, drop the rest' } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. Frequency is one over the period, so a faster wave has a shorter cycle.',
      scene: { kind: 'recap', items: ['f = 1 / T'] } },
    { text: 'Two. Peak to peak is twice the peak, and R M S is the peak over root two for a sine.',
      scene: { kind: 'recap', items: ['f = 1 / T', 'RMS is the DC equivalent'] } },
    { text: 'Three. Any signal is a sum of frequencies, and that is what makes filtering possible.',
      scene: { kind: 'recap', items: ['f = 1 / T', 'RMS is the DC equivalent', 'A signal is a set of frequencies'] } },
    { text: 'Go and work out the peak voltage of a nine volt R M S transformer output.',
      scene: { kind: 'outro' } },
  ],
};
