import type { LessonScript } from '../types';

/**
 * Unit 12, Comms, Motors & Robotics. Checkpoint for "Speed & Precision".
 *
 * Three actuators for three different questions: how fast, what angle, how far.
 * The stepper section ends on open loop drift, which is the failure a learner
 * will meet on their first long print or gantry move.
 */
export const speedAndPrecision: LessonScript = {
  id: 'speed-and-precision',
  title: 'Speed and Precision',
  unitTitle: 'Comms, Motors & Robotics',
  unitId: 'comms-motors-robotics',
  skillId: 'speed-and-precision',
  skillTitle: 'Speed & Precision',
  accent: '#549cf0',
  segments: [
    { text: 'Three ways to move something, and they answer three different questions.',
      scene: { kind: 'title' } },
    { text: 'How fast. What angle. And how far. Pick the wrong one and the job is much harder than it needs to be.',
      scene: { kind: 'statement', lines: ['How fast.', 'What angle.', 'How far.'] } },
    { text: 'Start with speed, and you already know the technique from unit five.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'pwm50 avg', label: 'PWM, again' } },
    { text: 'Pulse the supply fully on and fully off, very fast, and vary how long it spends on.',
      scene: { kind: 'statement', lines: ['Fully on.', 'Fully off.'] } },
    { text: 'The motor’s inertia averages the pulses out, so it behaves as if it saw the average voltage.',
      scene: { kind: 'statement', lines: ['The motor does', 'the averaging'] } },
    { text: 'Fifty percent duty on nine volts acts like four and a half.',
      scene: { kind: 'formula', expr: '50% x 9V = 4.5V average' } },
    { text: 'On an Arduino that is analogWrite, from nought to two hundred and fifty five.',
      scene: { kind: 'formula', expr: 'analogWrite(M, 128);' } },
    { text: 'And it is efficient for the same reason a saturated transistor is. The switch is never in the middle.',
      scene: { kind: 'compare', left: 'PWM: little heat', right: 'A resistor: all heat', caption: 'Two ways to slow a motor' } },
    { text: 'One thing surprises people. A motor that runs happily at ten percent duty will not start at ten percent.',
      scene: { kind: 'statement', lines: ['It runs at 10.', 'It will not start at 10.'] } },
    { text: 'Starting has to overcome static friction with no momentum to help, so it needs more torque than keeping going.',
      scene: { kind: 'statement', lines: ['Starting costs', 'more than running'] } },
    { text: 'Now the second question. Not how fast, but what angle.',
      scene: { kind: 'statement', lines: ['What angle'] } },
    { text: 'A hobby servo is a small geared motor with electronics inside that hold a commanded position.',
      scene: { kind: 'statement', lines: ['It holds', 'a position'] } },
    { text: 'You do not set its speed. You tell it an angle and it drives itself there and stays.',
      scene: { kind: 'compare', left: 'Motor: a speed', right: 'Servo: an angle', caption: 'Two completely different commands' } },
    { text: 'And it tells you nothing back. It just holds, against a load, until you say something else.',
      scene: { kind: 'statement', lines: ['It holds,', 'against a load'] } },
    { text: 'The command is not a voltage. It is the width of a pulse on the signal wire.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'pwm25', label: 'The width is the command' } },
    { text: 'One millisecond is about nought degrees. One and a half is centre. Two milliseconds is about a hundred and eighty.',
      scene: { kind: 'formula', expr: '1ms = 0°, 1.5ms = 90°' } },
    { text: 'And that pulse has to repeat about every twenty milliseconds, or the servo goes limp.',
      scene: { kind: 'formula', expr: 'repeat every 20ms' } },
    { text: 'The Servo library generates all of that for you. You call write with an angle and it handles the timing.',
      scene: { kind: 'statement', lines: ['The library does', 'the timing'] } },
    { text: 'Those pulse widths are nominal, though. Real servos differ, which is why libraries let you calibrate the ends.',
      scene: { kind: 'statement', lines: ['Nominal, not', 'exact'] } },
    { text: 'Third question. How far, precisely, over any distance you like.',
      scene: { kind: 'statement', lines: ['How far,', 'precisely'] } },
    { text: 'A stepper motor has several coils around a magnetic rotor, and no brushes at all.',
      scene: { kind: 'statement', lines: ['Several coils.', 'No brushes.'] } },
    { text: 'Energise them in the right sequence and the rotor is pulled round one fixed step at a time.',
      scene: { kind: 'statement', lines: ['One step,', 'then the next'] } },
    { text: 'A two hundred step motor turns one point eight degrees per step, so fifty steps is a quarter turn.',
      scene: { kind: 'formula', expr: '360° / 200 = 1.8° per step' } },
    { text: 'Count the steps you commanded and you know exactly where it is, with no sensor anywhere.',
      scene: { kind: 'statement', lines: ['Count the steps,', 'know the position'] } },
    { text: 'Which is called open loop control, and it has one specific way of failing.',
      scene: { kind: 'statement', lines: ['Open loop,', 'and one failure'] } },
    { text: 'Overload it and it misses a step. Nothing reports that, so the position quietly drifts, forever.',
      scene: { kind: 'compare', left: 'Commanded 50', right: 'Moved 49', caption: 'And nothing tells you' } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. P W M sets a motor’s speed by duty cycle, and starting needs more duty than running.',
      scene: { kind: 'recap', items: ['PWM duty sets the speed'] } },
    { text: 'Two. A servo is commanded by pulse width, repeated every twenty milliseconds, and it holds an angle.',
      scene: { kind: 'recap', items: ['PWM duty sets the speed', 'A servo holds a commanded angle'] } },
    { text: 'Three. A stepper counts steps for precise position, and a missed step is invisible.',
      scene: { kind: 'recap', items: ['PWM duty sets the speed', 'A servo holds a commanded angle', 'A stepper counts, and can drift'] } },
    { text: 'Go and find the lowest duty cycle your motor will actually start from.',
      scene: { kind: 'outro' } },
  ],
};
