import type { LessonScript } from '../types';

/**
 * Unit 2, On the Breadboard. Checkpoint for "Switches & Control".
 *
 * The lessons cover the idea, a switch is a controlled break. The film adds the
 * two things that only show up at the bench: contact bounce, which no still
 * diagram can convey, and the current rating that decides whether a button
 * survives what you connect to it.
 */
export const switchesControl: LessonScript = {
  id: 'switches-control',
  title: 'Switches and Control',
  unitTitle: 'On the Breadboard',
  unitId: 'breadboard',
  skillId: 'switches-control',
  skillTitle: 'Switches & Control',
  accent: '#549cf0',
  segments: [
    { text: 'A switch is not a source of power. It is a break in the loop that you get to control.',
      scene: { kind: 'title' } },
    { text: 'Open, there is a gap in the circuit, and current has no way across it.',
      scene: { kind: 'circuit', variant: 'switch', flow: false, label: 'Open: no path' } },
    { text: 'Closed, the gap is bridged, the loop is whole, and the lamp lights.',
      scene: { kind: 'circuit', variant: 'switch', flow: true, label: 'Closed: the loop is whole' } },
    { text: 'That is the entire idea. Everything else is detail about how the gap gets bridged.',
      scene: { kind: 'statement', lines: ['A gap', 'you control'] } },
    { text: 'A momentary switch, the little tactile button in your kit, is closed only while you hold it down.',
      scene: { kind: 'compare', left: 'Momentary', right: 'Toggle', caption: 'Held closed, or stays put' } },
    { text: 'A toggle or slide switch stays wherever you leave it. Momentary for events, toggle for states.',
      scene: { kind: 'statement', lines: ['Events, or states'] } },
    { text: 'Switches are described by poles and throws, and the words are worth ten seconds.',
      scene: { kind: 'statement', lines: ['Poles', 'and throws'] } },
    { text: 'A pole is one separate circuit the switch controls. A throw is one position it can connect to.',
      scene: { kind: 'statement', lines: ['Pole: a circuit.', 'Throw: a position.'] } },
    { text: 'Single pole, single throw is plain on and off. That is your pushbutton.',
      scene: { kind: 'formula', expr: 'SPST = on or off' } },
    { text: 'Single pole, double throw picks between two destinations instead of just breaking the path.',
      scene: { kind: 'formula', expr: 'SPDT = A or B' } },
    { text: 'So where does a switch go in the loop?',
      scene: { kind: 'statement', lines: ['Where does it go?'] } },
    { text: 'In a single series loop, anywhere works. One path means one break stops everything.',
      scene: { kind: 'circuit', variant: 'switch', flow: false, label: 'Anywhere breaks it' } },
    { text: 'In practice, put it on the high side, between the supply and the load.',
      scene: { kind: 'statement', lines: ['High side,', 'by habit'] } },
    { text: 'Then when it is off, the load sits at ground rather than floating at supply voltage.',
      scene: { kind: 'statement', lines: ['Off means', 'sitting at ground'] } },
    { text: 'Now the thing that will confuse you the first time a switch meets code.',
      scene: { kind: 'statement', lines: ['One press,', 'many readings'] } },
    { text: 'The contacts inside a switch are metal springs. When they meet, they bounce apart and back again.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'bounce', label: 'One press, close up' } },
    { text: 'It settles in something like one to five milliseconds. Your eye will never see it happen.',
      scene: { kind: 'statement', lines: ['Settled in', 'a few milliseconds'] } },
    { text: 'A microcontroller reading that pin sees five or six separate presses where you made one.',
      scene: { kind: 'compare', left: 'You pressed once', right: 'It counted five', caption: 'The same event, two accounts' } },
    { text: 'The fix in software is called debouncing. After the first change, ignore that pin for a while.',
      scene: { kind: 'statement', lines: ['Ignore it,', 'briefly'] } },
    { text: 'Twenty to fifty milliseconds is the usual window. Long enough to settle, short enough to feel instant.',
      scene: { kind: 'formula', expr: 'ignore for 20 to 50ms' } },
    { text: 'You can do it in hardware too, with a small capacitor across the contacts to smooth the bouncing away.',
      scene: { kind: 'statement', lines: ['Or a capacitor,', 'in hardware'] } },
    { text: 'Last thing, and it is printed on the packet. Every switch has a current and a voltage rating.',
      scene: { kind: 'statement', lines: ['Switches have', 'ratings'] } },
    { text: 'A tactile button rated at fifty milliamps will pit its contacts and eventually weld shut driving a motor.',
      scene: { kind: 'compare', left: '50mA rating', right: '500mA motor', caption: 'This ends one way' } },
    { text: 'When the load is bigger than the switch, do not make the switch carry it.',
      scene: { kind: 'statement', lines: ['Do not make', 'it carry the load'] } },
    { text: 'Use the switch to control a transistor, and let the transistor take the current.',
      scene: { kind: 'circuit', variant: 'transistor', flow: true, highlight: 'base', label: 'The switch decides, the transistor works' } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. A switch is a controlled break, and anywhere in a series loop will do.',
      scene: { kind: 'recap', items: ['A switch is a controlled break'] } },
    { text: 'Two. Contacts bounce for a few milliseconds, so anything counting presses must debounce.',
      scene: { kind: 'recap', items: ['A switch is a controlled break', 'Real contacts bounce'] } },
    { text: 'Three. Check the rating, and put a transistor in the path when the load is bigger.',
      scene: { kind: 'recap', items: ['A switch is a controlled break', 'Real contacts bounce', 'Check the current rating'] } },
    { text: 'Go and count one button press in code. Then count it again with a delay.',
      scene: { kind: 'outro' } },
  ],
};
