import type { LessonScript } from '../types';

/**
 * Unit 10, Power Supplies & Regulation. Checkpoint for "Switching & Choosing".
 *
 * A choosing film, and the last one before the digital half of the curriculum.
 * It closes the power chain by tying the regulator back to the decoupling
 * capacitor from unit six, because a regulated rail is not a clean rail.
 */
export const switchingRegulation: LessonScript = {
  id: 'switching-regulation',
  title: 'Switching and Choosing',
  unitTitle: 'Power Supplies & Regulation',
  unitId: 'power-supplies',
  skillId: 'switching-regulation',
  skillTitle: 'Switching & Choosing',
  accent: '#f2b705',
  segments: [
    { text: 'A linear regulator burns off the voltage you did not want. There is a way not to burn anything.',
      scene: { kind: 'title' } },
    { text: 'Think about where the heat came from. A transistor held half on, dropping seven volts.',
      scene: { kind: 'compare', left: 'Half on: hot', right: 'Fully on: cool', caption: 'You already know this one' } },
    { text: 'You met that exact idea with transistors. A partly on switch is a heater.',
      scene: { kind: 'circuit', variant: 'transistor', flow: true, label: 'Saturation, or heat' } },
    { text: 'So a switching regulator never sits in the middle. It is fully on, or fully off, and nothing else.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'pwm50', label: 'Fully on, fully off' } },
    { text: 'Fully on it drops almost no voltage. Fully off it passes no current. Either way, almost no power lost.',
      scene: { kind: 'statement', lines: ['No voltage,', 'or no current'] } },
    { text: 'And in between the switching, an inductor and a capacitor store and release the energy.',
      scene: { kind: 'circuit', variant: 'regulator', flow: true, highlight: 'buck cout', label: 'Stored, then released' } },
    { text: 'The output is set by how long the switch spends on, which is a duty cycle, exactly like P W M.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'pwm25 avg', label: 'Duty cycle sets the output' } },
    { text: 'Efficiency of eighty five to ninety five percent is normal, where a linear regulator managed forty two.',
      scene: { kind: 'compare', left: 'Switching: 90%', right: 'Linear: 42%', caption: 'Stepping 12V down to 5V' } },
    { text: 'Three arrangements, and the names tell you what they do.',
      scene: { kind: 'statement', lines: ['Three names'] } },
    { text: 'A buck converter steps voltage down. Twelve volts in, five volts out, and very little wasted.',
      scene: { kind: 'formula', expr: 'buck: 12V → 5V' } },
    { text: 'A boost converter steps voltage up, which a linear regulator can never do at all.',
      scene: { kind: 'formula', expr: 'boost: 3.7V → 5V' } },
    { text: 'That is how a single lithium cell runs five volt electronics, and there is no linear equivalent.',
      scene: { kind: 'statement', lines: ['No linear part', 'can go up'] } },
    { text: 'And a buck boost does either, holding the output steady as a battery drains past it.',
      scene: { kind: 'statement', lines: ['Either way,', 'as it drains'] } },
    { text: 'So why does anybody still use a linear regulator?',
      scene: { kind: 'statement', lines: ['So why use', 'a linear one?'] } },
    { text: 'Because switching hundreds of thousands of times a second puts noise on everything.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'noise', label: 'The price of switching' } },
    { text: 'That noise lands on your output rail, and it radiates from the inductor into nearby circuits.',
      scene: { kind: 'statement', lines: ['It conducts,', 'and it radiates'] } },
    { text: 'A linear regulator is quiet, simple, and needs three parts. A switcher needs a layout you thought about.',
      scene: { kind: 'compare', left: 'Linear: quiet, hot', right: 'Switching: cool, noisy', caption: 'Choose by what the circuit minds' } },
    { text: 'So the rule of thumb. Big voltage drop, high current, or a battery, use a switcher.',
      scene: { kind: 'statement', lines: ['Big drop or', 'a battery: switch'] } },
    { text: 'Small drop, low current, or a sensitive analog rail, use a linear one and accept the heat.',
      scene: { kind: 'statement', lines: ['Small drop or', 'sensitive: linear'] } },
    { text: 'And plenty of real designs use both. A switcher to get close, then a small L D O to clean it up.',
      scene: { kind: 'statement', lines: ['Switch to get close.', 'Then clean it up.'] } },
    { text: 'One last thing, because a regulated rail is still not a clean rail at the far end of a wire.',
      scene: { kind: 'statement', lines: ['Regulated is', 'not clean'] } },
    { text: 'The regulator sits over there. Your chip is over here, and the track between them has resistance.',
      scene: { kind: 'statement', lines: ['The track', 'is not perfect'] } },
    { text: 'So you finish the job locally. A bulk capacitor near the regulator, for slow, large swings.',
      scene: { kind: 'circuit', variant: 'regulator', flow: true, highlight: 'cout', label: 'Bulk, at the regulator' } },
    { text: 'And a hundred nanofarad ceramic right at each chip’s power pins, for the fast spikes.',
      scene: { kind: 'formula', expr: '100nF, at every chip' } },
    { text: 'That is the whole chain. Rectify, smooth, regulate, then decouple where the current is actually drawn.',
      scene: { kind: 'statement', lines: ['Rectify. Smooth.', 'Regulate. Decouple.'] } },
    { text: 'Get that chain right and most of the mysterious faults in a build simply never happen.',
      scene: { kind: 'statement', lines: ['A good rail', 'prevents mysteries'] } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. A switching regulator is fully on or fully off, so it wastes almost nothing.',
      scene: { kind: 'recap', items: ['Switching wastes almost nothing'] } },
    { text: 'Two. Buck steps down, boost steps up, and only a switcher can step up at all.',
      scene: { kind: 'recap', items: ['Switching wastes almost nothing', 'Buck down, boost up, linear neither'] } },
    { text: 'Three. Switchers are noisy, so a quiet analog rail still wants a linear regulator and local decoupling.',
      scene: { kind: 'recap', items: ['Switching wastes almost nothing', 'Buck down, boost up, linear neither', 'Efficient is not the same as clean'] } },
    { text: 'Go and find the inductor on a phone charger board. That is a buck converter.',
      scene: { kind: 'outro' } },
  ],
};
