import type { LessonScript } from '../types';

/**
 * Unit 4, Meet the Arduino. Checkpoint for "Talking & Debugging".
 *
 * The board has no screen, so the learner has been debugging blind. This is the
 * film that hands them the one instrument software gives them, and it spends
 * real time on the two upload failures that stop people before they start.
 */
export const talkDebug: LessonScript = {
  id: 'talk-debug',
  title: 'Talking and Debugging',
  unitTitle: 'Meet the Arduino',
  unitId: 'arduino',
  skillId: 'talk-debug',
  skillTitle: 'Talking & Debugging',
  accent: '#f2b705',
  segments: [
    { text: 'Your board has no screen, so when a sketch misbehaves you cannot see what it is thinking.',
      scene: { kind: 'title' } },
    { text: 'Serial is how it talks back, and it turns guessing into reading.',
      scene: { kind: 'circuit', variant: 'board', flow: true, highlight: 'usb', label: 'It talks over the USB cable' } },
    { text: 'One line in setup opens the channel.',
      scene: { kind: 'formula', expr: 'Serial.begin(9600);' } },
    { text: 'Nine thousand six hundred is the baud rate, which is how many bits per second travel down the wire.',
      scene: { kind: 'statement', lines: ['Baud is bits', 'per second'] } },
    { text: 'The Serial Monitor on your computer has to be set to the same number.',
      scene: { kind: 'compare', left: 'Matched: text', right: 'Mismatched: gibberish', caption: 'Both ends agree, or neither works' } },
    { text: 'If your output is a screenful of strange symbols, that is the only fault it ever is.',
      scene: { kind: 'statement', lines: ['Symbols mean', 'the wrong baud'] } },
    { text: 'Then print from anywhere in your code.',
      scene: { kind: 'formula', expr: 'Serial.println(value);' } },
    { text: 'Println adds a new line at the end. Plain print does not, which is how you build one line from several pieces.',
      scene: { kind: 'compare', left: 'print: same line', right: 'println: new line', caption: 'The difference is the ln' } },
    { text: 'Now what to print, because this is where it becomes a real tool.',
      scene: { kind: 'statement', lines: ['What to print'] } },
    { text: 'Print the sensor value inside your loop and turn the knob, and you see the whole range scroll past.',
      scene: { kind: 'circuit', variant: 'divider', flow: true, highlight: 'pot tap', label: 'Watch a real value move' } },
    { text: 'Now you know your actual bright and dark numbers rather than the ones a tutorial guessed.',
      scene: { kind: 'statement', lines: ['Your numbers,', 'not a tutorial’s'] } },
    { text: 'Print inside an if branch and you learn whether the branch runs at all.',
      scene: { kind: 'statement', lines: ['Did it even', 'get here?'] } },
    { text: 'That question, did this code run, is most of debugging, and printing answers it in seconds.',
      scene: { kind: 'statement', lines: ['Most bugs are', 'that question'] } },
    { text: 'Now getting the sketch onto the board at all.',
      scene: { kind: 'statement', lines: ['Getting it', 'onto the board'] } },
    { text: 'Upload compiles your code, then sends it down the USB cable into the chip’s memory.',
      scene: { kind: 'circuit', variant: 'board', flow: true, highlight: 'usb mcu', label: 'Compile, then transfer' } },
    { text: 'You have to tell the software two things first. Which board, and which port.',
      scene: { kind: 'statement', lines: ['Which board.', 'Which port.'] } },
    { text: 'Pick the wrong board and the code compiles for a different chip, and nothing works.',
      scene: { kind: 'statement', lines: ['Wrong board,', 'wrong chip'] } },
    { text: 'And if it says no port found, there are only two real causes.',
      scene: { kind: 'compare', left: 'Wrong port picked', right: 'Charge-only cable', caption: 'It is nearly always one of these' } },
    { text: 'A USB cable that only carries power looks exactly like a good one, and it will never upload.',
      scene: { kind: 'statement', lines: ['Some cables', 'carry no data'] } },
    { text: 'Once it is uploaded it stays there. Unplug the computer and it keeps running from any power.',
      scene: { kind: 'circuit', variant: 'board', flow: true, highlight: 'power', label: 'It keeps running alone' } },
    { text: 'Last, the errors before you ever get that far.',
      scene: { kind: 'statement', lines: ['Errors first,', 'though'] } },
    { text: 'The two commonest are a missing semicolon at the end of a line, and a missing closing brace.',
      scene: { kind: 'formula', expr: 'digitalWrite(LED, HIGH);' } },
    { text: 'Nearly every statement ends in a semicolon, and the compiler will not guess for you.',
      scene: { kind: 'statement', lines: ['Every statement,', 'a semicolon'] } },
    { text: 'When you get twenty errors at once, read only the first one.',
      scene: { kind: 'statement', lines: ['Read only', 'the first'] } },
    { text: 'The rest are usually the compiler getting lost after the first mistake. Fix the top and most vanish.',
      scene: { kind: 'compare', left: 'Fix the first', right: 'Read all twenty', caption: 'One of these takes a minute' } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. Serial dot begin in setup, Serial dot println anywhere, and match the baud at both ends.',
      scene: { kind: 'recap', items: ['Serial is how the board talks back'] } },
    { text: 'Two. Choose the board and the port before uploading, and use a cable that carries data.',
      scene: { kind: 'recap', items: ['Serial is how the board talks back', 'Right board, right port, real cable'] } },
    { text: 'Three. Fix the first compile error and recompile, rather than reading the whole list.',
      scene: { kind: 'recap', items: ['Serial is how the board talks back', 'Right board, right port, real cable', 'Fix the first error first'] } },
    { text: 'Go and print something from inside a loop, and watch it move.',
      scene: { kind: 'outro' } },
  ],
};
