import type { LessonScript } from '../types';

/**
 * Unit 7, Transistors & Switching. Checkpoint for "The Transistor".
 *
 * The skill before "Driving Loads", so this film stays on the device itself:
 * what the three legs do, what beta actually promises, and why designing at the
 * exact minimum base current produces a switch that runs hot.
 */
export const theTransistor: LessonScript = {
  id: 'the-transistor',
  title: 'The Transistor',
  unitTitle: 'Transistors & Switching',
  unitId: 'transistors',
  skillId: 'the-transistor',
  skillTitle: 'The Transistor',
  accent: '#84cc30',
  segments: [
    { text: 'A transistor is a valve. A small effort at the handle controls a much larger flow.',
      scene: { kind: 'title' } },
    { text: 'The bipolar transistor has three legs, and each one has a job.',
      scene: { kind: 'circuit', variant: 'transistor', flow: false, label: 'Three legs, three jobs' } },
    { text: 'The base is the handle. A small current into it is what you control.',
      scene: { kind: 'circuit', variant: 'transistor', flow: false, highlight: 'base', label: 'Base: the handle' } },
    { text: 'The collector and the emitter are the pipe. The large current runs between them.',
      scene: { kind: 'circuit', variant: 'transistor', flow: true, highlight: 'load', label: 'Collector to emitter: the pipe' } },
    { text: 'The commonest type is called N P N, and the rule for it is one sentence.',
      scene: { kind: 'statement', lines: ['One rule'] } },
    { text: 'Collector current flows only while base current flows. No base current, nothing at all.',
      scene: { kind: 'compare', left: 'Base current: on', right: 'No base current: off', caption: 'There is no third option' } },
    { text: 'The base needs about nought point seven volts across it to conduct, like any silicon junction.',
      scene: { kind: 'formula', expr: 'Vbe ≈ 0.7V' } },
    { text: 'Below that it is simply off, and above it the current is set by whatever resistor you put there.',
      scene: { kind: 'circuit', variant: 'transistor', flow: true, highlight: 'baseresistor', label: 'The resistor sets the base current' } },
    { text: 'Now the number that ties the two currents together.',
      scene: { kind: 'statement', lines: ['One number', 'ties them'] } },
    { text: 'Current gain, written as beta, or as h F E on a datasheet.',
      scene: { kind: 'formula', expr: 'β = Ic / Ib' } },
    { text: 'Collector current divided by base current. One milliamp in, with a beta of a hundred, allows a hundred out.',
      scene: { kind: 'formula', expr: '1mA x 100 = 100mA' } },
    { text: 'Typical values run from about ten to three hundred, depending on the part.',
      scene: { kind: 'statement', lines: ['Ten to', 'three hundred'] } },
    { text: 'And here is the thing nobody tells you soon enough. Beta is not a reliable number.',
      scene: { kind: 'statement', lines: ['Beta is not', 'reliable'] } },
    { text: 'Two transistors from the same bag can differ by three times, and beta drifts with temperature.',
      scene: { kind: 'compare', left: 'β = 100', right: 'β = 300', caption: 'The same part number, the same bag' } },
    { text: 'So you never design for the typical beta. You design for the lowest one the datasheet allows.',
      scene: { kind: 'statement', lines: ['Design for', 'the minimum'] } },
    { text: 'Working backwards is the practical skill. You know your load current, and you want the base current.',
      scene: { kind: 'formula', expr: 'Ib = Ic / β' } },
    { text: 'A load needing one hundred and twenty milliamps, with a minimum beta of one hundred, needs one point two.',
      scene: { kind: 'formula', expr: '120mA / 100 = 1.2mA' } },
    { text: 'And then you deliberately give it more than that. Several times more.',
      scene: { kind: 'statement', lines: ['Then give it', 'more'] } },
    { text: 'To see why, look at the two states a switching transistor is supposed to live in.',
      scene: { kind: 'statement', lines: ['Two states,', 'and one trap'] } },
    { text: 'Cutoff is fully off. No base current, no collector current, and it behaves like an open switch.',
      scene: { kind: 'circuit', variant: 'transistor', flow: false, label: 'Cutoff: an open switch' } },
    { text: 'Saturation is fully on. It drops around nought point two volts and behaves like a closed switch.',
      scene: { kind: 'circuit', variant: 'transistor', flow: true, label: 'Saturation: a closed switch' } },
    { text: 'Between those two is the active region, where it is partly on, and that is where the heat lives.',
      scene: { kind: 'compare', left: 'Saturated: 0.2V', right: 'Partly on: 3V', caption: 'The voltage it drops across itself' } },
    { text: 'Three volts across it while a hundred milliamps flows through is nought point three watts, all as heat.',
      scene: { kind: 'formula', expr: '3V x 100mA = 0.3W' } },
    { text: 'In saturation the same load gives you two hundredths of a watt, and it stays cool.',
      scene: { kind: 'formula', expr: '0.2V x 100mA = 0.02W' } },
    { text: 'That is the whole reason you overdrive the base. Not to be safe, but to keep it out of the middle.',
      scene: { kind: 'statement', lines: ['Overdrive to', 'avoid the middle'] } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. Base current controls collector current, and the base needs nought point seven volts to start.',
      scene: { kind: 'recap', items: ['Base current lets collector current flow'] } },
    { text: 'Two. Beta is collector over base, and it scatters, so always design for the minimum.',
      scene: { kind: 'recap', items: ['Base current lets collector current flow', 'Design for the lowest beta'] } },
    { text: 'Three. As a switch, live in cutoff or saturation, because the region in between is a heater.',
      scene: { kind: 'recap', items: ['Base current lets collector current flow', 'Design for the lowest beta', 'Cutoff or saturation, never between'] } },
    { text: 'Go and feel a transistor driven at exactly its minimum base current. Then overdrive it.',
      scene: { kind: 'outro' } },
  ],
};
