import type { LessonScript } from '../types';

/**
 * Unit 6, Capacitors, RC & Timing. Checkpoint for "Timing & the 555".
 *
 * The first skill that asks a learner to CHOOSE between hardware and code, so
 * the film spends its last third on that choice rather than on more arithmetic.
 * The 555 is taught as a capacitor watcher, because that is all it is.
 */
export const timing555: LessonScript = {
  id: 'timing-555',
  title: 'Timing and the 555',
  unitTitle: 'Capacitors, RC & Timing',
  unitId: 'capacitors-rc',
  skillId: 'timing-555',
  skillTitle: 'Timing & the 555',
  accent: '#549cf0',
  segments: [
    { text: 'You know that a capacitor charges on a curve. Now we make that curve do a job.',
      scene: { kind: 'title' } },
    { text: 'A charging capacitor crosses any chosen voltage at a completely predictable moment.',
      scene: { kind: 'plot', upTo: 0.63, marker: 'It crosses here, every time' } },
    { text: 'So put something that reacts at a threshold on the other end and you have a timer.',
      scene: { kind: 'circuit', variant: 'rc', flow: true, label: 'A resistor, a capacitor, a delay' } },
    { text: 'The time constant is the resistance times the capacitance, and it comes out in seconds.',
      scene: { kind: 'formula', expr: 'τ = R x C' } },
    { text: 'One hundred kilohms and one microfarad gives a tenth of a second.',
      scene: { kind: 'formula', expr: '100kΩ x 1µF = 0.1s' } },
    { text: 'Fifty kilohms and the same capacitor gives you half of that.',
      scene: { kind: 'formula', expr: '50kΩ x 1µF = 0.05s' } },
    { text: 'That is exactly the range a hardware button debounce lives in, and it is one real use of RC timing.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'bounce', label: 'The bounce RC smooths away' } },
    { text: 'The capacitor cannot change its voltage fast enough to follow the bouncing, so the edge comes out clean.',
      scene: { kind: 'statement', lines: ['Too slow to', 'follow the bounce'] } },
    { text: 'Now, you have an Arduino. Why not just time it in code?',
      scene: { kind: 'statement', lines: ['Why not just', 'use code?'] } },
    { text: 'Often you should. A delay in code is a number you edit, and RC timing is a part you unsolder.',
      scene: { kind: 'compare', left: 'Edit a number', right: 'Change a part', caption: 'Which one you will do ten times' } },
    { text: 'Code timing is also precise, adjustable at runtime, and something you can print over serial.',
      scene: { kind: 'statement', lines: ['Precise.', 'Adjustable.', 'Visible.'] } },
    { text: 'But RC timing still runs the things code cannot reach.',
      scene: { kind: 'statement', lines: ['Some things code', 'cannot reach'] } },
    { text: 'Filter cutoffs, fade rates, hardware debounce, and the timing inside analog chips.',
      scene: { kind: 'circuit', variant: 'bode', highlight: 'lowpass', label: 'A filter is RC timing' } },
    { text: 'And the most famous of those chips is the 555.',
      scene: { kind: 'statement', lines: ['The 555'] } },
    { text: 'It is a timer in an eight pin package, and it has been made since nineteen seventy two.',
      scene: { kind: 'statement', lines: ['Eight pins,', 'and fifty years'] } },
    { text: 'What it does is simple. It watches a capacitor charge and discharge between two internal thresholds.',
      scene: { kind: 'circuit', variant: 'rc', flow: true, highlight: 'resistor', label: 'The 555 just watches this' } },
    { text: 'One third of the supply, and two thirds of the supply. Those are the two lines it looks for.',
      scene: { kind: 'formula', expr: 'thresholds at 1/3 and 2/3' } },
    { text: 'Cross the top one and it flips its output low. Cross the bottom one and it flips high again.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'square', label: 'The output it produces' } },
    { text: 'That gives you two modes, and they are the only two you need.',
      scene: { kind: 'statement', lines: ['Two modes'] } },
    { text: 'Monostable produces one pulse of a fixed length each time you trigger it. A one shot.',
      scene: { kind: 'compare', left: 'Monostable: one pulse', right: 'Astable: forever', caption: 'Triggered, or free running' } },
    { text: 'Astable free runs, producing a square wave with no trigger at all. A blinker, or a tone.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'square', label: 'Astable: a free running square wave' } },
    { text: 'And in both, the timing is set by the external resistor and capacitor you choose.',
      scene: { kind: 'statement', lines: ['You choose', 'R and C'] } },
    { text: 'For an astable, each phase lasts roughly nought point seven times R times C.',
      scene: { kind: 'formula', expr: 't ≈ 0.7 x R x C' } },
    { text: 'Forty seven kilohms and ten microfarads gives about a third of a second per phase.',
      scene: { kind: 'formula', expr: '0.7 x 47kΩ x 10µF = 0.33s' } },
    { text: 'So when do you choose the chip over the board? When the timing is fixed and nothing else has to happen.',
      scene: { kind: 'compare', left: '555: fixed and cheap', right: 'Arduino: changing and logged', caption: 'Pick by what the job needs' } },
    { text: 'A 555 costs pennies, needs no code, and will not stop working because of a firmware bug.',
      scene: { kind: 'statement', lines: ['No code means', 'no code bugs'] } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. RC timing is a curve crossing a threshold, and tau equals R times C.',
      scene: { kind: 'recap', items: ['A curve crossing a threshold'] } },
    { text: 'Two. Time in code when the number will change, and in hardware when it will not.',
      scene: { kind: 'recap', items: ['A curve crossing a threshold', 'Code for changing, RC for fixed'] } },
    { text: 'Three. The 555 watches a capacitor between one third and two thirds, and your R and C set the rate.',
      scene: { kind: 'recap', items: ['A curve crossing a threshold', 'Code for changing, RC for fixed', 'The 555 watches your capacitor'] } },
    { text: 'Go and work out the parts for a one second blink, then check it against a stopwatch.',
      scene: { kind: 'outro' } },
  ],
};
