import type { LessonScript } from '../types';

/**
 * Unit 7, Transistors & Switching. Checkpoint for "Transistor Variety".
 *
 * A choosing film rather than a mechanism film. It is deliberately blunt about
 * the two traps: a non logic level MOSFET that never fully turns on from 5V,
 * and a PNP whose base cannot be driven from a 5V pin when the load runs at 12.
 */
export const transistorVariety: LessonScript = {
  id: 'transistor-variety',
  title: 'Choosing a Switch',
  unitTitle: 'Transistors & Switching',
  unitId: 'transistors',
  skillId: 'transistor-variety',
  skillTitle: 'Transistor Variety',
  accent: '#84cc30',
  segments: [
    { text: 'You have used one transistor for everything so far. There are three more you should know.',
      scene: { kind: 'title' } },
    { text: 'Start with the biggest difference, which is what the control terminal actually wants.',
      scene: { kind: 'circuit', variant: 'transistor', flow: true, highlight: 'base', label: 'A BJT wants current' } },
    { text: 'A bipolar transistor is controlled by base current. It takes real current, continuously, to hold it on.',
      scene: { kind: 'statement', lines: ['Current in,', 'the whole time'] } },
    { text: 'A MOSFET is controlled by gate voltage, and once the gate is charged it takes almost nothing.',
      scene: { kind: 'compare', left: 'BJT: base current', right: 'MOSFET: gate voltage', caption: 'The control costs you differently' } },
    { text: 'Its three terminals are the gate, the drain and the source, matching base, collector and emitter.',
      scene: { kind: 'statement', lines: ['Gate, drain,', 'source'] } },
    { text: 'The second difference is what it costs you when it is on.',
      scene: { kind: 'statement', lines: ['What it costs', 'when on'] } },
    { text: 'A saturated bipolar drops about nought point two volts, and that drop does not get smaller.',
      scene: { kind: 'formula', expr: '0.2V x 5A = 1W of heat' } },
    { text: 'A MOSFET behaves like a small resistance instead, often a few hundredths of an ohm.',
      scene: { kind: 'formula', expr: '0.02Ω x 5A = 0.1V' } },
    { text: 'And its heat rises with the square of the current, so at five amps it dissipates half a watt, not five.',
      scene: { kind: 'formula', expr: 'P = I² x Rds' } },
    { text: 'Which is why anything switching amps rather than milliamps is a MOSFET now.',
      scene: { kind: 'statement', lines: ['Amps means', 'MOSFET'] } },
    { text: 'But there is a trap, and it is the commonest MOSFET mistake there is.',
      scene: { kind: 'statement', lines: ['The MOSFET trap'] } },
    { text: 'Most MOSFETs need ten volts on the gate to turn fully on. Your pin gives five.',
      scene: { kind: 'compare', left: 'Needs 10V', right: 'Pin gives 5V', caption: 'Partly on, and getting hot' } },
    { text: 'At five volts it sits half on, drops real voltage, and cooks itself while appearing to work.',
      scene: { kind: 'statement', lines: ['It works.', 'Then it does not.'] } },
    { text: 'So look for the words logic level. Those parts are specified to turn fully on at five volts or less.',
      scene: { kind: 'statement', lines: ['Look for', 'logic level'] } },
    { text: 'Now the other axis, which is which way round the device is.',
      scene: { kind: 'statement', lines: ['The other axis'] } },
    { text: 'Everything you have built so far is an N P N, and it turns on when the base goes high.',
      scene: { kind: 'circuit', variant: 'transistor', flow: true, label: 'NPN: base high turns it on' } },
    { text: 'It sits between the load and ground, which is called low side switching.',
      scene: { kind: 'statement', lines: ['Between the load', 'and ground'] } },
    { text: 'A P N P is its mirror image. It turns on when the base is pulled low, below its emitter.',
      scene: { kind: 'compare', left: 'NPN: base HIGH', right: 'PNP: base LOW', caption: 'Mirror images, in every respect' } },
    { text: 'And it sits between the supply and the load, which is high side switching.',
      scene: { kind: 'statement', lines: ['Between the supply', 'and the load'] } },
    { text: 'Low side is easier, because the base is referenced to the same ground your pin is.',
      scene: { kind: 'statement', lines: ['Same ground,', 'easy drive'] } },
    { text: 'High side is harder for exactly that reason, and here is the trap it hides.',
      scene: { kind: 'statement', lines: ['The high side', 'trap'] } },
    { text: 'To turn off a P N P on a twelve volt rail, the base has to be pulled up to twelve volts.',
      scene: { kind: 'compare', left: 'Base must reach 12V', right: 'Pin only reaches 5V', caption: 'So it never fully turns off' } },
    { text: 'A five volt pin cannot do that, so the P N P stays partly on and your load never quite switches off.',
      scene: { kind: 'statement', lines: ['Partly on,', 'permanently'] } },
    { text: 'The usual answer is a small N P N driving the P N P, so the pin only ever talks to ground level.',
      scene: { kind: 'statement', lines: ['An NPN to', 'drive the PNP'] } },
    { text: 'And whichever you choose, an inductive load still needs its flyback diode. That rule is about the load.',
      scene: { kind: 'circuit', variant: 'flyback', flow: true, highlight: 'diode', label: 'Still needed, every time' } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. A BJT is driven by current, a MOSFET by voltage, and MOSFETs win above about half an amp.',
      scene: { kind: 'recap', items: ['BJT current, MOSFET voltage'] } },
    { text: 'Two. From a five volt pin you need a logic level MOSFET, or it never fully turns on.',
      scene: { kind: 'recap', items: ['BJT current, MOSFET voltage', 'Logic level, or it half turns on'] } },
    { text: 'Three. N P N switches the low side and is easy. High side needs a P N P and a driver.',
      scene: { kind: 'recap', items: ['BJT current, MOSFET voltage', 'Logic level, or it half turns on', 'Low side is easy, high side is not'] } },
    { text: 'Go and read the gate threshold voltage on a MOSFET datasheet before you buy one.',
      scene: { kind: 'outro' } },
  ],
};
