import type { LessonScript } from '../types';

/**
 * Unit 3, Sensors & Signals. Checkpoint for "Variable Resistance".
 *
 * Three components that are really one idea, a resistor the world is allowed to
 * change. The film keeps them together on purpose so a learner meets the fourth
 * one, whatever it turns out to be, already knowing how to read it.
 */
export const variableResistance: LessonScript = {
  id: 'variable-resistance',
  title: 'Variable Resistance',
  unitTitle: 'Sensors & Signals',
  unitId: 'sensors',
  skillId: 'variable-resistance',
  skillTitle: 'Variable Resistance',
  accent: '#84cc30',
  segments: [
    { text: 'A sensor sounds like a complicated thing. Most of the ones in your kit are a resistor that changes.',
      scene: { kind: 'title' } },
    { text: 'Start with the one you change by hand. A potentiometer, or pot.',
      scene: { kind: 'circuit', variant: 'divider', flow: true, highlight: 'pot', label: 'A resistor you can turn' } },
    { text: 'Inside is a track of resistive material and a sliding contact called the wiper.',
      scene: { kind: 'statement', lines: ['A track,', 'and a wiper'] } },
    { text: 'It has three legs. The two ends of the track, and the wiper in the middle.',
      scene: { kind: 'statement', lines: ['Three legs,', 'not two'] } },
    { text: 'Turn the shaft and the wiper moves, so the resistance from the wiper to each end changes.',
      scene: { kind: 'circuit', variant: 'divider', flow: true, highlight: 'pot tap', label: 'Turning moves the tap' } },
    { text: 'Wire both ends across your supply and you have built a voltage divider you can turn.',
      scene: { kind: 'statement', lines: ['A divider', 'with a knob'] } },
    { text: 'Halfway round a ten kilohm pot on five volts, the wiper sits at two point five volts.',
      scene: { kind: 'formula', expr: 'halfway = 2.5V of 5V' } },
    { text: 'A quarter of the way gives you one point two five. The wiper voltage tracks the position.',
      scene: { kind: 'formula', expr: 'a quarter = 1.25V' } },
    { text: 'That is what a volume knob is, and what a brightness dial is, and how you set a threshold by hand.',
      scene: { kind: 'statement', lines: ['Volume, brightness,', 'threshold'] } },
    { text: 'Now the same idea, but with light doing the turning instead of your fingers.',
      scene: { kind: 'statement', lines: ['Now let light', 'turn it'] } },
    { text: 'A light dependent resistor, or LDR. Also called a photoresistor.',
      scene: { kind: 'circuit', variant: 'divider', flow: true, highlight: 'ldr', label: 'The LDR' } },
    { text: 'Its face is a semiconductor, usually cadmium sulfide, in a wiggly track under a clear window.',
      scene: { kind: 'statement', lines: ['A semiconductor', 'under a window'] } },
    { text: 'Light landing on it frees charge carriers in the material, so the resistance falls.',
      scene: { kind: 'statement', lines: ['More light,', 'less resistance'] } },
    { text: 'The numbers are dramatic. Bright room light might give one kilohm. A hand over it gives two hundred.',
      scene: { kind: 'compare', left: 'Bright: 1kΩ', right: 'Dark: 200kΩ', caption: 'Two hundred times, from a shadow' } },
    { text: 'It has no polarity, because it is just a resistor. Either leg can face either way.',
      scene: { kind: 'statement', lines: ['No polarity.', 'It is a resistor.'] } },
    { text: 'And it is slow, in electronics terms. Tens of milliseconds to settle after a change.',
      scene: { kind: 'statement', lines: ['Slow, but fast', 'enough for light'] } },
    { text: 'The third one swaps light for heat. A thermistor.',
      scene: { kind: 'circuit', variant: 'divider', flow: true, highlight: 'r1', label: 'The thermistor' } },
    { text: 'The common type is called N T C, for negative temperature coefficient.',
      scene: { kind: 'statement', lines: ['NTC: negative', 'coefficient'] } },
    { text: 'Negative means the resistance goes down as it gets hotter, which is the opposite of a plain wire.',
      scene: { kind: 'compare', left: 'NTC: hotter, lower', right: 'PTC: hotter, higher', caption: 'The two families' } },
    { text: 'A ten kilohm N T C reads ten kilohms at twenty five degrees, and about five when you warm it in your fingers.',
      scene: { kind: 'formula', expr: '10kΩ cold → 5kΩ warm' } },
    { text: 'It is not a straight line, though. The resistance falls exponentially with temperature.',
      scene: { kind: 'statement', lines: ['Not linear.', 'Exponential.'] } },
    { text: 'So turning a thermistor reading into actual degrees takes a curve, not a simple multiplication.',
      scene: { kind: 'statement', lines: ['Degrees need', 'a curve'] } },
    { text: 'Three components, one pattern. Something in the world sets a resistance.',
      scene: { kind: 'statement', lines: ['One pattern,', 'three parts'] } },
    { text: 'And every one of them is read the same way, by putting it in a divider and reading the middle.',
      scene: { kind: 'circuit', variant: 'divider', flow: true, highlight: 'ldr tap', label: 'Read the middle' } },
    { text: 'Which means when you meet a force sensor, or a moisture probe, you already know what to do with it.',
      scene: { kind: 'statement', lines: ['The next one', 'is the same'] } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. A pot is a divider with a knob, and the wiper voltage follows the position.',
      scene: { kind: 'recap', items: ['A pot is a divider you can turn'] } },
    { text: 'Two. An LDR falls in resistance with light, from kilohms bright to hundreds of kilohms dark.',
      scene: { kind: 'recap', items: ['A pot is a divider you can turn', 'Light lowers an LDR, hugely'] } },
    { text: 'Three. An N T C thermistor falls with heat, on a curve rather than a straight line.',
      scene: { kind: 'recap', items: ['A pot is a divider you can turn', 'Light lowers an LDR, hugely', 'NTC falls with heat, on a curve'] } },
    { text: 'Go and measure an LDR with your meter, in the light and under your hand.',
      scene: { kind: 'outro' } },
  ],
};
