import type { LessonScript } from '../types';

/**
 * Unit 11, Digital Logic & Embedded. Sits at the checkpoint for "Interrupts and
 * volatile".
 *
 * Chosen for video because the bug this teaches is invisible by construction. A
 * torn read happens between two machine instructions on a working chip running
 * correct-looking C, and the only way to see it is to watch the four bytes go
 * across one at a time while an interrupt lands in the middle. A quiz can state
 * that `volatile` is not atomicity. Watching half an old number joined to half a
 * new one is what makes it stick.
 */
export const volatileAndIsrs: LessonScript = {
  id: 'volatile-and-isrs',
  title: 'Interrupts and volatile',
  unitTitle: 'Digital Logic & Embedded',
  unitId: 'digital-logic',
  skillId: 'volatile-and-isrs',
  skillTitle: 'Interrupts and volatile',
  accent: '#549cf0',
  segments: [
    { text: 'An interrupt is the hardware telling your program to stop what it is doing, right now.',
      scene: { kind: 'title' } },
    { text: 'A pin changes. A timer expires. A byte arrives. The processor drops your code mid-flow and runs a handler.',
      scene: { kind: 'circuit', variant: 'board', flow: true, highlight: 'pin', label: 'A pin changes' } },
    { text: 'Then it goes back to exactly the instruction it left, as if nothing happened.',
      scene: { kind: 'statement', lines: ['Stop.', 'Handle it.', 'Carry on.'] } },
    { text: 'The alternative is polling. Asking, over and over, whether the thing has happened yet.',
      scene: { kind: 'compare', left: 'Poll: you keep asking', right: 'Interrupt: it tells you', caption: 'Two ways to notice' } },
    { text: 'Polling a slow thing is fine. Polling a fast one means you will miss it between two of your own questions.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'bounce', label: 'Faster than your loop' } },
    { text: 'Latency is the delay between the event and the first instruction of your handler running.',
      scene: { kind: 'statement', lines: ['Latency:', 'event to handler'] } },
    { text: 'It is never zero. The processor has to finish the current instruction and save its state first.',
      scene: { kind: 'statement', lines: ['Never zero.', 'Always bounded.'] } },
    { text: 'Now the part that catches everybody. The compiler does not know your interrupt exists.',
      scene: { kind: 'statement', lines: ['The compiler', 'does not know'] } },
    { text: 'It optimises by assuming a variable only changes when it can see code that changes it.',
      scene: { kind: 'compare', left: 'What you wrote', right: 'What it compiled', caption: 'The compiler is allowed to assume' } },
    { text: 'So a loop that reads a flag, and never writes it, gets the read hoisted out of the loop entirely.',
      scene: { kind: 'statement', lines: ['Read it once.', 'Reuse it forever.'] } },
    { text: 'The flag is in a register now. Your interrupt sets the one in memory. The loop never looks again.',
      scene: { kind: 'circuit', variant: 'board', flow: false, highlight: 'chip', label: 'Reading a stale copy' } },
    { text: 'Your program hangs, on correct-looking C, at any optimisation level above none.',
      scene: { kind: 'statement', lines: ['Correct code.', 'Wrong result.'] } },
    { text: 'Volatile is how you tell the compiler to stop assuming. Read it from memory every single time.',
      scene: { kind: 'formula', expr: 'volatile bool flag;', note: 'Read it fresh, write it through, never reorder it' } },
    { text: 'Any variable shared between an interrupt and your main code is volatile. No exceptions.',
      scene: { kind: 'statement', lines: ['Shared with an ISR', 'means volatile'] } },
    { text: 'And now the thing that catches people who already know all of that.',
      scene: { kind: 'statement', lines: ['Volatile is', 'not enough'] } },
    { text: 'Volatile is about visibility. It says nothing whatsoever about atomicity.',
      scene: { kind: 'compare', left: 'Volatile: you will see it', right: 'Atomic: all or nothing', caption: 'Two different promises' } },
    { text: 'The A T mega three two eight is an eight bit processor. It moves eight bits at a time.',
      scene: { kind: 'circuit', variant: 'board', flow: false, label: 'Eight bits at a time' } },
    { text: 'A thirty two bit counter is not one read. It is four, one byte after another.',
      scene: { kind: 'statement', lines: ['One line of C.', 'Four instructions.'] } },
    { text: 'Say a timer interrupt increments that counter, and it is about to roll from two five five to two five six.',
      scene: { kind: 'statement', lines: ['255', 'about to become', '256'] } },
    { text: 'Your main code reads the low byte. Two five five. Then the interrupt fires.',
      scene: { kind: 'circuit', variant: 'wave', highlight: 'bounce', label: 'The interrupt lands mid-read' } },
    { text: 'The handler increments the whole counter. Low byte to zero, next byte to one. Then it returns.',
      scene: { kind: 'statement', lines: ['Low byte: 0', 'Next byte: 1'] } },
    { text: 'Your code carries on and reads the remaining three bytes. It gets the new ones.',
      scene: { kind: 'compare', left: 'Low byte: old', right: 'High bytes: new', caption: 'A number that never existed' } },
    { text: 'The value you now hold is five one one. Not two five five, not two five six. A number that was never in that variable.',
      scene: { kind: 'formula', expr: '255 + 256 = 511', note: 'Half of one reading joined to half of another' } },
    { text: 'That is a torn read, and volatile does nothing at all to prevent it.',
      scene: { kind: 'statement', lines: ['A torn read'] } },
    { text: 'The fix is to make the read indivisible. Turn interrupts off, take a copy, turn them back on.',
      scene: { kind: 'formula', expr: 'noInterrupts(); c = count; interrupts();', note: 'Three lines, and the tear cannot happen' } },
    { text: 'Keep that window as short as you possibly can. Every cycle with interrupts off is a cycle of added latency.',
      scene: { kind: 'statement', lines: ['Copy it out.', 'Nothing else.'] } },
    { text: 'Which points at the rule for handlers generally. Do almost nothing inside one.',
      scene: { kind: 'compare', left: 'In the handler: set a flag', right: 'In the loop: do the work', caption: 'Where the work belongs' } },
    { text: 'No printing. No delays. No waiting on anything. Set a flag or copy one value, and get out.',
      scene: { kind: 'statement', lines: ['Get in.', 'Get out.'] } },
    { text: 'When more has to come out than a flag can carry, use a ring buffer with the head and tail owned by different sides.',
      scene: { kind: 'compare', left: 'ISR writes the head', right: 'Loop moves the tail', caption: 'One writer each, no lock needed' } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. Anything shared with an interrupt is volatile, every time.',
      scene: { kind: 'recap', items: ['Shared means volatile'] } },
    { text: 'Two. Volatile stops the stale copy. It does not make anything atomic.',
      scene: { kind: 'recap', items: ['Shared means volatile', 'Volatile is not atomic'] } },
    { text: 'Three. Anything wider than the processor needs the interrupts off around it.',
      scene: { kind: 'recap', items: ['Shared means volatile', 'Volatile is not atomic', 'Guard multi-byte reads'] } },
    { text: 'Go and find a variable in your own code that an interrupt writes, and check what it is declared as.',
      scene: { kind: 'outro' } },
  ],
};
