import type { LessonScript } from '../types';

/**
 * Unit 4, Meet the Arduino. Checkpoint for "What an Arduino Is".
 *
 * The film a learner watches at the moment software enters a course that has so
 * far been entirely physical. It keeps the frame from unit three, sense decide
 * act, so the board arrives as a replacement for the decide stage rather than
 * as a new subject.
 */
export const whatArduino: LessonScript = {
  id: 'what-arduino',
  title: 'What an Arduino Is',
  unitTitle: 'Meet the Arduino',
  unitId: 'arduino',
  skillId: 'what-arduino',
  skillTitle: 'What an Arduino Is',
  accent: '#f2b705',
  segments: [
    { text: 'An Arduino is not a computer in the sense you are used to. It has no screen and no keyboard.',
      scene: { kind: 'title' } },
    { text: 'It is a board built around a microcontroller, which is a whole small computer on one chip.',
      scene: { kind: 'circuit', variant: 'board', flow: false, highlight: 'mcu', label: 'One chip, one computer' } },
    { text: 'Processor, memory and input output, all in the black rectangle in the middle.',
      scene: { kind: 'statement', lines: ['Processor, memory,', 'and pins'] } },
    { text: 'What it does is read its pins, run the program you gave it, and set its pins.',
      scene: { kind: 'statement', lines: ['Read pins.', 'Run code.', 'Set pins.'] } },
    { text: 'Which is exactly the pattern you already know. Sense, decide, act.',
      scene: { kind: 'statement', lines: ['Sense, decide,', 'act, again'] } },
    { text: 'The difference is that decide is now something you write, and can change in ten seconds.',
      scene: { kind: 'compare', left: 'Rewire it', right: 'Reprogram it', caption: 'The same change, two costs' } },
    { text: 'The program is called a sketch, and it lives in the board’s own memory.',
      scene: { kind: 'statement', lines: ['The program is', 'called a sketch'] } },
    { text: 'So once you have uploaded it, you can unplug your laptop entirely and it keeps running.',
      scene: { kind: 'circuit', variant: 'board', flow: true, highlight: 'usb', label: 'Upload, then unplug' } },
    { text: 'Power it from a battery or a wall adapter and it does its job with no computer anywhere near it.',
      scene: { kind: 'circuit', variant: 'board', flow: true, highlight: 'power', label: 'It runs on its own' } },
    { text: 'Now the pins, because that is the part your circuit touches.',
      scene: { kind: 'circuit', variant: 'board', flow: false, label: 'The pins are the interface' } },
    { text: 'Along one long edge, the digital pins, numbered nought to thirteen.',
      scene: { kind: 'circuit', variant: 'board', flow: false, highlight: 'digital', label: 'Digital, 0 to 13' } },
    { text: 'A digital pin has exactly two states. High, which is five volts, or low, which is nought.',
      scene: { kind: 'formula', expr: 'HIGH = 5V, LOW = 0V' } },
    { text: 'Nothing in between. If you need in between, you are on the wrong row of pins.',
      scene: { kind: 'statement', lines: ['Two states.', 'No middle.'] } },
    { text: 'Along the other edge, six analog inputs, labelled A nought to A five.',
      scene: { kind: 'circuit', variant: 'board', flow: false, highlight: 'analog', label: 'Analog in, A0 to A5' } },
    { text: 'These measure a voltage anywhere between nought and five volts, which is what a sensor gives you.',
      scene: { kind: 'circuit', variant: 'divider', flow: true, highlight: 'tap', label: 'A sensor lands here' } },
    { text: 'And beside them the power pins. Five volts, three point three volts, and ground.',
      scene: { kind: 'circuit', variant: 'board', flow: false, highlight: 'power', label: 'Five volts, and ground' } },
    { text: 'Ground is the one people forget, and it is the one that stops everything working.',
      scene: { kind: 'statement', lines: ['Do not forget', 'the ground'] } },
    { text: 'Your circuit and the board must share a ground, or they do not agree on what nought volts means.',
      scene: { kind: 'statement', lines: ['A shared zero,', 'or no agreement'] } },
    { text: 'One warning about those pins, and it is the expensive one.',
      scene: { kind: 'statement', lines: ['One warning'] } },
    { text: 'A pin will give you about twenty milliamps safely. That is an LED, and not much else.',
      scene: { kind: 'formula', expr: '20mA per pin, safely' } },
    { text: 'A motor, a relay coil, a strip of LEDs, all of those need a transistor between the pin and the load.',
      scene: { kind: 'circuit', variant: 'transistor', flow: true, highlight: 'load', label: 'Bigger loads need help' } },
    { text: 'And a sketch always has the same two parts, whatever it does.',
      scene: { kind: 'statement', lines: ['Two parts,', 'always'] } },
    { text: 'Setup runs once when the board powers up. That is where you say which pins are which.',
      scene: { kind: 'formula', expr: 'setup() runs once' } },
    { text: 'Loop then runs over and over, for as long as it has power, thousands of times a second.',
      scene: { kind: 'formula', expr: 'loop() runs forever' } },
    { text: 'There is no end. When loop finishes, it simply starts again.',
      scene: { kind: 'statement', lines: ['It never', 'finishes'] } },
    { text: 'Three things to take with you.',
      scene: { kind: 'recap', items: [] } },
    { text: 'One. It reads pins, runs your sketch, and drives pins, with no screen involved.',
      scene: { kind: 'recap', items: ['Read pins, run code, drive pins'] } },
    { text: 'Two. Digital pins are high or low only, analog inputs read the whole range, and grounds must be shared.',
      scene: { kind: 'recap', items: ['Read pins, run code, drive pins', 'Digital is two states, analog is a range'] } },
    { text: 'Three. Setup runs once, loop runs forever, and a pin gives you twenty milliamps.',
      scene: { kind: 'recap', items: ['Read pins, run code, drive pins', 'Digital is two states, analog is a range', 'setup once, loop forever, 20mA'] } },
    { text: 'Go and find the built in LED on pin thirteen. It is your first output.',
      scene: { kind: 'outro' } },
  ],
};
