#!/usr/bin/env node
// Regenerate content/films.json from what is actually in the bucket.
//
// The film index used to be inferred: every skill that was not a review or a
// gateway was assumed to have a film. True on the day the films were rendered,
// false the moment six skills were authored on 2026-08-28. The index claimed 49
// and the bucket held 43, so Labs drew a play button on six skills whose film
// does not exist, and pressing it signed a URL for a missing object.
//
// An inference about the contents of a bucket is a guess. This asks.
//
// A skill counts as filmed only when BOTH renders, a poster and captions are
// present. A half-uploaded film is a play button that opens a broken player,
// which is the same defect in a smaller costume.
//
// Run after rendering and uploading films:
//   node frontend/scripts/sync-films.mjs
// Then re-run the curriculum export, which stamps `hasFilm` onto every skill.
//
// Needs gcloud auth. It is deliberately NOT part of `npm run check`: CI has no
// credentials for the bucket, and a check that cannot run is a check that gets
// deleted. check-films.mjs is the CI-safe half.
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const FRONTEND = dirname(dirname(fileURLToPath(import.meta.url)));
const REPO = resolve(FRONTEND, '..');
const BUCKET = 'ohmlet-app-lessons';
const VERSION = 'v1';

const listing = (() => {
  try {
    return execFileSync('gsutil', ['ls', `gs://${BUCKET}/${VERSION}/**`], {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'pipe'],
    }).split('\n').filter(Boolean);
  } catch (err) {
    console.error(`sync-films: could not list gs://${BUCKET}/${VERSION}.`);
    console.error('Check `gcloud auth list` and that the ohmlet configuration is active.');
    console.error(String(err.stderr || err.message).trim().split('\n').slice(0, 3).join('\n'));
    process.exit(1);
  }
})();

/** skill id -> the file names under it. */
const bySkill = new Map();
for (const path of listing) {
  const tail = path.split(`/${VERSION}/`)[1];
  if (!tail) continue;
  const seg = tail.split('/');
  if (seg.length < 2) continue;
  if (!bySkill.has(seg[0])) bySkill.set(seg[0], new Set());
  bySkill.get(seg[0]).add(seg[seg.length - 1]);
}

const complete = [];
const partial = [];
for (const [id, files] of [...bySkill].sort(([a], [b]) => a.localeCompare(b))) {
  const f = [...files];
  const renders = f.filter((n) => n.endsWith('.mp4'));
  const poster = f.some((n) => /\.(jpg|jpeg|png|webp)$/.test(n));
  const captions = f.some((n) => n.endsWith('.vtt'));
  if (renders.length >= 2 && poster && captions) complete.push(id);
  else partial.push({ id, missing: [
    renders.length < 2 ? `${2 - renders.length} render(s)` : null,
    poster ? null : 'poster',
    captions ? null : 'captions',
  ].filter(Boolean) });
}

const out = resolve(REPO, 'content/films.json');
const before = (() => {
  try { return JSON.parse(readFileSync(out, 'utf8')).skills ?? []; } catch { return []; }
})();

writeFileSync(out, `${JSON.stringify({
  note: 'Skills with a rendered lesson film in gs://ohmlet-app-lessons. Generated by frontend/scripts/sync-films.mjs; do not hand-edit.',
  bucket: BUCKET,
  version: VERSION,
  skills: complete,
}, null, 2)}\n`);

// The TS twin, so the web bundle carries the same list and the parity check
// between web and backend holds by construction rather than by discipline.
writeFileSync(resolve(FRONTEND, 'components/ohmlet/data/films.ts'),
  `// GENERATED by frontend/scripts/sync-films.mjs from what is in the bucket.
// Do not hand-edit: the next sync overwrites it.
//
// This exists so that ONE list answers "which skills have a film" on every
// surface. Three places used to answer it independently, all by guessing "not a
// review and not a gateway", and all three were wrong together the moment six
// skills were authored without films: Labs drew a play button on all six and
// pressing it signed a URL for an object that is not there.
//
// curriculum.ts stamps \`hasFilm\` from this while building SESSION_CURRICULUM, so
// the web bundle carries it, the export carries it to the backend, and the two
// cannot disagree.

export const FILMED_SKILLS: ReadonlySet<string> = new Set([
${complete.map((id) => `  '${id}',\n`).join('')}]);
`);

const added = complete.filter((id) => !before.includes(id));
const gone = before.filter((id) => !complete.includes(id));

console.log(`sync-films: ${complete.length} complete film(s) in gs://${BUCKET}/${VERSION}`);
if (added.length) console.log(`  added:   ${added.join(', ')}`);
if (gone.length) console.log(`  removed: ${gone.join(', ')}`);
if (partial.length) {
  console.log(`\n  ${partial.length} skill folder(s) are incomplete and are NOT listed as filmed:`);
  for (const p of partial) console.log(`    ${p.id.padEnd(24)} missing ${p.missing.join(', ')}`);
}
console.log('\nNow run: node frontend/scripts/export-curriculum.mjs');
