// GENERATED by frontend/scripts/sync-films.mjs from what is in the bucket.
// Do not hand-edit: the next sync overwrites it.
//
// This exists so that ONE list answers "which skills have a film" on every
// surface. Three places used to answer it independently, all by guessing "not a
// review and not a gateway", and all three were wrong together the moment six
// skills were authored without films: Labs drew a play button on all six and
// pressing it signed a URL for an object that is not there.
//
// curriculum.ts stamps `hasFilm` from this while building SESSION_CURRICULUM, so
// the web bundle carries it, the export carries it to the backend, and the two
// cannot disagree.

export const FILMED_SKILLS: ReadonlySet<string> = new Set([
  'analog-pwm',
  'breadboarding',
  'brushless-and-foc',
  'building-circuits',
  'can-bus',
  'caps-at-work',
  'circuits-current',
  'clock-domains',
  'code-alarm',
  'debugging-safety',
  'driving-loads',
  'driving-motors',
  'embedded-bridge',
  'filters',
  'first-sketch',
  'inductive-protection',
  'leds-limiting',
  'light-alarm',
  'linear-regulation',
  'logic-gates',
  'making-dc',
  'meet-capacitor',
  'memory-and-sequencing',
  'numbers-and-levels',
  'opamp-amplifiers',
  'opamp-basics',
  'opamp-comparators',
  'opamp-real-world',
  'rc-charging',
  'reading-inputs',
  'reading-sensors',
  'resistance-ohms',
  'resonance-oscillators',
  'robot-control',
  'robot-sensing-comms',
  'rtos-basics',
  'sensor-fusion',
  'series-parallel',
  'signals',
  'speed-and-precision',
  'switches-control',
  'switching-regulation',
  'talk-debug',
  'the-transistor',
  'timing-555',
  'transistor-variety',
  'variable-resistance',
  'volatile-and-isrs',
  'what-arduino',
]);
